### ISSUE TITLE
Channel abort/kill/destroy

### ISSUE THREAD

**Issue by rptl** [net-ssh/net-ssh#100]
I just need to abort/kill/destroy a channel which is actually receiving data. 

channel.close method didn't work. It never closes the channel.

Here is the case: I am streaming data using a channel (tailing -f a file). 

This is a webapp, so if user reload his browser, this channel will keep opened on the server, no matter if I close or shutdown! the entire session. I still can see 'my tail' in ps.

I am looking for something pretty much like shutdown! method, but for channel. 

Is there any way to accomplish that?

**Comment by mfazekas** [comment]
CHannel close was changed in 3.0 if it's still an issue we need log and code to repro
