### ISSUE TITLE
PacketStream#next_packet(:nonblock)  is not able to sustain data arrival rate is more than one packet

### ISSUE THREAD

**Issue by huy** [net-ssh/net-ssh#113]
The current code first read all available data from socket into an internal buffer then pull out data from the buffer equivalent one packet so if data arrives at rate higher than size of one packet, it never been consumed, worse process spend most of time extend buffer and copy data into exhausting cpu and memory . 

The code should be probably modified like that 

```
def next_packet(mode=:nonblock)
  case mode
  when :nonblock then
    packet = poll_next_packet # pull out and return a packet if there is any
    return packet if packet

    fill if available_for_read? # if not fill a buffer and try again, give up if there is still no data in the buffer
    poll_next_packet
```

**Comment by mfazekas** [comment]
@huy do you want to open a PR for this?

**Comment by huy** [comment]
I have seen fix, still missing this part
---
 when :nonblock then
    packet = poll_next_packet # pull out and return a packet if there is any
    return packet if packet
