### ISSUE TITLE
Authentication Method determination can pick up a class from the root namespace

### ISSUE THREAD

**Issue by j0hnds** [net-ssh/net-ssh#119]
Ruby environment: 1.9.3 p327
In our codebase, we have a class defined with the name None in the root namespace. This initializer for this class accepts no parameters.

When we attempt to start a connection without specifying an :auth_methods option, we get an exception indicating that the initializer on the None class received 2 parameters rather than the expected 0.

The following line of code is where the exception is raised (in net/ssh/authentication/session.rb):

```ruby
method = Methods.const_get(name.split(/\W+/).map { |p| p.capitalize }.join).new(self, :key_manager => key_manager)
```

This line of code assumes that the class found will have the appropriate initializer. There is no protection here to ensure that the class found is actually the expected class. The search performed by the const_get method will always find the class in the root namespace - if it exists - before it finds the class in the Net::SSH::Authentication::Methods namespace.

The fix for our particular case was to specify the appropriate :auth_methods option to the start method. 

However, if another dev organization has a code base with any of the other auth_methods as a class in the root namespace they will encounter a similar issue. A particularly bad example would be if they wanted to use the 'password' :auth_method but had a class in their root namespace called 'Password'. 

This was a relatively difficult issue to troubleshoot. We had to put debug statements in the code to finally understand what was happening. 

Thanks for considering this issue.

**Comment by mfazekas** [comment]
Cant reproduce any longer with ruby 2.1
```ruby
class None
  end
 module Methods
  class None
    end
  class Foo
    end
  end
end
Methods.const_get(:None)
# Methods::None 
```
