### ISSUE TITLE
How to connect ssh from already created ssh session using net-ssh ruby.

### ISSUE THREAD

**Issue by maheshpj** [net-ssh/net-ssh#182]
I am using the net-ssh api for my ruby script but I am wondering how I can automate the below shell commands by ruby. In the below code bridge1 is the container server. In other words the box "1.1.1.1" is inside bridge2 and bridge2 is inside bridge3. So inorder to reach 1.1.1.1 I will have to ssh bridge1 first and than once I reached bridge2 than I will ssh 1.1.1.1
 ssh my.bridge1.com # logged into bridge1
 ssh my.bridge2.com # logged into bridge2 which is under bridge1
 ssh user@1.1.1.1 # logged into box which is under bridge2

I was referring some articles as below code. But could not figured out how to do multiple times ssh.

Net::SSH.start( HOST, USER, :password => PASS ) do|ssh| 
  ssh.exec('ls') do|ch, stream, data| 
    puts "Got this on the #{stream} stream: " 
    puts data 
  end 
end 
http://stackoverflow.com/questions/25687327/how-to-connect-ssh-to-ssh-in-ruby

**Comment by mfazekas** [comment]
you should be able to do ```ssh.exec('ssh ...')```
