### ISSUE TITLE
Net-SSH not compatible with Celluloid::IO / implements own IO.select logic

### ISSUE THREAD

**Issue by TiagoCardoso1983** [net-ssh/net-ssh#195]
I've been using net-ssh to connect to remote boxes and perform commands. Since this involves an API which has been integrated before with ruby's Net::Telnet library, I've used the [net-ssh-telnet](https://github.com/jasonkarns/net-ssh-telnet/) gem to leverage them.

I've been also trying to integrate [celluloid-io](https://github.com/celluloid/celluloid-io) to handle concurrent connections. Don't know if you're familiar with the project, but it basically handles event-based actors (Actors with a reactor inside). This means that, in theory, one actor could connect concurrently to multiple devices. 

In theory, because celluloid-io decorates the TCP/UDPSockets and implements its own Reactor and wait/select logic, while net-ssh uses IO::select calls directly within the channel. Since net-ssh-telnet opens a channel on the session, writes using Net::SSH::Connection::Channel#send_data and uses the callbacks to read to a buffer, it therefore waits on the IO::select calls, thereby not releasing the actor's reactor to other (possible) concurrent messages. I don't know if you're familiar with the Net::Telnet (also Net::SSH::Telnet) API, but basically, #cmd calls #puts (sends command) and #waitfor (waits on the response). On Net::SSH::Telnet, #puts sends to command on the channel Net::SSH::Connection::Channel#send_data; #waitfor reads from the socket using Net::Connection::Connection::Session#process (which calls IO::select). 

Now, I know that I already have a Net::SSH-decorated socket at my disposal.This socket is decorated with the Net::SSH::Transport::PacketStream and Net::SSH::BufferedIO modules. How could I (using the existing API) write to the socket and reading from the socket directly (bypassing the channel and any IO::select calls)? I would like something as simple as this (adapted already to Celluloid::IO):

https://github.com/pberndt/celluloid-io/blob/73060d15f175b1c773606c22ea155be91dc88c99/lib/celluloid/net/telnet.rb#L636-L643
https://github.com/pberndt/celluloid-io/blob/73060d15f175b1c773606c22ea155be91dc88c99/lib/celluloid/net/telnet.rb#L586

Simple calls to Socket#write and Socket#readpartial. How can I do it using the Buffered::IO and Packetstream APIs?

Just for the record, I gave up using the Channel calls because I cannot really move away from calling any method that uses IO::select (be it #dispatch_incoming_packets, Session#process and all that).

**Comment by mfazekas** [comment]
What is the usecase? Do you want the full net-ssh over celluloid-io?
The main place we use IO.select is process. Can't we just make process to use celluliod-io's reactor? 
(i'm not familiar with celluloid-io)

**Comment by TiagoCardoso1983** [comment]
Unfortunately not really :/ net-ssh uses IO::select, celluloid-io uses it's own reactor based underneath on libev or NIO on JRuby. Since writing this issue I've succeeded in "monkey patching" net-ssh to (not totally fully) support it. I'm thinking of maybe writing a small library  based on some parts of net-ssh. Point is that net-ssh IMO should behave as a thin wrapper modelled on Net::Telnet and leave concurrency strategies to other libraries. It's debatable, though.

**Comment by mfazekas** [comment]
there is WIP event loop abstraction see https://github.com/net-ssh/net-ssh/pull/309
