### ISSUE TITLE
Missing implementation KexAlgorithm curve25519-sha256@libssh.org

### ISSUE THREAD

**Issue by voidus** [net-ssh/net-ssh#211]
Although https://github.com/net-ssh/net-ssh/blob/master/lib/net/ssh/transport/algorithms.rb#L62 adds it to the known algorithms, there is no implementation in https://github.com/net-ssh/net-ssh/blob/master/lib/net/ssh/transport/kex.rb

**Comment by voidus** [comment]
Additionally, a fatal Error occurs if a ed25519 hostkey is used:

voyd@kanne> vagrant provision
==> sulfur: Running provisioner: shell...
An error occurred in the underlying SSH library that Vagrant uses.
The error message is shown below. In many cases, errors from this
library are caused by ssh-agent issues. Try disabling your SSH
agent or removing some keys and try again.

If the problem persists, please report a bug to the net-ssh project.

curve name mismatched (`<random garbage>' with `')

**Comment by mfazekas** [comment]
ed25519 should have removed in 2.9.2 so it should work can you try 2.9.2.rc2?
I'll remove curve25519-sha256@libssh.org too.

**Comment by mfazekas** [comment]
Can you try with 2.9.2.rc3? It no longer advertises curve25519-sha256@libssh.org as supported.

**Comment by voidus** [comment]
Jup, now it just tells me "could not settle on host_key algorithm".

**Comment by voidus** [comment]
net-ssh should really support curve25519-sha256 though. It's the upcoming default algorithm and currently the best bet for reliable security.

**Comment by mfazekas** [comment]
If you add a host_key that supported by current net-ssh it works right?

We'll work implemnting curve25519-sha256 and PR-s are more than welcome. But in the meantime it's much better to say it's not supported than to say it's supported, then not being able to handle it.

**Comment by voidus** [comment]
Yes, it works if a rsa host key is available.
