### ISSUE TITLE
Patch 2.9.2 introduced a bug

### ISSUE THREAD

**Issue by esciara** [net-ssh/net-ssh#218]
Don't know exactly what is the cause of it, but reverting to `2.9.1` resolved the issue opscode/chef-provisioning#263. This needs investigation (which I cannot do).

**Comment by mfazekas** [comment]
see https://github.com/opscode/chef-provisioning/issues/263#issuecomment-69855518

**Comment by mfazekas** [comment]
Bug in chef https://github.com/opscode/chef-provisioning/issues/263#issuecomment-69855518
