### ISSUE TITLE
Passes options hash to third argument when given a proxy on start

### ISSUE THREAD

**Issue by TiagoCardoso1983** [net-ssh/net-ssh#220]
This came from here: https://github.com/celluloid/celluloid-io/issues/99 .

Basically the issue seems to me that since version 2.8.0 the options has is passed around as the third argument. Was this intentional? A Proxy should mimic the raw TCPSocket API, I don't think this would work. I actually tried passing TCPSocket has a proxy, also didn't work!

```ruby
Net::SSH.start('localhost', 'localuser') # all good
Net::SSH.start('localhost', 'localuser', proxy: Celluloid::IO::TCPSocket) # not good
Net::SSH.start('localhost', 'localuser', proxy: TCPSocket) # surprisingly also not good
```

This [line](Net::SSH.start('localhost', 'localuser', proxy: Celluloid::IO::TCPSocket) # not good) seems to be causing it. It was introduced in this [commit](https://github.com/net-ssh/net-ssh/commit/b84becc741e233fb4182e02b2ef3f194bc29174c). It seems an error, as the block doesn't match anymore the inlined version.

Can you confirm this? I could submit a patch. I would also suggest a patch version for 2.8.x.

**Comment by mfazekas** [comment]
Yes you're right. Tests needs to be added.

**Comment by mfazekas** [comment]
Sorry i was misreading that patch. Yes it broke passing ```TCPSocket``` or ```Celluloid::IO::TCPSocket``` to proxy argument, but it was never supported just happen to work.  (That is it was a undocumented feature that 2.8 and 2.9 broke.)

You should be able to use TCPSocket like that:
```
class TCPSocketAsProxy
   def self.open(host,port,connection_options={})
      TCPSocket.open(host,port)
   end
end
```

**Comment by mfazekas** [comment]
You're using undocumented "feature" which is expected to break between versions. Since there is workaround i'll close this but.

**Comment by TiagoCardoso1983** [comment]
Nice, thx for the replies. Is there a way to see the feature documented somewhere? It's just because people tend to be misled to belive the proxy parameter behaves like the proxy parameter from the stdlib Net::Telnet library, which can be passed a class.

**Comment by mfazekas** [comment]
@TiagoCardoso1983 what is your usecase? Is this #195?

**Comment by TiagoCardoso1983** [comment]
Yup, it was. Still... I've just seen ruby source code for net-telnet, and it actually expects an instance and not the class. Maybe we can skip the documentation, I think I mislead myself in this. Thx for the replies, though.
