### ISSUE TITLE
ruby 1.8 support

### ISSUE THREAD

**Issue by mfazekas** [net-ssh/net-ssh#223]
2.9.2 breaks ruby1.8 with this commit, (noone complained yet)
https://github.com/net-ssh/net-ssh/commit/b7dd7ea6dc045934f6e9aa13498ec2f63af23515

@delano do we want to support ruby 1.8? If so we need to add it to travis.
https://github.com/net-ssh/net-ssh#ruby-18-support

**Comment by carlhoerberg** [comment]
I think it's time to move on. Ruby 1.8 haven't gotten security updates for i don't know how many years. Not even [Ruby 1.9 is officially supported anymore](https://www.ruby-lang.org/en/news/2015/02/23/support-for-ruby-1-9-3-has-ended/).

**Comment by oliverklee** [comment]
So this issue can be closed, I think.
