### ISSUE TITLE
Authentication hangs forever when password is wrong since keeps asking

### ISSUE THREAD

**Issue by MarioRuiz** [net-ssh/net-ssh#227]
Now when 2.9.2 and 2.9.3 beta versions.... everytime i supplied an incorrect password to the server... it displays:
"Text will be echoed in the clear. Please install the HighLine or Termios liraries to suppress echoed text."
And hangs forever since is asking to introduce the password with 2.9.1 this was the output:
D, [2015-02-03T11:30:06.423468 #13144] DEBUG -- net.ssh.authentication.session[1519278]: trying password
E, [2015-02-03T11:30:06.423468 #13144] ERROR -- net.ssh.authentication.session[1519278]: all authorization methods failed (tried none, publickey, password)
C:/Ruby200/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.1/lib/net/ssh.rb:219:in `start': Authentication failed for user root@myserver (Net::SSH::AuthenticationFailed)
	from xbr.rb:10:in `<main>'

and now... the error is this one.. and hangs forever asking for the pwd:
D, [2015-02-03T11:30:44.477273 #5724] DEBUG -- net.ssh.authentication.session[14541fc]: trying password
Text will be echoed in the clear. Please install the HighLine or Termios libraries to suppress echoed text.
root@myserver's password:>

**Comment by mfazekas** [comment]
Thanks for the report. Are you using capistrano? Why can't you enter the password?

A workaround to switch back to previous mode where it will not ask for password is using the ```number_of_password_prompts: 0``` option.

**Comment by MarioRuiz** [comment]
thanks for the answer... nope... i am using just pure ruby and the net-ssh library, the problem is we are testing the server with wrong passwords in purpose 

I tried supplying these options:
:auth_methods => [ 'password' ], :number_of_password_prompts => 0
and it works now thanks.

**Comment by jeremy-israel** [comment]
Just came across the `non_interactive: true` option. This did the trick for me.
