### ISSUE TITLE
Separate/modularize known_hosts parsing

### ISSUE THREAD

**Issue by TiagoCardoso1983** [net-ssh/net-ssh#232]
I'm using net-ssh in a concurrent scenario where I'm connecting to many hostnames in serial. This is making my known_hosts file (understandably) massively big, which makes the whole connection slow. But worse than that, the reading is happening x + y times, being x the number of hostnames I'm connecting to, and y the number of times that the known_hosts file is parsed after calling Net::SSH.start . My current known_hosts file sample has (gulp!) over 18000 entries. 

Now, I guess that maybe net-ssh wasn't thought for such scenarios, but I'm thinking whether one could easily modularize the whole known hosts file parsing, in that maybe the file would be held in memory (double gulp) and passed to the session initialization, maybe make it an additional parameter which is passed to the session initialization. I don't know, these are just suggestions and ideas. But currently as things stand, it's a bit unbearable, as parsing a > 18000-line file is causing me a huge number of EOF and broken pipes all around. Is there a short-term solution for it or should one discuss about possible solutions?

I assume that all ssh configuration files suffer from the same issue, that is, they are loaded during the session establishment flow.

**Comment by mfazekas** [comment]
As a workaround you should be able to read the known hosts yourself then when connection generate a new temp file with just he needed entry and use :user_known_hosts_file to specify that host file.

**Comment by carlhoerberg** [comment]
Or disable host checking completely with `paranoid: false`

**Comment by TiagoCardoso1983** [comment]
@mfazekas I thought about that as a possible workaround, but, in the case where I will access all hostnames concurrently, the penalty will still hold. In the scenario I'm working with, that's a fairly doable scenario. 
@carlhoerberg wouldn't that defeat the purpose of using ssh in the first place? I'd be then susceptible to man-in-the-middle attacks, right? If I have to sacrifice security over performance, wouldn't I be then just ok with plain telnet?

**Comment by carlhoerberg** [comment]
Well, with SSH your at risk of MITM on every first connect to a new server unless you've collected the host pub key beforehand through an out-of-band method, but maybe you're doing that?

But if you're using ssh key authentication (not password authentication) you still can't be MITMed as the MITM attacker (hopefully) don't have your private key, and the real server only accepts your private key. The MITM can still fake being a server and listen to the commands you're sending (which can be bad enough), but they won't reach the real server. 

Please correct me if I'm wrong.

**Comment by TiagoCardoso1983** [comment]
@carlhoerberg you're right on your assumption. the known_hosts is (or will be) pre-fetched using an out-of-band mechanism. 

You're also correct on the public key authentication strategy, but our solution specifies password-based authentication, as not only the login/password credential pair is the same in all devices, it has support multiple credentials. Doing that with public keys is unfeasible, as every login will have a different public key per device.
