### ISSUE TITLE
send_env doesn't work as expected

### ISSUE THREAD

**Issue by rickhull** [net-ssh/net-ssh#236]
minimal test case here: https://gist.github.com/rickhull/d9a80efbe66fd0da7c15

note:
1. FOO is in the local env
2. `SSH.start` options have: `send_env: ['FOO']`
3. `env` on the remote side doesn't show FOO

Can anyone confirm?  Am I misunderstanding something about this feature?  This is on net-ssh 2.9.2

`export FOO=foo` locally does not help

**Comment by rafecolton** [comment]
+1 `:send_env` does not work as expected

**Comment by carlhoerberg** [comment]
Of the top of my head, the server must whitelist which variables that can
be set.

**Comment by carlhoerberg** [comment]
See `AcceptEnv` in [the man page for sshd_config](http://manpages.ubuntu.com/manpages/trusty/en/man5/sshd_config.5.html) 

This issue can be closed.

**Comment by rickhull** [comment]
Good point.  I'll retest with that setting on the server.  Closing.
