### ISSUE TITLE
typo in docs

### ISSUE THREAD

**Issue by zeroecco** [net-ssh/net-ssh#244]
on page:
http://net-ssh.github.io/ssh/v2/api/classes/Net/SSH/Service/Forward.html

there is a typo around the forward_agent:

```
Net::SSH.start("remote.host", "me", :forwrd_agent => true) do |ssh|
  ssh.open_channel do |ch|
    # agent will be automatically forwarded by this point
  end
  ssh.loop
end
```
should be:
```
Net::SSH.start("remote.host", "me", :forward_agent => true) do |ssh|
  ssh.open_channel do |ch|
    # agent will be automatically forwarded by this point
  end
  ssh.loop
end
```

**Comment by sschuberth** [comment]
@zeroecco This was fixed in afc95daf8e89e3d02275d5bcf5ab3fe8e57e9d60, so would you mind closing the issue?

**Comment by mfazekas** [comment]
new docs published to http://net-ssh.github.io/net-ssh/Net/SSH/Service/Forward.html

**Comment by zeroecco** [comment]
@sschuberth I didn't see your comment to me in July, would have replied if I did.
