### ISSUE TITLE
Does not respect $stdout/in.tty when prompting

### ISSUE THREAD

**Issue by leehambley** [net-ssh/net-ssh#254]
Also, has a nil exception if the stdin is `/bin/false` as you get a `undefined method chomp for nil class`. I may try and work out a patch for this. As the similar error has surfaced in SSHKit and Capistrano through carelessness (and I have to fix both of those too)

**Comment by mfazekas** [comment]
Thanks, for the report. Can you provide more details and usecase?
2.10 now introduces a non_interactive mode, which means we don't prompt. In case we do prompt then an exception with stdin redirected to /bin/false is desirable IMO, but exception might be improved/more specific.

See also: https://github.com/net-ssh/net-ssh/pull/234

**Comment by leehambley** [comment]
hey @mfazekas kudos for the fast response, sorry I missed #234 - although not a 100% duplicate, maybe if I'm able to solve this I could cure both.

> Thanks, for the report. Can you provide more details and usecase?

It's Capistrano in a CI tool which doesn't provide a TTY, the CI tools is one my company is building (I'm the Capistrano maintainer) and can be found at https://www.harrow.io/

To cut a long story short, we run into this kind of thing all the time with software that is poorly designed, or simply was never supposed to be used this way, surprisingly enough Git is a really bad offender, so alone for git we essentially run `/bin/false | the_user_script.sh` in order that anything careless enoguh to read from the world's stdin (not affecting the case internally that people do a local redirection to pipe something into a program).

Initially two surprising things:

1. Apparently due to some changes on your side Capistrano now prompts for passwords on auth failure (it never used to) - which I need to disable from outside, I guess I can restrict the auth methods, rather than simply using `Net::SSH.start`
1a. I need the ability to make sure this never, ever happens in a CI environment or where there is no tty 
2. The warning about missing termcap and echoing in the cleartext is a bit obnoxious, and unnecessary

I wanted to suggest that you might use `io/console` which is in the Ruby 1.9+ standard lib, but I don't know what your policy on support for 1.9 is, given that we also have ask/prompt in Capistrano that has the same expectations of echoing safely only if we have a readlineish library around, I'd be glad of one dependency fewer to deal with.

**Comment by mfazekas** [comment]
> Apparently due to some changes on your side Capistrano now prompts for passwords on auth failure (it never used to)

This is because of a strange behaviour in Capistrano 1.x. Now as we do ask for password in case of auth failure for both ```password``` and ```keyboard-ineractive```
https://github.com/net-ssh/net-ssh/issues/145

> I need the ability to make sure 1. never, ever happens in a CI environment or where there is no tty

pass ```non_interactive: true``` as net-ssh option this will cause net-ssh not to ask for passwords.

> The warning about missing termcap and echoing in the cleartext is

same as above if you pass non_interactive then no prompt will be made so no warning

>I wanted to suggest that you might use io/console

we already 1.9+ (actually 2.0+ in 2.10, since 1.9 is EOL already)

**Comment by leehambley** [comment]
> pass non_interactive: true as net-ssh option this will cause net-ssh not to ask for passwords.
> ... 
> same as above if you pass non_interactive then no prompt will be made so no warning

Awesome, sounds good :) I hoped it would be that easy, I just have to maybe deal with some fallout from people who've come to rely on this behaviour who'll want it back! Presently it's non-trivial to pass options to Net::SSH, however we do expose `ssh_options`… the hash that Net::SSH merges with the local `~/.ssh/config`, etc.

Regarding `io/console`, this was the bit I thought was nice 

 - http://ruby-doc.org/stdlib-2.0.0/libdoc/io/console/rdoc/IO.html#method-i-noecho

**Comment by mfazekas** [comment]
So we use ```io/console``` now. Also there is a new password_prompt option where you can supply a custom logic for password prompting. It should be now possible to password caching that way.
