### ISSUE TITLE
undefined method `recv' with a proxy command

### ISSUE THREAD

**Issue by willbryant** [net-ssh/net-ssh#255]
For a long time, we've found that when we start up and connect to a bunch of servers through ProxyCommand gateways (AKA jump hosts), every once in a while it fails with the following error:

```
NoMethodError: undefined method `recv' for #<IO:fd 55>
```

It occurs something like 5% of the time, and we're typically connecting to ~25 hosts at once, so I think it really only occurs about 0.2% of the time.  Pretty weird.

This is a bit of a tracking ticket, I'm going to try and get this down to something we can reproduce and try to fix it or workaround it.

**Comment by willbryant** [comment]
The code that injects the recv method lives in the open method in command.rb:

```ruby
      class << io
        def send(data, flag)
          write_nonblock(data)
        end

        def recv(size)
          read_nonblock(size)
        end
      end
      io
```

I can't see how it is possible for recv not to be present, but if I add a puts in, I can see that sometimes it isn't!:

```
      class << io
        def send(data, flag)
          write_nonblock(data)
        end

        def recv(size)
          read_nonblock(size)
        end
      end
      puts "*"*300 unless io.respond_to?(:recv)
      io
```

This outputs the *s before it fails with the NoMethodError.

That looks kinda like a Ruby VM bug to me.

**Comment by mfazekas** [comment]
See https://github.com/net-ssh/net-ssh/pull/240
should be worked around in 2.10.beta

**Comment by willbryant** [comment]
Reproduced also on Ruby 2.2.2.
