### ISSUE TITLE
Waiting forever in recv

### ISSUE THREAD

**Issue by rubemz** [net-ssh/net-ssh#256]
We noticed in our production environment that some sidekiq workers get stuck waiting recv() method to respond.

https://github.com/net-ssh/net-ssh/blob/master/lib/net/ssh/buffered_io.rb#L65

```ruby
 def fill(n=8192)
      input.consume!
      data = recv(n)
      debug { "read #{data.length} bytes" }
      input.append(data)
      return data.length
    end
```

I'm wondering if anyone has any advices on how to handle this. Also, how could  I set a timeout for the socket?

Thanks

**Comment by mfazekas** [comment]
We should be getting to .fill if and only if the select returned it as a readable channel. Not sure why it's blocking. If the issue is still there reopen we'd also  need stacktrace and full log.
