### ISSUE TITLE
Could not find net-ssh-2.10.0 in any of the sources

### ISSUE THREAD

**Issue by ELouisYoung** [net-ssh/net-ssh#263]
remote:        Fetching gem metadata from https://rubygems.org/........
remote:        Fetching version metadata from https://rubygems.org/...
remote:        Fetching dependency metadata from https://rubygems.org/..
remote:        Could not find net-ssh-2.10.0 in any of the sources
remote:        Bundler Output: Fetching gem metadata from https://rubygems.org/........
remote:        Fetching version metadata from https://rubygems.org/...
remote:        Fetching dependency metadata from https://rubygems.org/..
remote:        Could not find net-ssh-2.10.0 in any of the sources
remote:  !
remote:  !     Failed to install gems via Bundler.
remote:  !
remote:
remote:  !     Push rejected, failed to compile Multipack app
remote:

**Comment by mfazekas** [comment]
Hi sorry i've yanked net-ssh 2.10.0 (see https://github.com/net-ssh/net-ssh/pull/259) you can either use 2.10.1.rc1 or use  2.9.2 for now

**Comment by ELouisYoung** [comment]
thanks, it is working with rubygems resolving to 2.9.2 automatically
