### ISSUE TITLE
NET::SSH tries all keys from agent before specified keys

### ISSUE THREAD

**Issue by arnaud-lb** [net-ssh/net-ssh#27]
I seems that `NET::SSH.start(..., :keys => [list of keys])` is trying all keys from the agent before trying the keys specified in the `:keys` option.

Default configuration of many SSH servers it to abort the connection after a few failed auth attempts (e.g. 3 or 5). As a result, if too many keys are tried before trying the right one, the connection is aborted. I have more than 5 keys in my `~/.ssh`, all of them are tried before trying the keys I specified, and as a result `NET::SSH.start` is not working anymore for me.

Here is a stripped-down script I used to test this:

``` ruby
#!/usr/bin/ruby

require 'rubygems'
require 'net/ssh'

Net::SSH.start('hostname', 'user', :verbose => Logger::DEBUG, :keys => ['~/id_rsa']) do |ssh|
  output = ssh.exec!("hostname")
  puts output
end
```

The bug seems to come from [`KeyManager.each_identify`](https://github.com/net-ssh/net-ssh/blob/6812153a2d1e84853114622b3d9bacb4e7696bb4/lib/net/ssh/authentication/key_manager.rb#L97), which is returning keys from the agent before user specified keys.

I'm using net-ssh 2.1.4

**Comment by mfazekas** [comment]
keys_only should be a fix for this
