### ISSUE TITLE
Windows Putty Pageant Conflict

### ISSUE THREAD

**Issue by AlexYudaev** [net-ssh/net-ssh#272]
Hello all,
i use ruby script on windows os,When Putty  Pageant shut down, everithing work perfectly. But if it's running i get this error:  

C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/net-ssh-2.9.3.beta1/lib/net/ssh/authentication/pageant.rb:355:in `send_query': Creation of file mapping failed with error: 998 (Net::SSH::Exception)

Can i do something?

**Comment by jamgregory** [comment]
Hi @AlexYudaev. I think you might be experiencing the same issue as mentioned in issue #180.

**Comment by mfazekas** [comment]
@AlexYudaev have you tried as the 3.0.0? (But https://github.com/net-ssh/net-ssh/pull/239 should be already in 2.9.3beta1)

ERROR_NOACCESS 998 (0x3E6)
Invalid access to memory location.

https://msdn.microsoft.com/en-us/library/windows/desktop/ms681388(v=vs.85).aspx

https://github.com/net-ssh/net-ssh/blob/master/lib/net/ssh/authentication/pageant.rb#L351

https://msdn.microsoft.com/en-us/library/windows/desktop/aa366537(v=vs.85).aspx

**Comment by mfazekas** [comment]
reopen if this is still an issue with 3.0.2
