### ISSUE TITLE
Undefined method `tcp' on Socket in Rubinius

### ISSUE THREAD

**Issue by saizai** [net-ssh/net-ssh#276]
https://github.com/net-ssh/net-ssh/blob/master/lib/net/ssh/transport/session.rb#L70 requires Socket.tcp.

This raises an error in rbx-2.5.8: 

    kernel/delta/kernel.rb:78:in `tcp (method_missing)'

See https://github.com/rubinius/rubinius/issues/3510

**Comment by carlhoerberg** [comment]
The best you can do is to help Rubinius implement the API, you can see how it's implemented in Ruby here: https://github.com/ruby/ruby/blob/ruby_2_2/ext/socket/lib/socket.rb#L314

**Comment by mfazekas** [comment]
shoud be fixed by now see https://github.com/rubysl/rubysl-socket/issues/11
