### ISSUE TITLE
Confusing regarding 2.x vs. 3.x

### ISSUE THREAD

**Issue by fingolfin** [net-ssh/net-ssh#277]
So I just learned about Net::SSH, and went to this repository. And was greeted by this big fat message:
```
Net::SSH 2.x

Please note: this project is in maintenance mode. It is not under active development
but pull requests are very much welcome. Just be sure to include tests! – delano
```
Then I look at the list of releases, and see a 3.0.0 release, and a 3.0.1 release. Huh? A look at CHANGES.txt also indicates the existence of a 3.0.1 release, though not a 3.0.0 (only a 3.0.0.rc1); interestingly, the 3.0.1 release announces breaking changes (curious, since the entry for 3.0.0rc1 mentions semver...).

So I think, "Let's take a look at the official website http://net-ssh.github.io/ surely that will indicate what's going on." But no, it doesn't mention 3.x... In fact following the link to the documentation, http://net-ssh.github.io/net-ssh/ tells me 2.9.1 is latest -- so it doesn't seem to "know" about 2.9.2 and 2.10.0, which exist according to CHANGES.txt..

So: What is going on here? Am I supposed to use 2.9.1? Or 2.10.0? Or 3.0.1? What are the (future) plans with respect to backwards compaibility? Is someone going to update the README and homepage, perhaps with some advice to potential users of the lib as to what Net::SSH version to use?

**Comment by mfazekas** [comment]
The project tries to follow semver principles. I've updated README, and we'll update the webpage as well. As for directions use the latest and greatest net-ssh! (unless you have reason not to)

**Comment by fingolfin** [comment]
Hmm, but if you follow semver, then you can't introduce a major breaking change in version 3.0.1, can you? It would have to be called 4.0.0 :). But perhaps the change was already introduced in 3.0.0 and the CHANGES files is just wrong?

Anyway, thanks for at least improving the README, it now doesn't look quite as weird.

**Comment by mfazekas** [comment]
3.0.1 is the first stable release in the 3.* series, and according to semver prerelease versions "might not satisfy the intended compatibility requirements" so what was 3.0.0.rc1 is not really relevant. Note that there was practically no 3.0.0 released - (it was yanked shortly after it's release), so i've made that small incompatible change in 3.0.1, making 4.0.0 would have probably even more confusing.

**Comment by fingolfin** [comment]
Ahh, now I understand! Thanks for the clarification.

So, perhaps the CHANGES.txt could be update to reflect that? E.g. by saying "3.0.0: withdrawn shortly after release"?
