### ISSUE TITLE
Net::SSH does not fall-back to using local user's username

### ISSUE THREAD

**Issue by mexisme** [net-ssh/net-ssh#281]
We tried to connect to another host without setting the username, e.g:
```
require 'net/ssh'
Net::SSH.start(HOST, nil) do |ssh|
  ssh.exec!('env')
end
```
However, instead of it defaulting to trying to connect to said `HOST` with the local user's username, Net::SSH tried to connect with an empty username:
```
Text will be echoed in the clear. Please install the HighLine or Termios libraries to suppress echoed text.
@HOST's password:
@HOST's password:
@HOST's password:
Net::SSH::AuthenticationFailed: Authentication failed for user @HOST
	from /usr/local/rvm/gems/ruby-2.2.1@kiwiops/gems/net-ssh-3.0.1/lib/net/ssh.rb:239:in `start'
	from (irb):2
	from /usr/local/rvm/rubies/ruby-2.2.1/bin/irb:11:in `<main>'
2.2.1
```

We don't normally have an `~/.ssh/config` file, but did discover it will connect correctly with the following added:
```
Host *
  User USER
```

Is this expected behaviour?
If so:  we know we could use `$ENV['USER']` in the `Net::SSH.start()` (or similar system calls) is there any other way to get Net::SSH to default/fall-back to the local user's username?

Thanks

Will

NB: `HOST` and `USER` have been changed to protect the innocent.

**Comment by mfazekas** [comment]
You should be able to use Etc.getlogin. Passing empty user instead when user is nil is not an usefull feature, so this is a meaningfull feature request, PR-s welcome.

**Comment by mexisme** [comment]
> You should be able to use Etc.getlogin

Yeah, sure. `$ENV['USER']` was an easy example.


> Passing empty user instead when user is nil is not an usefull feature, so this is a meaningfull feature request, PR-s welcome.

OK, I'll take a look tonight.

**Comment by mexisme** [comment]
Does https://github.com/net-ssh/net-ssh/pull/282 fix it appropriately, @mfazekas ?
