### ISSUE TITLE
Vagrant UP Problems

### ISSUE THREAD

**Issue by gocanto** [net-ssh/net-ssh#301]
Hey, 

I am having this problem trying to run my homestead up:

An error occurred in the underlying SSH library that Vagrant uses.
The error message is shown below. In many cases, errors from this
library are caused by ssh-agent issues. Try disabling your SSH
agent or removing some keys and try again.

If the problem persists, please report a bug to the net-ssh project.

any suggestion?

**Comment by mfazekas** [comment]
> The error message is shown below.

Can you post the error message here?

**Comment by gocanto** [comment]
I would start from fresh.

Clone the repo again into your home directory then you can do `bash init.sh` then `vagrant up` and now I am getting this error: 


An error occurred in the underlying SSH library that Vagrant uses.
The error message is shown below. In many cases, errors from this
library are caused by ssh-agent issues. Try disabling your SSH
agent or removing some keys and try again.

If the problem persists, please report a bug to the net-ssh project.

timeout during server version negotiating

**Comment by mfazekas** [comment]
Sorry which repo, what os vagrant version are you using? This sounds like the ssh server is not running on the vagrant vm. Are you sure that ssh is up? Can you ssh to it using regular ssh commands?

**Comment by gocanto** [comment]
* Repo: https://github.com/laravel/homestead.git
* OS: Mac OS "El Capitan"

The ssh is running because the regulars commands are working ...

**Comment by mfazekas** [comment]
What version of vagrant? Also can you provide the logs requested to the related vagrant issue? 
https://github.com/mitchellh/vagrant/issues/6812

What do you mean by regular commands? Can you use /usr/bin/ssh to connect to vagrant vm?

**Comment by mfazekas** [comment]
I'm closing this now until we have some indication this is a net-ssh issue. 

Looking at the logs posted at:
https://gist.github.com/akaSStalkALEX/6315b40683fc7c9d64cc
there is one timeout in negotiate error then a few disconnect, then succesfull connects. So i assume if VM boots up slowly then connecting before ssh fully started on server causes those.

**Comment by gocanto** [comment]
Thanks for helping me @mfazekas it was a problem with my `vagrant` version.

**Comment by hellsinglord22** [comment]
@gocanto what vagrant version do you use now to solve the problem ?
