### ISSUE TITLE
Forwarding Service ignores :proxy option from the session it's coming

### ISSUE THREAD

**Issue by TiagoCardoso1983** [net-ssh/net-ssh#304]
Don't know if this is by design, but port forwarding opens a raw TCPSocket. 

Shouldn't it be using the proxy coming from the main session?

https://github.com/net-ssh/net-ssh/blob/edd7335d42630aec1ad5b18542e863608bb4ed39/lib/net/ssh/transport/session.rb#L67-L72

https://github.com/net-ssh/net-ssh/blob/edd7335d42630aec1ad5b18542e863608bb4ed39/lib/net/ssh/service/forward.rb#L346

**Comment by mfazekas** [comment]
This is by design. 

> ProxyCommand
> Specifies the command to use to connect to the server.

**Comment by TiagoCardoso1983** [comment]
this is not necessarily related to the protocol, just with the choice of socket type. Using the proxy option, I can pass something quacking like tcp socket, like a em-synchrony TCPSocket or a celluloid-io TCPSocket, and make it work within an event loop (yes, with other patches, we've discussed this somewhere else). By using the raw ruby TCPSocket you effectively break the event loop interaction. 

I don't know if the proxy option is the best for this use case, but currently net-ssh doesn't specify an option for providing the socket class. 

P.S.: maybe keep the ticket open until having the issue figured out?

**Comment by mfazekas** [comment]
the proxy option is for proxy and we don't want to proxy local sockets, just connection to the server. We might invent another option like :socket_factory but it's unrelated to proxy.

**Comment by TiagoCardoso1983** [comment]
yes, we came to that conclusion when discussion the best way to pass celluloid-io TCPSockets and you suggested the :proxy option as a workaround. 

I don't think there's consensus for this use-case in ruby libraries, but the next best thing I can come up with is what net-telnet is doing: https://github.com/ruby/net-telnet/blob/master/lib/net/telnet.rb#L331-L338 . Then again, is not a lot different from what net-ssh is already doing, minus unsupported forwarding by protocol. I'd be ok for a socket_factory option.
