### ISSUE TITLE
Object#timeout is deprecated, use Timeout.timeout instead.

### ISSUE THREAD

**Issue by bparanj** [net-ssh/net-ssh#305]
In Ruby 2.3.0, net-ssh version 2.9.3 gives the deprecation message:

/.rvm/gems/ruby-2.3.0@lafon/gems/net-ssh-2.9.2/lib/net/ssh/transport/session.rb:67:in `initialize': Object#timeout is deprecated, use Timeout.timeout instead.

**Comment by mfazekas** [comment]
Have you tried 3.0.2?
