### ISSUE TITLE
Net::SSH::Config.load parses ssh-config | differently

### ISSUE THREAD

**Issue by bascht** [net-ssh/net-ssh#310]
## bug.rb
```ruby
#!/usr/bin/ruby

require 'net/ssh'

puts Net::SSH::Config.load('./working.conf', 'example.com').inspect()
puts Net::SSH::Config.load('./working.conf', 'unrelatedhost.com').inspect()
puts Net::SSH::Config.load('./broken.conf', 'unrelatedhost.com').inspect()
```

## working.conf
```ini
Host example.com
  Hostname "WORKING"

Host example.org
  Hostname "WORKING"
```

## broken.conf
```ini
Host example.com | example.org
  Hostname "BROKEN"
```

### Output
```
$ ruby bug.rb 
{"host"=>"example.com", "hostname"=>"WORKING"}
{"host"=>"unrelatedhost.com"}
{"host"=>"unrelatedhost.com", "hostname"=>"BROKEN"}
```

while the ssh client parses the conf correctly:
```
$ ssh -F broken.conf unrelatedhost.com
ssh: Could not resolve hostname unrelatedhost.com: Name or service not known
```
Reproducible with ruby-2.1.8 and net-ssh-3.0.2

**Comment by mfazekas** [comment]
I don't think that ```|``` is a valid pattern, it confuses net-ssh likely here.
https://github.com/net-ssh/net-ssh/blob/master/lib/net/ssh/config.rb#L235

the issue is that ``` 'asd' =~ /^|$/ ``` matches anything. We need to use Regex#quote rather than ad hoc quote we do see:
http://ruby-doc.org/core-1.9.3/Regexp.html#method-c-quote

**Comment by mfazekas** [comment]
So do not use the ```I``` in host expressions it's not neccesary for openssh and confuses net-ssh

**Comment by bascht** [comment]
@mfazekas Now that you mention it, even `man 5 ssh_config` explicitly recommends white space. I just "inherited" the SSH config and somehow thought there was a special meaning to it. Thanks for digging through the code! :bow:
