### ISSUE TITLE
Opening channels making the session closing procedure block

### ISSUE THREAD

**Issue by TiagoCardoso1983** [net-ssh/net-ssh#312]
Tested against 3.0.2:

```ruby
require 'net/ssh'                       
ssh = Net::SSH.start("localhost", ENV["USER"])   
puts "ssh session established"                   
channel = ssh.open_channel                       
puts "channel opened"                            
channel.close                                    
puts "channel closed"                            
ssh.close # hint: it blocks here            
puts "ssh session closed"       
```

If I don't open a channel, it closes cleanly. If I refrain from closing the channel, it also blocks. 

Why do I think this is breaking? If you look at the channel close procedure, it sends a  CHANNEL_CLOSE message and proceeds to cleaning up the channel from the session. However, the session only cleans up the channel **if** the channel has been locally and remotely closed. As far as I understood, the process above counts as a local close. The remote close is activated only when the server we are communicating to [sends a close packet](https://github.com/net-ssh/net-ssh/blob/4b36d0c08fc55d45ca4025daf4bad5c8349efcb4/lib/net/ssh/connection/session.rb#L590). 

Still, it does seem like a bug that I can't properly close the session if the channel is there, specially when it hangs.

**Comment by mfazekas** [comment]
It's kind of looks like works as documented. When you get to the second close channel is still opening, but not yet opened.

https://github.com/net-ssh/net-ssh/blob/master/lib/net/ssh/connection/channel.rb#L294

> nor does it do anything if the channel has not yet been confirmed open 

On the other hand with the [change of close not actually sending anything just setting the state which will be sent by process](https://github.com/net-ssh/net-ssh/commit/4b36d0c08fc55d45ca4025daf4bad5c8349efcb4). This restriction of not close doing nothing on not yet opened channels is not neccesary.
