### ISSUE TITLE
Net::SSH::Config#translate requires downcase for hash key

### ISSUE THREAD

**Issue by miminashi** [net-ssh/net-ssh#313]
https://github.com/net-ssh/net-ssh/blob/edd7335d42630aec1ad5b18542e863608bb4ed39/lib/net/ssh/config.rb#L140

Any reason?
It's bit inconvenient to import OpenSSH config file.
(its config key name is usually in CamelCase)

**Comment by mfazekas** [comment]
We should be downcasing, when reading the file see:
https://github.com/net-ssh/net-ssh/blob/edd7335d42630aec1ad5b18542e863608bb4ed39/lib/net/ssh/config.rb#L93

What is the concrete issue you're facing?

**Comment by mfazekas** [comment]
will be reopened in case of new details
