### ISSUE TITLE
/net/ssh/authentication/key_manager.rb:65:in `expand_path' - no implicit conversion of nil into String

### ISSUE THREAD

**Issue by Startouf** [net-ssh/net-ssh#316]
When trying to establish a SSH connection for deployment with Capistrano, I had a problem loading the private key file for puclic key authentication, and the only message I had was a 

```
TypeError: no implicit conversion of nil into String
C:/Dev/Ruby22-x64/lib/ruby/gems/2.2.0/gems/net-ssh-3.0.2/lib/net/ssh/authentication/key_manager.rb:65:in `expand_path'
...
```

After digging net-ssh code and debugging my own code I realized it was just because there was a mistype in my configuration and I was providing a nil parameter for the private key file. Would it be okay to check that the given parameter is indeed a valid string pointing to a valid private key file ?

**Comment by mfazekas** [comment]
@Startouf so your usecase is passing ```keys: [ENV['foo']] ``` where foo is not defined?

**Comment by Startouf** [comment]
Yes, which resulted most likely in `[nil]` being passed.

**Comment by mfazekas** [comment]
@Startouf sorry for late answer yes if you can add a check that would be great. i think the best place would be  where we extract from options. https://github.com/net-ssh/net-ssh/blob/master/lib/net/ssh/authentication/session.rb#L146
