### ISSUE TITLE
When using channel, can't get PTY

### ISSUE THREAD

**Issue by pizzaops** [net-ssh/net-ssh#342]
I seem to always get 

```
Exception `Net::SSH::Exception' at /opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/net-ssh-2.9.2/lib/net/ssh/transport/algorithms.rb:329 - could not settle on language_client algorithm
Exception `Net::SSH::Exception' at /opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/net-ssh-2.9.2/lib/net/ssh/transport/algorithms.rb:329 - could not settle on language_server algorithm
Exception `Net::SSH::ChannelRequestFailed' at /opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/net-ssh-2.9.2/lib/net/ssh/connection/channel.rb:550 - Net::SSH::ChannelRequestFailed
```

 when I try to request a pty, no matter what server I'm targeting, etc.

Doing `Net::SSH.start` and then calling `.exec` or `.exec!` inside the block works fine but I don't seem to see a way to ask for a PTY when using that shorthand to run commands.

Could this be a bug?

The server supports PTYs perfectly fine (e.g. can use normal ssh client and open a pty session).

This happens with `net-ssh` `2.9.2` and `3.1.1`.

**Comment by mfazekas** [comment]
@pizzaops can you post the full code? Also can you add ```verbose: :debug``` and post the full log?

**Comment by mfazekas** [comment]
will be reopened if we have details

**Comment by pizzaops** [comment]
Hey Miklós, sorry that I haven't been able to reply to this yet; I've been
completely consumed with work. I'll get you additional details as soon as I
can.
