### ISSUE TITLE
forward ssh

### ISSUE THREAD

**Issue by NirMendel** [net-ssh/net-ssh#347]
Hi, 
is there a way to use nested ssh:
open a session with ssh to remote host, and from that remote host open another session with ssh to 3rd host?

**Comment by mfazekas** [comment]
see https://github.com/net-ssh/net-ssh-gateway

**Comment by NirMendel** [comment]
Thanks for the quick reply.
I'll be more accurate:
I have my server, middleware server, and unknown device.
The device opens a tunnel to the middleware, and listens to port X.
I have my ssh keys to the midlleware server, and the middleware has it's ssh keys to verify the connection to the device.

I succeeded to use Net::SSH to open ssh connection to the middleware.
With that session, I would like to open ssh connection (with the middleware's keys) to the unknown device (but the port is known).
Since I don't know the device's IP, I can't see how gateway helps.
This is my code:
Net::SSH.start("middle_host", "user", :keys => ["key"]) do |ssh|
    # in here I would like to open ssh to the tunnel:
   ssh 127.0.0.1, root, middleware_keys
end

**Comment by mfazekas** [comment]
```ruby
gateway = Net::SSH::Gateway.new('middle_host', 'user')

gateway.ssh("127.0.0.1", "root", port: port_by_unkonw_device, keys: [middleware_keys]) do |ssh| 
   puts ssh.exec!("hostname") 
end
```
