### ISSUE TITLE
net-ssh requires Ruby version >= 2.0. even if my is 2.2.1p85

### ISSUE THREAD

**Issue by AndreaBarghigiani** [net-ssh/net-ssh#358]
Hi there, I have a really strange problem because I am trying to install this gem because it is used in the wordmove gem but any time I try to update my system I get the followuing error:
`ERROR:  Error installing net-ssh:
	net-ssh requires Ruby version >= 2.0.`

So I've run `ruby -v` and got 2.2.1p85 as version, also because I am not used to the gem world (I am usign wordmove because let's me move easily WordPress installations); I've run `gem -v` and got 2.4.6 as an answer.

I have to tell you that I'm using it on a VVV installation (that's a Vagrant machine for WordPress development) in the hope that this is going to help.

Can you please help me up with this problem because I do not understand this strange behavior?

Thanks you a lot in advance, all the best
Andrea

**Comment by mfazekas** [comment]
What is the exact command you run? (that results in that error). My guess is that you're running ```ruby -v``` in a different environment than where the ```gem install``` is done.

**Comment by AndreaBarghigiani** [comment]
In order to find a solution I've removed [wordmove](https://github.com/welaika/wordmove) from my [VVV](https://github.com/Varying-Vagrant-Vagrants/VVV) machine. Then insert `sudo gem install wordmove` gives me this error:

<img width="325" alt="schermata 2016-04-22 alle 12 00 11" src="https://cloud.githubusercontent.com/assets/190159/14738437/cdf47182-0881-11e6-899c-e778c427f167.png">

Actually I am not an expert of ruby or the gem system, I'm only usign it to download some useful gems. Can you help me understand how check which version of ruby has been used from gem?

Thanks you a lot!
Andrea

**Comment by mfazekas** [comment]
Strange. Can you try gem install with --backtrace --verbose --debug.

**Comment by AndreaBarghigiani** [comment]
Really strange... I get *a lot* of this:
```
Exception `OpenSSL::SSL::SSLError' at /usr/lib/ruby/1.9.1/openssl/buffering.rb:174 - read would block
```
That's really strange since it appears to me that when installing I am usign versione 1.9.1...

**Comment by AndreaBarghigiani** [comment]
When I was starting my Vagrant machine, recently updated, I got an:
`timeout during server version negotiating`
This sounds strange... Probably I am going to delete this machine and start a new one...

**Comment by mfazekas** [comment]
So the 1.9 issue is because ```sudo gem install```, so root defaults to different version than normal user.
```sudo ruby --version``` should print you 1.9.1

**Comment by mfazekas** [comment]
I'm closing the issue as it doesn't seems to be net-ssh related, but feel free to post further updates to the thread

**Comment by leifjohn** [comment]
So how do you get this to work then? My sudo is a different version, but normal user does not have permission to install...???

**Comment by mfazekas** [comment]
```sh
sudo rvm 2.2.1p85 do gem environment
sudo rvm 2.2.1p85 do gem install ...
```

**Comment by laittg** [comment]
I meet the same issue today and find a quick solution.
1. `sudo gem install wordmove` returns `net-ssh requires Ruby version >= 2.0` thought my vagrant box has ruby 2.3.0
2. Without sudo, `gem install wordmove` returns `You don't have write permissions for the /usr/local/rvm/gems/ruby-2.3.0 directory`
Then I try to make ruby directory publicly writeable with `sudo chmod -R 777 /usr/local/rvm/gems/ruby-2.3.0`
After that, `gem install wordmove` works like a charm.

**Comment by kingluddite** [comment]
I needed to upgrade ruby and [this article helped](https://jibai31.wordpress.com/2013/09/01/upgrading-your-vagrant-box-to-ruby-20/)

**Comment by infotek** [comment]
using:
Ubuntu 14.04.5 LTS, Trusty Tahr
error when running "gem install ..."

net-ssh requires Ruby version >= 2.0

fix:

apt install ruby2.0 ruby2.0-dev rubygems-integration

ln -fs /usr/bin/erb2.0 /usr/bin/erb
ln -fs /usr/bin/irb2.0 /usr/bin/irb
ln -fs /usr/bin/rdoc2.0 /usr/bin/rdoc
ln -fs /usr/bin/ri2.0 /usr/bin/ri
ln -fs /usr/bin/ruby2.0 /usr/bin/ruby
ln -fs /usr/bin/testrb2.0 /usr/bin/testrb
ln -fs /usr/bin/gem2.0 /usr/bin/gem

rerun "gem install ..."
