### ISSUE TITLE
net-ssh doesn't work with pageant on cygwin

### ISSUE THREAD

**Issue by duerst** [net-ssh/net-ssh#361]
This is the reverse of issue https://github.com/net-ssh/net-ssh/issues/192, in that I work on cygwin (linux emulation on Windows), but would like to use PuTTY pageant as an authentication agent. I get it to work if I comment out the checks around lines 4 and 136 in net/ssh/authentication/agent/socket.rb, but that's just a short-time quick hack.

Both issues could be solved by introducing an optional configuration variable that tells net-ssh to use (bash) ssh-agent or (PuTTY) pageant. If that helps, I can send a patch.

**Comment by mfazekas** [comment]
@duerst #360 introduces agent_socket_factory i assume that can be used to solve it.

**Comment by duerst** [comment]
@mfazekas: Thanks for the pointer. Line 136 that I mentioned in net/ssh/authentication/agent/socket.rb is indeed in agent_socket_factory. It's just that that line, which reads
    if Net::SSH::Authentication::PLATFORM == :win32
is too simplistic for my case or that of  issue #192.

What would the best way be to make this more flexible? The easiest thing I could come up with would be to allow Net::SSH::Authentication::PLATFORM to be defined in advance, e.g. in Capfile or wherever the user wants, as follows:
module Net; module SSH; module Authentication; PLATFORM = :win32; end end end
(A simple Net::SSH::Authentication::PLATFORM = :win32 doesn't work because the modules don't exist yet.)

As far as I understand, the only thing needed to make this work would be to change line 6 in 
from
  PLATFORM = File::ALT_SEPARATOR \
    ? RUBY_PLATFORM =~ /java/ ? :java_win32 : :win32 \
    : RUBY_PLATFORM =~ /java/ ? :java : :unix
to
  PLATFORM ||= File::ALT_SEPARATOR \
    ? RUBY_PLATFORM =~ /java/ ? :java_win32 : :win32 \
    : RUBY_PLATFORM =~ /java/ ? :java : :unix
to give preference to already existing values.

I have created a tentative pull request for this change at https://github.com/net-ssh/net-ssh/pull/362, just so that it's easy to see what change I propose. But something like
module Net; module SSH; module Authentication; PLATFORM = :win32; end end end
doesn't feel like Ruby; much more like a bad hack. Any advice welcome.

**Comment by mfazekas** [comment]
So #360 introduces a new option to use like this:
```Net::SSH::start(user,host,agent_socket_factory: ->{ UNIXSocket.open('/foo/bar') })```

You should be able to use that to force specific connection.

I don't really like user defining a constant in my package to overwrite this behaviour.


```ruby
module Net; module SSH; module Authentication; PLATFORM = :win32; end end end
```
is fragile as if it cames after net-ssh loaded, then it's not going to work.

I think by default with :use_agent set to true we should be doing this:
If we have UnixSocket and SSH_AUTH_SOCK then we should try UnixSocket, if it fails we can fallback to Pageant if we're on windows.

If users want to customize then there is agent_socket_factory.
Other options let :use_agent to be set to :pagent to force pageant.

**Comment by duerst** [comment]
I agree with your dislike of overwriting Net::SSH::Authentication::PLATFORM; it's fragile and intrusive. This was just "a bad patch is better than no patch", sorry.

I have picked up your idea of using SSH_AUTH_SOCK and provided a new patch: https://github.com/net-ssh/net-ssh/pull/365. I hope this gets closer to what we want.

agent_socket_factory is still available for more complex configuration.

I haven't implemented the "try..., if it fails" part. Maybe we don't need it. If you think we should add it, a pointer to where it might go is appreciated.

Just as an aside, I thought that the code at https://github.com/net-ssh/net-ssh/blob/master/lib/net/ssh/authentication/agent/socket.rb#L3-L6 would fit better at https://github.com/net-ssh/net-ssh/blob/master/lib/net/ssh/authentication/agent.rb#L24, and that pageant.rb might better be moved to the authentication/agent directory. What do you think?

**Comment by duerst** [comment]
@mfazekas: Ping!

**Comment by mfazekas** [comment]
@duerst i apologize for late answer, and i'm really thankfull for your contributions.

I plan to do something like this:
https://github.com/net-ssh/net-ssh/pull/439

in particular the logic would be simplified as:
```ruby
        @socket =
          if agent_socket_factory
            agent_socket_factory.call
          else
            if ENV['SSH_AUTH_SOCK'] && defined?(UNIXSocket)
              UNIXSocket.open(ENV['SSH_AUTH_SOCK'])
            elsif Gem.win_platform?
              Pageant::Socket.open
            end
          end
```
https://github.com/net-ssh/net-ssh/pull/439/files#diff-fdc347d62092dff1038700b85f4d3796R75

**Comment by mfazekas** [comment]
This should now be merged and fixed in master
