### ISSUE TITLE
undefined method `chomp' for nil:NilClass

### ISSUE THREAD

**Issue by Vanders** [net-ssh/net-ssh#366]
If public key authentication fails and no password was given to Net::SSH.start, it will fall back to an interactive password prompt. If the application is running as a daemon or otherwise doesn't have a valid stdio, `lib/net/ssh/prompt.rb` throws `undefined method 'chomp' for nil:NilClass`, which is a bit of an opaque error.

It might be better if the method checked for a valid stdin before it tried to use it, or rescued that exception itself and re-raised its own more descriptive error.

Ruby 2.3.0
Net::SSH 3.1.1
```
E, [2016-05-04T09:14:33.765197 #2504] ERROR -- : job runner failed: undefined method `chomp' for nil:NilClass
/var/lib/gems/2.3.0/gems/net-ssh-3.1.1/lib/net/ssh/prompt.rb:73:in `prompt'
/var/lib/gems/2.3.0/gems/net-ssh-3.1.1/lib/net/ssh/authentication/methods/password.rb:57:in `ask_password'
/var/lib/gems/2.3.0/gems/net-ssh-3.1.1/lib/net/ssh/authentication/methods/password.rb:22:in `authenticate'
/var/lib/gems/2.3.0/gems/net-ssh-3.1.1/lib/net/ssh/authentication/session.rb:79:in `block in authenticate'
/var/lib/gems/2.3.0/gems/net-ssh-3.1.1/lib/net/ssh/authentication/session.rb:66:in `each'
/var/lib/gems/2.3.0/gems/net-ssh-3.1.1/lib/net/ssh/authentication/session.rb:66:in `authenticate'
/var/lib/gems/2.3.0/gems/net-ssh-3.1.1/lib/net/ssh.rb:233:in `start'
```

**Comment by mfazekas** [comment]
Non interactive applications should set the non_interactive option.

**Comment by Vanders** [comment]
Thanks, I see it now. (As an aside, it's listed in the documentation for #start _twice_, so I guess I have no excuse!)
