### ISSUE TITLE
DL is deprecated, please use Fiddle

### ISSUE THREAD

**Issue by chef09210** [net-ssh/net-ssh#369]
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gemsnet-ssh-3.1.1/lib/net/ssh/authentication/pageant.rb:16: warning: previous definition of RUBY_FREE was here
DL is deprecated, please use Fiddle

**Comment by Ajedi32** [comment]
Fixed by #221

**Comment by mfazekas** [comment]
Can you try some more recent version?
https://github.com/net-ssh/net-ssh/commit/b70085567eea92d9b2c93a1d146001e471176572
3.2.0 should not have the RUBY_FREE related warning. 

I'm not sure ```DL is deprecated, please use Fiddle``` is coming from net-ssh ```3.1.1``` as ```3.1.1``` should be already using Fiddle on 2.1.0
