### ISSUE TITLE
Incompatible character encodings: ASCII-8BIT and UTF-8

### ISSUE THREAD

**Issue by sickmoses** [net-ssh/net-ssh#370]
Versions : ruby-2.3.0 , net-ssh-3.1.1

Code :
`Net::SSH.start( @hostname, @username, :password => @password ) do |ssh|
    output = ssh.exec!("hostname")
    puts output
end`

Produces :
`.../.rvm/gems/ruby-2.3.0/gems/net-ssh-3.1.1/lib/net/ssh/buffer.rb:284:in `block in write': incompatible character encodings: ASCII-8BIT and UTF-8 (Encoding::CompatibilityError)
.../.rvm/gems/ruby-2.3.0/gems/net-ssh-3.1.1/lib/net/ssh/buffer.rb:284:in `each'
...
from maint.rb:11:in `<main>'`

**Comment by mfazekas** [comment]
@sickmoses thanks for the report. You mean ascii '*' char or some uft-8 asterisk?

Asterisk can be appended:
```ruby
[1,152].pack("N2") << "*"
```

But 
```ruby
[1,152].pack("N2") << "✱"
```
reproduces the error

**Comment by sickmoses** [comment]
* this one, yea that example reproduces the error as well.

**Comment by mfazekas** [comment]
so ascii '*' should work. '*'.encoding is utf-8 but it can be translated to ascii. You're more interesed in this:


```ruby
2.3.0 :038 > "✱".encode(Encoding::ASCII_8BIT)
Encoding::UndefinedConversionError: U+2731 from UTF-8 to ASCII-8BIT

vs
2.3.0 :038 > "*".encode(Encoding::ASCII_8BIT) 
 => "*" 
```

**Comment by sickmoses** [comment]
It doesn't seem to be an issue with my variables as I only get the error when I attempt commenting out ssh.exec!

**Comment by sickmoses** [comment]
I'm unable to reproduce on my personal computer. I ran the same script with Success. I'm running the same version of ruby and net-ssh but with rbenv this time. I think there is a configuration issue on my work computer and have to look into it. Should this thread be closed?

**Comment by xueyaodeai** [comment]
I've got same problem with you @sickmoses.

**Comment by mfazekas** [comment]
@xueyaodeai which version of ruby are you using which version of net-ssh.
For both versions i'm getting the incompatible character encodings: ASCII-8BIT and UTF-8 error

**Comment by mfazekas** [comment]
as for handling unicode chars see #394

**Comment by xueyaodeai** [comment]
@mfazekas ruby: 2.3.0 net-ssh 3.2.0

**Comment by mfazekas** [comment]
@xueyaodeai i've tried the following program and both were giving me incompatible encoding error:

```ruby
gem 'net-ssh', '= 3.2.0'
require 'net/ssh'
require 'byebug'
puts "NetSSH=#{Net::SSH::Version::CURRENT}"
puts "RUBY=#{RUBY_VERSION}"

USE_VAR = true

host = 'localhost'
user = ENV['USER']

if USE_VAR
  image_storage = "local"
  image = "images/host-fefcfe5a5480/34cb4dce323c/048039e26209/38a57817e6e9/371abc7b5f38/cb5f599d114e/abcd_efg_号号_xxx02.vm/vm-disk-1.qcow2"

  Net::SSH.start(host, user) do |ssh|
    puts ssh.exec!("qemu-img info /sf/data/#{image_storage}/#{image} --output json")
  end
else

  Net::SSH.start(host, user) do |ssh|
    puts ssh.exec!("qemu-img info /sf/data/local/images/host-fefcfe5a5480/34cb4dce323c/048039e26209/38a57817e6e9/371abc7b5f38/cb5f599d114e/abcd_efg_号号xxx02.vm/vm-disk-1.qcow2 --output json")
  end
end
```

**Comment by mfazekas** [comment]
Should be fixed in 4.0.0.beta1

**Comment by xueyaodeai** [comment]
@mfazekas It‘s so weird. I have tried them both again in my pc today, and I found that they both got incompatible encoding error

**Comment by chadlwm** [comment]
try `ssh.exec!(cmd.force_encoding("ASCII-8BIT"))`
