### ISSUE TITLE
timeout during server version negotiating with KVM guests

### ISSUE THREAD

**Issue by jayshah11** [net-ssh/net-ssh#373]
I am using serverspec in the ssh mode to ssh into a server from a central server and run a few commands. I execute serverspec via cron on a central server

Every few days, I get the message "host is not reachable: timeout during server version negotiating". But the host is reachable and works fine and I can run the test manually just fine. The ssh versions are the same as well. 

Has someone come across such issue and may be have a solution for it?

**Comment by mfazekas** [comment]
There is not much we can do if we cannot reproduce the issue, or don't have server logs/tcp dump to debug it... It can be a network issue, or the host is being restarted.
