### ISSUE TITLE
Net::SSH should support certificate based authentication

### ISSUE THREAD

**Issue by chilicheech** [net-ssh/net-ssh#379]
A lot of systems are now forcing certificate based authentication and it would be awesome if Net::SSH could support it. http://www.openbsd.org/cgi-bin/cvsweb/src/usr.bin/ssh/PROTOCOL.certkeys?rev=HEAD

**Comment by nbibler** [comment]
Related to #124.

**Comment by louahola** [comment]
+1

**Comment by dpigliavento** [comment]
+1

**Comment by viv7266** [comment]
+1
Facing this issue.
http://stackoverflow.com/questions/41341704/signed-ca-certificate-authentication-using-net-ssh-in-capistrano

**Comment by mfazekas** [comment]
cert client auth should be supported on master
