### ISSUE TITLE
Remote and Local Forward

### ISSUE THREAD

**Issue by arion** [net-ssh/net-ssh#38]
Hi!

Net::SSH.configuration_for ignore LocalForward and RemoteForward from ~/.ssh/config and Net::SSH.start has no option for forward

**Comment by mfazekas** [comment]
We have remote and local forward programatically. 
https://github.com/net-ssh/net-ssh/blob/master/lib/net/ssh.rb#L47-L59
```ruby
  # == X == "forward connections on a local port to a remote host"
  #
  #   Net::SSH.start("host", "user", :password => "password") do |ssh|
  #     ssh.forward.local(1234, "www.google.com", 80)
  #     ssh.loop { true }
  #   end
  #
  # == X == "forward connections on a remote port to the local host"
  #
  #   Net::SSH.start("host", "user", :password => "password") do |ssh|
  #     ssh.forward.remote(80, "www.google.com", 1234)
  #     ssh.loop { true }
  #   end
```

i'd be interested in concrete usecase, LocalForward and RemotForward is more for interactive use. Even if we support those options it should be non default as for non interactive cases doing the forward might not be desirable.
