### ISSUE TITLE
command.rb:93:in `read_nonblock': end of file reached (EOFError)

### ISSUE THREAD

**Issue by 0xAalaoui** [net-ssh/net-ssh#380]
Hello,

I can't connect to a Cisco switch IOS version 15.4, here is the full trace:

D, [2016-05-30T15:42:17.012400 #2689] DEBUG -- net.ssh.transport.session[14fc3a0]: establishing connection to 192.168.136.160:22
D, [2016-05-30T15:42:17.024289 #2689] DEBUG -- net.ssh.transport.session[14fc3a0]: connection established
I, [2016-05-30T15:42:17.024403 #2689]  INFO -- net.ssh.transport.server_version[150b92c]: negotiating protocol version
D, [2016-05-30T15:42:17.024432 #2689] DEBUG -- net.ssh.transport.server_version[150b92c]: local is `SSH-2.0-Ruby/Net::SSH_3.1.1 x86_64-linux'
D, [2016-05-30T15:42:17.024517 #2689] DEBUG -- net.ssh.transport.server_version[150b92c]: remote is `SSH-2.0-Cisco-1.25'
D, [2016-05-30T15:42:17.045407 #2689] DEBUG -- io[15004f0]: read 368 bytes
D, [2016-05-30T15:42:17.045492 #2689] DEBUG -- io[15004f0]: received packet nr 0 type 20 len 364
I, [2016-05-30T15:42:17.045546 #2689]  INFO -- net.ssh.transport.algorithms[150a914]: got KEXINIT from server
I, [2016-05-30T15:42:17.045610 #2689]  INFO -- net.ssh.transport.algorithms[150a914]: sending KEXINIT
D, [2016-05-30T15:42:17.045718 #2689] DEBUG -- io[15004f0]: queueing packet nr 0 type 20 len 1684
D, [2016-05-30T15:42:17.045755 #2689] DEBUG -- io[15004f0]: sent 1688 bytes
I, [2016-05-30T15:42:17.045776 #2689]  INFO -- net.ssh.transport.algorithms[150a914]: negotiating algorithms
D, [2016-05-30T15:42:17.045838 #2689] DEBUG -- net.ssh.transport.algorithms[150a914]: negotiated:
* kex: diffie-hellman-group-exchange-sha1
* host_key: ssh-rsa
* encryption_server: aes128-cbc
* encryption_client: aes128-cbc
* hmac_client: hmac-sha1
* hmac_server: hmac-sha1
* compression_client: none
* compression_server: none
* language_client:
* language_server:
D, [2016-05-30T15:42:17.045864 #2689] DEBUG -- net.ssh.transport.algorithms[150a914]: exchanging keys
D, [2016-05-30T15:42:17.045989 #2689] DEBUG -- io[15004f0]: queueing packet nr 1 type 34 len 20
D, [2016-05-30T15:42:17.046022 #2689] DEBUG -- io[15004f0]: sent 24 bytes
D, [2016-05-30T15:42:17.048857 #2689] DEBUG -- io[15004f0]: read 152 bytes
D, [2016-05-30T15:42:17.048919 #2689] DEBUG -- io[15004f0]: received packet nr 1 type 31 len 148
D, [2016-05-30T15:42:17.049973 #2689] DEBUG -- io[15004f0]: queueing packet nr 2 type 32 len 140
D, [2016-05-30T15:42:17.050013 #2689] DEBUG -- io[15004f0]: sent 144 bytes
D, [2016-05-30T15:42:17.091790 #2689] DEBUG -- io[15004f0]: read 464 bytes
D, [2016-05-30T15:42:17.091881 #2689] DEBUG -- io[15004f0]: received packet nr 2 type 33 len 444
D, [2016-05-30T15:42:17.092848 #2689] DEBUG -- io[15004f0]: queueing packet nr 3 type 21 len 20
D, [2016-05-30T15:42:17.092892 #2689] DEBUG -- io[15004f0]: sent 24 bytes
D, [2016-05-30T15:42:17.092938 #2689] DEBUG -- io[15004f0]: received packet nr 3 type 21 len 12
D, [2016-05-30T15:42:17.093173 #2689] DEBUG -- net.ssh.authentication.session[13ebbb4]: beginning authentication of `admin'
D, [2016-05-30T15:42:17.093270 #2689] DEBUG -- io[15004f0]: queueing packet nr 4 type 5 len 28
D, [2016-05-30T15:42:17.093305 #2689] DEBUG -- io[15004f0]: sent 52 bytes
D, [2016-05-30T15:42:17.095390 #2689] DEBUG -- io[15004f0]: read 52 bytes
D, [2016-05-30T15:42:17.095461 #2689] DEBUG -- io[15004f0]: received packet nr 4 type 6 len 28
D, [2016-05-30T15:42:17.095568 #2689] DEBUG -- net.ssh.authentication.session[13ebbb4]: trying none
D, [2016-05-30T15:42:17.095656 #2689] DEBUG -- io[15004f0]: queueing packet nr 5 type 50 len 44
D, [2016-05-30T15:42:17.095689 #2689] DEBUG -- io[15004f0]: sent 68 bytes
D, [2016-05-30T15:42:17.098576 #2689] DEBUG -- io[15004f0]: read 84 bytes
D, [2016-05-30T15:42:17.098649 #2689] DEBUG -- io[15004f0]: received packet nr 5 type 51 len 60
D, [2016-05-30T15:42:17.098703 #2689] DEBUG -- net.ssh.authentication.session[13ebbb4]: allowed methods: publickey,keyboard-interactive,password
D, [2016-05-30T15:42:17.098743 #2689] DEBUG -- net.ssh.authentication.methods.none[13d7290]: none failed
D, [2016-05-30T15:42:17.098783 #2689] DEBUG -- net.ssh.authentication.session[13ebbb4]: trying publickey
D, [2016-05-30T15:42:17.098865 #2689] DEBUG -- net.ssh.authentication.agent[13d0c9c]: connecting to ssh-agent
E, [2016-05-30T15:42:17.098917 #2689] ERROR -- net.ssh.authentication.agent[13d0c9c]: could not connect to ssh-agent
D, [2016-05-30T15:42:17.098951 #2689] DEBUG -- net.ssh.authentication.session[13ebbb4]: trying password
D, [2016-05-30T15:42:17.099043 #2689] DEBUG -- io[15004f0]: queueing packet nr 6 type 50 len 60
D, [2016-05-30T15:42:17.099076 #2689] DEBUG -- io[15004f0]: sent 84 bytes
D, [2016-05-30T15:42:17.103200 #2689] DEBUG -- io[15004f0]: read 36 bytes
D, [2016-05-30T15:42:17.103272 #2689] DEBUG -- io[15004f0]: received packet nr 6 type 52 len 12
D, [2016-05-30T15:42:17.103329 #2689] DEBUG -- net.ssh.authentication.methods.password[13d0274]: password succeeded
D, [2016-05-30T15:42:17.103439 #2689] DEBUG -- io[15004f0]: queueing packet nr 7 type 90 len 44
D, [2016-05-30T15:42:17.103526 #2689] DEBUG -- io[15004f0]: sent 68 bytes
D, [2016-05-30T15:42:17.105567 #2689] DEBUG -- io[15004f0]: read 52 bytes
D, [2016-05-30T15:42:17.105643 #2689] DEBUG -- io[15004f0]: received packet nr 7 type 91 len 28
I, [2016-05-30T15:42:17.105708 #2689]  INFO -- net.ssh.connection.session[13cca98]: channel_open_confirmation: 0 3 8192 4096
I, [2016-05-30T15:42:17.105821 #2689]  INFO -- net.ssh.connection.channel[13cc8b8]: sending channel request "env"
D, [2016-05-30T15:42:17.105889 #2689] DEBUG -- io[15004f0]: queueing packet nr 8 type 98 len 44
I, [2016-05-30T15:42:17.106233 #2689]  INFO -- net.ssh.connection.channel[13cc8b8]: sending channel request "exec"
D, [2016-05-30T15:42:17.106312 #2689] DEBUG -- io[15004f0]: queueing packet nr 9 type 98 len 44
D, [2016-05-30T15:42:17.106366 #2689] DEBUG -- io[15004f0]: sent 136 bytes
D, [2016-05-30T15:42:17.108370 #2689] DEBUG -- io[15004f0]: read 36 bytes
D, [2016-05-30T15:42:17.108443 #2689] DEBUG -- io[15004f0]: received packet nr 8 type 99 len 12
I, [2016-05-30T15:42:17.108498 #2689]  INFO -- net.ssh.connection.session[13cca98]: channel_success: 0
D, [2016-05-30T15:42:17.123765 #2689] DEBUG -- io[15004f0]: read 1072 bytes
D, [2016-05-30T15:42:17.124040 #2689] DEBUG -- io[15004f0]: read 536 bytes
D, [2016-05-30T15:42:17.125623 #2689] DEBUG -- io[15004f0]: read 844 bytes
D, [2016-05-30T15:42:17.125724 #2689] DEBUG -- io[15004f0]: received packet nr 9 type 94 len 2428
I, [2016-05-30T15:42:17.125784 #2689]  INFO -- net.ssh.connection.session[13cca98]: channel_data: 0 2403b
D, [2016-05-30T15:42:17.223494 #2689] DEBUG -- io[15004f0]: read 68 bytes
D, [2016-05-30T15:42:17.223786 #2689] DEBUG -- io[15004f0]: received packet nr 10 type 98 len 44
I, [2016-05-30T15:42:17.223859 #2689]  INFO -- net.ssh.connection.session[13cca98]: channel_request: 0 exit-status false
D, [2016-05-30T15:42:17.224634 #2689] DEBUG -- io[15004f0]: read 72 bytes
I, [2016-05-30T15:42:17.224724 #2689]  INFO -- net.ssh.connection.session[13cca98]: closing remaining channels (1 open)

**/home/xxxx/.gem/ruby/gems/net-ssh-3.1.1/lib/net/ssh/proxy/command.rb:93:in `read_nonblock': end of file reached (EOFError)**
        from /home/xxxx/.gem/ruby/gems/net-ssh-3.1.1/lib/net/ssh/proxy/command.rb:93:in `recv'
        from /home/xxxx/.gem/ruby/gems/net-ssh-3.1.1/lib/net/ssh/buffered_io.rb:65:in `fill'
        from /home/xxxx/.gem/ruby/gems/net-ssh-3.1.1/lib/net/ssh/transport/packet_stream.rb:88:in `next_packet'
        from /home/xxxx/.gem/ruby/gems/net-ssh-3.1.1/lib/net/ssh/transport/session.rb:192:in `block in poll_message'
        from /home/xxxx/.gem/ruby/gems/net-ssh-3.1.1/lib/net/ssh/transport/session.rb:187:in `loop'
        from /home/xxxx/.gem/ruby/gems/net-ssh-3.1.1/lib/net/ssh/transport/session.rb:187:in `poll_message'
        from /home/xxxx/.gem/ruby/gems/net-ssh-3.1.1/lib/net/ssh/connection/session.rb:471:in `dispatch_incoming_packets'
        from /home/xxxx/.gem/ruby/gems/net-ssh-3.1.1/lib/net/ssh/connection/session.rb:222:in `preprocess'
        from /home/xxxx/.gem/ruby/gems/net-ssh-3.1.1/lib/net/ssh/connection/session.rb:206:in `process'
        from /home/xxxx/.gem/ruby/gems/net-ssh-3.1.1/lib/net/ssh/connection/session.rb:170:in `block in loop'
        from /home/xxxx/.gem/ruby/gems/net-ssh-3.1.1/lib/net/ssh/connection/session.rb:170:in `loop'
        from /home/xxxx/.gem/ruby/gems/net-ssh-3.1.1/lib/net/ssh/connection/session.rb:170:in `loop'
        from /home/xxxx/.gem/ruby/gems/net-ssh-3.1.1/lib/net/ssh/connection/session.rb:119:in `close'
        from /home/xxxx/.gem/ruby/gems/net-ssh-3.1.1/lib/net/ssh.rb:239:in `ensure in start'
        from /home/xxxx/.gem/ruby/gems/net-ssh-3.1.1/lib/net/ssh.rb:239:in `start'

**Comment by tiagobevilaqua** [comment]
+1

**Comment by csaki** [comment]
This is not the best solution, but works for me:

res = ''
begin
  ssh.exec!("#{cmd}") do |channel, stream, data|
     res << data if stream == :stdout
  end
rescue EOFError => e
end

**Comment by mfazekas** [comment]
Can someone try 4.0.0beta3? #421, and #422 might improve this.
