### ISSUE TITLE
connection closed by remote host  (Net::SSH::Disconnect)

### ISSUE THREAD

**Issue by 0xAalaoui** [net-ssh/net-ssh#388]
Hello,

How to fix this issue?

```
D, [2016-06-17T11:09:50.958529 #7324] DEBUG -- net.ssh.transport.session[17136b4]: establishing connection to xxx:xx
D, [2016-06-17T11:09:50.972539 #7324] DEBUG -- net.ssh.transport.session[17136b4]: connection established
I, [2016-06-17T11:09:50.972539 #7324]  INFO -- net.ssh.transport.server_version[1713144]: negotiating protocol version
D, [2016-06-17T11:09:50.972539 #7324] DEBUG -- net.ssh.transport.server_version[1713144]: local is `SSH-2.0-Ruby/Net::SSH_3.1.1 i386-mingw32'
D, [2016-06-17T11:09:50.973540 #7324] DEBUG -- net.ssh.transport.server_version[1713144]: remote is `SSH-2.0-Cisco-1.25'
D, [2016-06-17T11:09:50.974540 #7324] DEBUG -- socket[17134c8]: read 368 bytes
D, [2016-06-17T11:09:50.975541 #7324] DEBUG -- socket[17134c8]: received packet nr 0 type 20 len 364
I, [2016-06-17T11:09:50.975541 #7324]  INFO -- net.ssh.transport.algorithms[1712b5c]: got KEXINIT from server
I, [2016-06-17T11:09:50.976541 #7324]  INFO -- net.ssh.transport.algorithms[1712b5c]: sending KEXINIT
D, [2016-06-17T11:09:50.976541 #7324] DEBUG -- socket[17134c8]: queueing packet nr 0 type 20 len 1684
D, [2016-06-17T11:09:50.978547 #7324] DEBUG -- socket[17134c8]: sent 1688 bytes
I, [2016-06-17T11:09:50.978547 #7324]  INFO -- net.ssh.transport.algorithms[1712b5c]: negotiating algorithms
D, [2016-06-17T11:09:50.978547 #7324] DEBUG -- net.ssh.transport.algorithms[1712b5c]: negotiated:
* kex: diffie-hellman-group-exchange-sha1
* host_key: ssh-rsa
* encryption_server: aes128-cbc
* encryption_client: aes128-cbc
* hmac_client: hmac-sha1
* hmac_server: hmac-sha1
* compression_client: none
* compression_server: none
* language_client:
* language_server:
D, [2016-06-17T11:09:50.980544 #7324] DEBUG -- net.ssh.transport.algorithms[1712b5c]: exchanging keys
D, [2016-06-17T11:09:50.980544 #7324] DEBUG -- socket[17134c8]: queueing packet nr 1 type 34 len 20
D, [2016-06-17T11:09:50.982545 #7324] DEBUG -- socket[17134c8]: sent 24 bytes
D, [2016-06-17T11:09:51.183471 #7324] DEBUG -- socket[17134c8]: read 152 bytes
D, [2016-06-17T11:09:51.183471 #7324] DEBUG -- socket[17134c8]: received packet nr 1 type 31 len 148
D, [2016-06-17T11:09:52.480740 #7324] DEBUG -- socket[17134c8]: queueing packet nr 2 type 32 len 140
D, [2016-06-17T11:09:52.481747 #7324] DEBUG -- socket[17134c8]: sent 144 bytes
D, [2016-06-17T11:09:52.522762 #7324] DEBUG -- socket[17134c8]: read 464 bytes
D, [2016-06-17T11:09:52.522762 #7324] DEBUG -- socket[17134c8]: received packet nr 2 type 33 len 444
D, [2016-06-17T11:09:52.527773 #7324] DEBUG -- socket[17134c8]: queueing packet nr 3 type 21 len 20
D, [2016-06-17T11:09:52.528773 #7324] DEBUG -- socket[17134c8]: sent 24 bytes
D, [2016-06-17T11:09:52.528773 #7324] DEBUG -- socket[17134c8]: received packet nr 3 type 21 len 12
D, [2016-06-17T11:09:52.529772 #7324] DEBUG -- net.ssh.authentication.session[173d51c]: beginning authentication of `admin'
D, [2016-06-17T11:09:52.530772 #7324] DEBUG -- socket[17134c8]: queueing packet nr 4 type 5 len 28
D, [2016-06-17T11:09:52.530772 #7324] DEBUG -- socket[17134c8]: sent 52 bytes
D, [2016-06-17T11:09:52.736426 #7324] DEBUG -- socket[17134c8]: read 52 bytes
D, [2016-06-17T11:09:52.736426 #7324] DEBUG -- socket[17134c8]: received packet nr 4 type 6 len 28
D, [2016-06-17T11:09:52.738435 #7324] DEBUG -- net.ssh.authentication.session[173d51c]: trying none
D, [2016-06-17T11:09:52.739434 #7324] DEBUG -- socket[17134c8]: queueing packet nr 5 type 50 len 44
D, [2016-06-17T11:09:52.740435 #7324] DEBUG -- socket[17134c8]: sent 68 bytes
D, [2016-06-17T11:09:52.750961 #7324] DEBUG -- socket[17134c8]: read 84 bytes
D, [2016-06-17T11:09:52.750961 #7324] DEBUG -- socket[17134c8]: received packet nr 5 type 51 len 60
D, [2016-06-17T11:09:52.751970 #7324] DEBUG -- net.ssh.authentication.session[173d51c]: allowed methods: publickey,keyboard-interactive,password
D, [2016-06-17T11:09:52.752971 #7324] DEBUG -- net.ssh.authentication.methods.none[173c7e4]: none failed
D, [2016-06-17T11:09:52.752971 #7324] DEBUG -- net.ssh.authentication.session[173d51c]: trying publickey
D, [2016-06-17T11:09:52.755711 #7324] DEBUG -- net.ssh.authentication.agent[174375c]: connecting to ssh-agent
E, [2016-06-17T11:09:52.756711 #7324] ERROR -- net.ssh.authentication.agent[174375c]: could not connect to ssh-agent
D, [2016-06-17T11:09:52.756711 #7324] DEBUG -- net.ssh.authentication.methods.publickey[1743a80]: trying publickey (83:0c:05:f6:c1:00:37:f0:c4:04:6f:7:bc:3b:8b:21)
D, [2016-06-17T11:09:52.757713 #7324] DEBUG -- socket[17134c8]: queueing packet nr 6 type 50 len 348
D, [2016-06-17T11:09:52.757713 #7324] DEBUG -- socket[17134c8]: sent 372 bytes
D, [2016-06-17T11:09:54.768037 #7324] DEBUG -- socket[17134c8]: read 84 bytes
D, [2016-06-17T11:09:54.768037 #7324] DEBUG -- socket[17134c8]: received packet nr 6 type 51 len 60
D, [2016-06-17T11:09:54.769037 #7324] DEBUG -- net.ssh.authentication.session[173d51c]: allowed methods: publickey,keyboard-interactive,password
D, [2016-06-17T11:09:54.769037 #7324] DEBUG -- net.ssh.authentication.session[173d51c]: trying password
D, [2016-06-17T11:09:54.770038 #7324] DEBUG -- socket[17134c8]: queueing packet nr 7 type 50 len 60
D, [2016-06-17T11:09:54.770038 #7324] DEBUG -- socket[17134c8]: sent 84 bytes
D, [2016-06-17T11:09:54.781137 #7324] DEBUG -- socket[17134c8]: read 36 bytes
D, [2016-06-17T11:09:54.781137 #7324] DEBUG -- socket[17134c8]: received packet nr 7 type 52 len 12
D, [2016-06-17T11:09:54.782140 #7324] DEBUG -- net.ssh.authentication.methods.password[17423f4]: password succeeded
D, [2016-06-17T11:09:54.782140 #7324] DEBUG -- socket[17134c8]: queueing packet nr 8 type 90 len 44
D, [2016-06-17T11:09:54.782140 #7324] DEBUG -- socket[17134c8]: sent 68 bytes
D, [2016-06-17T11:09:54.793719 #7324] DEBUG -- socket[17134c8]: read 52 bytes
D, [2016-06-17T11:09:54.793719 #7324] DEBUG -- socket[17134c8]: received packet nr 8 type 91 len 28
I, [2016-06-17T11:09:54.794719 #7324]  INFO -- net.ssh.connection.session[1749978]: channel_open_confirmation: 0 3 8192 4096
I, [2016-06-17T11:09:54.794719 #7324]  INFO -- net.ssh.connection.channel[17498a0]: sending channel request "exec"
D, [2016-06-17T11:09:54.795720 #7324] DEBUG -- socket[17134c8]: queueing packet nr 9 type 98 len 44
D, [2016-06-17T11:09:54.795720 #7324] DEBUG -- socket[17134c8]: sent 68 bytes
D, [2016-06-17T11:09:54.797721 #7324] DEBUG -- socket[17134c8]: read 120 bytes
D, [2016-06-17T11:09:54.798722 #7324] DEBUG -- socket[17134c8]: received packet nr 9 type 99 len 12
I, [2016-06-17T11:09:54.798722 #7324]  INFO -- net.ssh.connection.session[1749978]: channel_success: 0
D, [2016-06-17T11:09:54.798722 #7324] DEBUG -- socket[17134c8]: received packet nr 10 type 94 len 60
I, [2016-06-17T11:09:54.800166 #7324]  INFO -- net.ssh.connection.session[1749978]: channel_data: 0 35b
D, [2016-06-17T11:09:54.895781 #7324] DEBUG -- socket[17134c8]: read 140 bytes
D, [2016-06-17T11:09:54.895781 #7324] DEBUG -- socket[17134c8]: read 0 bytes
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/net-ssh-3.1.1/lib/net/ssh/transport/packet_stream.rb:89:in `next_packet': connection closed by r
mote host (Net::SSH::Disconnect)
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/net-ssh-3.1.1/lib/net/ssh/transport/session.rb:192:in `block in poll_message'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/net-ssh-3.1.1/lib/net/ssh/transport/session.rb:187:in `loop'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/net-ssh-3.1.1/lib/net/ssh/transport/session.rb:187:in `poll_message'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/net-ssh-3.1.1/lib/net/ssh/connection/session.rb:471:in `dispatch_incoming_packets'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/net-ssh-3.1.1/lib/net/ssh/connection/session.rb:222:in `preprocess'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/net-ssh-3.1.1/lib/net/ssh/connection/session.rb:206:in `process'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/net-ssh-3.1.1/lib/net/ssh/connection/session.rb:170:in `block in loop'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/net-ssh-3.1.1/lib/net/ssh/connection/session.rb:170:in `loop'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/net-ssh-3.1.1/lib/net/ssh/connection/session.rb:170:in `loop'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/net-ssh-3.1.1/lib/net/ssh/connection/channel.rb:269:in `wait'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/net-ssh-3.1.1/lib/net/ssh/connection/session.rb:365:in `exec!'
        from file.rb:6:in `<main>'

```

**Comment by mfazekas** [comment]
Hi remote side closed the connection. 
What is the script you're executing? What is the remote side server version?
Ideally i'd need it to reproduce to fix it.

**Comment by 0xAalaoui** [comment]
I'm executing one command, "show version" on a cisco switch ssh version: SSH-2.0-Cisco-1.25, i will can give you a tunnel to the devise using ngrok.

**Comment by mfazekas** [comment]
That tunnel would be usefull. I've sent a private email regarding this.

**Comment by 0xAalaoui** [comment]
i've sent you an email with the credentials

**Comment by CliffordBernard** [comment]
I am experiencing the same issue when trying to log into Cisco routers and switches, my nexus platform does not have this problem however.

**Comment by CliffordBernard** [comment]
My log information below:

Ruby Server Output:

D, [2016-06-30T11:28:29.621092 #3544] DEBUG -- net.ssh.transport.session[3fcba20a2bf4]: establishing connection to <device ip address>:22
D, [2016-06-30T11:28:29.623094 #3544] DEBUG -- net.ssh.transport.session[3fcba20a2bf4]: connection established
I, [2016-06-30T11:28:29.623204 #3544]  INFO -- net.ssh.transport.server_version[3fcba209f3f0]: negotiating protocol version
D, [2016-06-30T11:28:29.623286 #3544] DEBUG -- net.ssh.transport.server_version[3fcba209f3f0]: local is `SSH-2.0-Ruby/Net::SSH_3.2.0 universal.x86_64-darwin15'
D, [2016-06-30T11:28:29.624361 #3544] DEBUG -- net.ssh.transport.server_version[3fcba209f3f0]: remote is `SSH-2.0-Cisco-1.25'
I, [2016-06-30T11:28:29.624531 #3544]  INFO -- net.ssh.transport.algorithms[3fcba209bf84]: sending KEXINIT
D, [2016-06-30T11:28:29.624778 #3544] DEBUG -- socket[3fcba20a2578]: queueing packet nr 0 type 20 len 636
D, [2016-06-30T11:28:29.624892 #3544] DEBUG -- socket[3fcba20a2578]: sent 640 bytes
D, [2016-06-30T11:28:29.626002 #3544] DEBUG -- socket[3fcba20a2578]: read 216 bytes
D, [2016-06-30T11:28:29.626127 #3544] DEBUG -- socket[3fcba20a2578]: received packet nr 0 type 20 len 212
I, [2016-06-30T11:28:29.626201 #3544]  INFO -- net.ssh.transport.algorithms[3fcba209bf84]: got KEXINIT from server
I, [2016-06-30T11:28:29.626382 #3544]  INFO -- net.ssh.transport.algorithms[3fcba209bf84]: negotiating algorithms
D, [2016-06-30T11:28:29.626525 #3544] DEBUG -- net.ssh.transport.algorithms[3fcba209bf84]: negotiated:
* kex: diffie-hellman-group-exchange-sha1
* host_key: ssh-rsa
* encryption_server: 3des-cbc
* encryption_client: 3des-cbc
* hmac_client: hmac-sha1
* hmac_server: hmac-sha1
* compression_client: none
* compression_server: none
* language_client:
* language_server:
D, [2016-06-30T11:28:29.626568 #3544] DEBUG -- net.ssh.transport.algorithms[3fcba209bf84]: exchanging keys
D, [2016-06-30T11:28:29.626797 #3544] DEBUG -- socket[3fcba20a2578]: queueing packet nr 1 type 34 len 20
D, [2016-06-30T11:28:29.626919 #3544] DEBUG -- socket[3fcba20a2578]: sent 24 bytes
D, [2016-06-30T11:28:29.627706 #3544] DEBUG -- socket[3fcba20a2578]: read 152 bytes
D, [2016-06-30T11:28:29.627801 #3544] DEBUG -- socket[3fcba20a2578]: received packet nr 1 type 31 len 148
D, [2016-06-30T11:28:29.630634 #3544] DEBUG -- socket[3fcba20a2578]: queueing packet nr 2 type 32 len 140
D, [2016-06-30T11:28:29.630754 #3544] DEBUG -- socket[3fcba20a2578]: sent 144 bytes
D, [2016-06-30T11:28:29.770548 #3544] DEBUG -- socket[3fcba20a2578]: read 448 bytes
D, [2016-06-30T11:28:29.770711 #3544] DEBUG -- socket[3fcba20a2578]: received packet nr 2 type 33 len 444
D, [2016-06-30T11:28:29.773198 #3544] DEBUG -- socket[3fcba20a2578]: queueing packet nr 3 type 21 len 20
D, [2016-06-30T11:28:29.773311 #3544] DEBUG -- socket[3fcba20a2578]: sent 24 bytes
D, [2016-06-30T11:28:29.773398 #3544] DEBUG -- socket[3fcba20a2578]: read 16 bytes
D, [2016-06-30T11:28:29.773499 #3544] DEBUG -- socket[3fcba20a2578]: received packet nr 3 type 21 len 12
D, [2016-06-30T11:28:29.773823 #3544] DEBUG -- net.ssh.authentication.session[3fcba2036670]: beginning authentication of `<username>'
D, [2016-06-30T11:28:29.774007 #3544] DEBUG -- socket[3fcba20a2578]: queueing packet nr 4 type 5 len 28
D, [2016-06-30T11:28:29.774103 #3544] DEBUG -- socket[3fcba20a2578]: sent 52 bytes
D, [2016-06-30T11:28:29.971057 #3544] DEBUG -- socket[3fcba20a2578]: read 52 bytes
D, [2016-06-30T11:28:29.971236 #3544] DEBUG -- socket[3fcba20a2578]: received packet nr 4 type 6 len 28
D, [2016-06-30T11:28:29.971448 #3544] DEBUG -- net.ssh.authentication.session[3fcba2036670]: trying password
D, [2016-06-30T11:28:29.971693 #3544] DEBUG -- socket[3fcba20a2578]: queueing packet nr 5 type 50 len 68
D, [2016-06-30T11:28:29.971822 #3544] DEBUG -- socket[3fcba20a2578]: sent 92 bytes
D, [2016-06-30T11:28:29.977018 #3544] DEBUG -- socket[3fcba20a2578]: read 1072 bytes
D, [2016-06-30T11:28:29.977141 #3544] DEBUG -- socket[3fcba20a2578]: read 368 bytes
D, [2016-06-30T11:28:29.977506 #3544] DEBUG -- socket[3fcba20a2578]: read 1072 bytes
D, [2016-06-30T11:28:29.977618 #3544] DEBUG -- socket[3fcba20a2578]: read 388 bytes
D, [2016-06-30T11:28:29.977861 #3544] DEBUG -- socket[3fcba20a2578]: received packet nr 5 type 53 len 2876
I, [2016-06-30T11:28:29.977927 #3544]  INFO -- net.ssh.authentication.session[3fcba2036670]:
D, [2016-06-30T11:28:29.983507 #3544] DEBUG -- socket[3fcba20a2578]: read 36 bytes
D, [2016-06-30T11:28:29.983623 #3544] DEBUG -- socket[3fcba20a2578]: received packet nr 6 type 52 len 12
D, [2016-06-30T11:28:29.983739 #3544] DEBUG -- net.ssh.authentication.methods.password[3fcba20322f0]: password succeeded
D, [2016-06-30T11:28:29.984007 #3544] DEBUG -- socket[3fcba20a2578]: queueing packet nr 6 type 90 len 36
D, [2016-06-30T11:28:29.984264 #3544] DEBUG -- socket[3fcba20a2578]: sent 60 bytes
D, [2016-06-30T11:28:29.985069 #3544] DEBUG -- socket[3fcba20a2578]: read 52 bytes
D, [2016-06-30T11:28:29.985235 #3544] DEBUG -- socket[3fcba20a2578]: received packet nr 7 type 91 len 28
I, [2016-06-30T11:28:29.985329 #3544]  INFO -- net.ssh.connection.session[3fcba20269c8]: channel_open_confirmation: 0 3 8192 4096
I, [2016-06-30T11:28:29.985502 #3544]  INFO -- net.ssh.connection.channel[3fcba2026810]: sending channel request "env"
D, [2016-06-30T11:28:29.985592 #3544] DEBUG -- socket[3fcba20a2578]: queueing packet nr 7 type 98 len 44
I, [2016-06-30T11:28:29.985709 #3544]  INFO -- net.ssh.connection.channel[3fcba2026810]: sending channel request "exec"
D, [2016-06-30T11:28:29.985818 #3544] DEBUG -- socket[3fcba20a2578]: queueing packet nr 8 type 98 len 44
D, [2016-06-30T11:28:29.985972 #3544] DEBUG -- socket[3fcba20a2578]: sent 136 bytes
D, [2016-06-30T11:28:29.987055 #3544] DEBUG -- socket[3fcba20a2578]: read 36 bytes
D, [2016-06-30T11:28:29.987243 #3544] DEBUG -- socket[3fcba20a2578]: received packet nr 8 type 99 len 12
I, [2016-06-30T11:28:29.987322 #3544]  INFO -- net.ssh.connection.session[3fcba20269c8]: channel_success: 0
D, [2016-06-30T11:28:29.990153 #3544] DEBUG -- socket[3fcba20a2578]: read 556 bytes
D, [2016-06-30T11:28:29.990432 #3544] DEBUG -- socket[3fcba20a2578]: received packet nr 9 type 94 len 532
I, [2016-06-30T11:28:29.990531 #3544]  INFO -- net.ssh.connection.session[3fcba20269c8]: channel_data: 0 516b
D, [2016-06-30T11:28:30.090502 #3544] DEBUG -- socket[3fcba20a2578]: read 96 bytes
D, [2016-06-30T11:28:30.090679 #3544] DEBUG -- socket[3fcba20a2578]: read 36 bytes
D, [2016-06-30T11:28:30.090880 #3544] DEBUG -- socket[3fcba20a2578]: received packet nr 10 type 98 len 36
I, [2016-06-30T11:28:30.091044 #3544]  INFO -- net.ssh.connection.session[3fcba20269c8]: channel_request: 0 exit-status false
D, [2016-06-30T11:28:30.091172 #3544] DEBUG -- socket[3fcba20a2578]: read 0 bytes
/Library/Ruby/Gems/2.0.0/gems/net-ssh-3.2.0/lib/net/ssh/transport/packet_stream.rb:89:in `next_packet': connection closed by remote host (Net::SSH::Disconnect)
  from /Library/Ruby/Gems/2.0.0/gems/net-ssh-3.2.0/lib/net/ssh/transport/session.rb:193:in `block in poll_message'
  from /Library/Ruby/Gems/2.0.0/gems/net-ssh-3.2.0/lib/net/ssh/transport/session.rb:188:in `loop'
  from /Library/Ruby/Gems/2.0.0/gems/net-ssh-3.2.0/lib/net/ssh/transport/session.rb:188:in `poll_message'
  from /Library/Ruby/Gems/2.0.0/gems/net-ssh-3.2.0/lib/net/ssh/connection/session.rb:474:in `dispatch_incoming_packets'
  from /Library/Ruby/Gems/2.0.0/gems/net-ssh-3.2.0/lib/net/ssh/connection/session.rb:225:in `preprocess'
  from /Library/Ruby/Gems/2.0.0/gems/net-ssh-3.2.0/lib/net/ssh/connection/session.rb:206:in `process'
  from /Library/Ruby/Gems/2.0.0/gems/net-ssh-3.2.0/lib/net/ssh/connection/session.rb:170:in `block in loop'
  from /Library/Ruby/Gems/2.0.0/gems/net-ssh-3.2.0/lib/net/ssh/connection/session.rb:170:in `loop'
  from /Library/Ruby/Gems/2.0.0/gems/net-ssh-3.2.0/lib/net/ssh/connection/session.rb:170:in `loop'
  from /Library/Ruby/Gems/2.0.0/gems/net-ssh-3.2.0/lib/net/ssh/connection/channel.rb:269:in `wait'
  from /Library/Ruby/Gems/2.0.0/gems/net-ssh-3.2.0/lib/net/ssh/connection/session.rb:368:in `exec!'
  from main.rb:19:in `block (2 levels) in <main>'
  from main.rb:18:in `each'
  from main.rb:18:in `block in <main>'
  from main.rb:13:in `each'
  from main.rb:13:in `<main>'




Cisco Router Output:

SSH1: starting SSH control process
SSH1: sent protocol version id SSH-2.0-Cisco-1.25
SSH1: protocol version id is - SSH-2.0-Ruby/Net::SSH_3.2.0 universal.x86_64-darwin15
SSH2 1: kexinit sent: encryption algo = 3des-cbc
SSH2 1: kexinit sent: mac algo = hmac-sha1
SSH2 1: SSH2_MSG_KEXINIT sent
SSH2 1: SSH2_MSG_KEXINIT received
SSH2 1: kex: client->server enc:3des-cbc mac:hmac-sha1
SSH2 1: kex: server->client enc:3des-cbc mac:hmac-sha1
SSH2 1: Using kex_algo = diffie-hellman-group-exchange-sha1
SSH2 1: SSH2_MSG_KEX_DH_GEX_REQUEST received
SSH2 1: Range sent by client is - 1024 < 1024 < 8192
SSH2 1:  Modulus size established : 1024 bits
SSH2 1: expecting SSH2_MSG_KEX_DH_GEX_INIT
SSH2 1: SSH2_MSG_KEXDH_INIT received
SSH2: kex_derive_keys complete
SSH2 1: SSH2_MSG_NEWKEYS sent
SSH2 1: waiting for SSH2_MSG_NEWKEYS
SSH2 1: SSH2_MSG_NEWKEYS received
%SSH-5-SSH2_SESSION: SSH2 Session request from <server ip address> (tty = 1) using crypto cipher '3des-cbc', hmac 'hmac-sha1' Succeeded
SSH2 1: Using method = password
SSH2 1: authentication successful for <username>
%SSH-5-SSH2_USERAUTH: User <username> authentication for SSH2 Session from <server ip address> (tty = 1) using crypto cipher '3des-cbc', hmac 'hmac-sha1' Succeeded
SSH2 1: channel open request
SSH2 1: env request
SSH2 1: exec request
SSH2 1: exec message received
SSH2 1: starting shell for vty
%SSH-5-SSH2_CLOSE: SSH2 Session from <server ip address> (tty = 1) for user <username> using crypto cipher '3des-cbc', hmac 'hmac-sha1' closed
SSH1: Session terminated normally

**Comment by mfazekas** [comment]
4.0.0.beta3 should be fixing this issue. See #422 and #421
