### ISSUE TITLE
Ssh config parsing doesnt seem to handle %

### ISSUE THREAD

**Issue by ktaragorn** [net-ssh/net-ssh#391]
This is on `net-ssh` v 2.6.4, so if it has been fixed please do close.

My ssh config is similar to this gist https://gist.github.com/ktaragorn081a64ad54d29ffd9a6acebc7b1ce5e1
The crucial part is 
```
Host *.xyz.com
Hostname %h
```
When i do `Net::SSH.start(host, user)` with host = "abc.xyz.com", I get `SocketError: getaddrinfo: nodename nor servname provided, or not known` because infact, just before `Transport::Session` is initialized, `host` is set to `%h` instead of expanding that wildcard.

**Comment by mfazekas** [comment]
Should have been fixed in 2.6.8
see https://github.com/net-ssh/net-ssh/commit/cfd64a41ce160bb1b3b552d45327e97e2d37780d
