### ISSUE TITLE
Block multiples login

### ISSUE THREAD

**Issue by soarde** [net-ssh/net-ssh#399]
Hello,

I log using SshClient from lib, after connected, send the command "w" to list users logged, but it does not appear, see:

Connected with SSH.NET Lib
 16:13:18 up 4 days, 23:12,  0 user,  load average: 0.00, 0.01, 0.05
USER     TTY      FROM             LOGIN@   IDLE   JCPU   PCPU WHAT

Connected with PuTTY
16:22:00 up 4 days, 23:20,  1 user,  load average: 0.00, 0.01, 0.05
USER     TTY      FROM             LOGIN@   IDLE   JCPU   PCPU WHAT
batling      pts/0    189.65.127.54    16:21    2.00s  0.10s  0.00s w

If me connect with Putty, my user list, because this i cant block login case this user is logged in.

I need block for can log just one session per user on any computer.

Thanks a lot, sorry for bad english.

**Comment by mfazekas** [comment]
You should be able to use request_pty to request a pty then it will show up on the 'w' command.

**Comment by soarde** [comment]
how i change this?
