### ISSUE TITLE
Feature request: Equivalent of $CHILD_STATUS

### ISSUE THREAD

**Issue by crantok** [net-ssh/net-ssh#404]
I can see from a [stackoverflow question](http://stackoverflow.com/questions/3386233/how-to-get-exit-status-with-rubys-netssh-library) that it is possible to get the exit status of a command by a fine-grained use of net-ssh. Would you consider adding an equivalent of $CHILD_STATUS so that this information could be discovered even after using Session#exec!() ?

**Comment by mfazekas** [comment]
This is a valid request i'd propose an API like this:
```
output = ssh.exec!('ls -la foo')
puts "Exit status=#{output.exit_status}"
```
