### ISSUE TITLE
broken pipe error during negotiate for RHEL7/CENTOS7 guests

### ISSUE THREAD

**Issue by raghavendra-talur** [net-ssh/net-ssh#405]
Hi,

I know this might not be a bug in net-ssh and is rather a configuration problem but I wanted to confirm once for myself and for others facing the same problem.

When we are using vagrant-libvirt with remote host option, during creation of VM, negotiate fails with a broken pipe error.

I have tried the following scenarios

Scenario A
vagrant host: fedora 24
libvirt host: rhel 6
guest os/vagrant box: fedora 24
status: works

Scenario A
vagrant host: fedora 24
libvirt host: rhel 6
guest os/vagrant box: RHEL7
status: Does not work

Scenario C
vagrant host: fedora 24
libvirt host: rhel 6
guest os/vagrant box: CENTOS7
status: Does not work

If I insert a sleep before in initialize method before negotiate at line 32 of server_version.rb then the problem goes away. The number of seconds that is required for it to work varied from 5 to 8. I understand that sleep is not a good solution and am looking for possible config solutions. I have tried ServerAliveInterval and ClientAliveInterval with various values and none of them seemed to work. I suspect it is key generation happening on first start of sshd causing this as subsequest ssh commands work.

Given below is the backtrace:

/home/rtalur/Appdata/vagrant/data/gems/gems/net-ssh-3.2.0/lib/net/ssh/transport/server_version.rb:45:in `write': Broken pipe (Errno::EPIPE)
        from /home/rtalur/Appdata/vagrant/data/gems/gems/net-ssh-3.2.0/lib/net/ssh/transport/server_version.rb:45:in `negotiate!'
        from /home/rtalur/Appdata/vagrant/data/gems/gems/net-ssh-3.2.0/lib/net/ssh/transport/server_version.rb:32:in `initialize'
        from /home/rtalur/Appdata/vagrant/data/gems/gems/net-ssh-3.2.0/lib/net/ssh/transport/session.rb:84:in `new'
        from /home/rtalur/Appdata/vagrant/data/gems/gems/net-ssh-3.2.0/lib/net/ssh/transport/session.rb:84:in `initialize'
        from /home/rtalur/Appdata/vagrant/data/gems/gems/net-ssh-3.2.0/lib/net/ssh.rb:232:in `new'
        from /home/rtalur/Appdata/vagrant/data/gems/gems/net-ssh-3.2.0/lib/net/ssh.rb:232:in `start'
        from /usr/share/vagrant/plugins/communicators/ssh/communicator.rb:389:in `block (2 levels) in connect'
        from /usr/share/ruby/timeout.rb:91:in `block in timeout'
        from /usr/share/ruby/timeout.rb:33:in `block in catch'
        from /usr/share/ruby/timeout.rb:33:in `catch'
        from /usr/share/ruby/timeout.rb:33:in `catch'
        from /usr/share/ruby/timeout.rb:106:in `timeout'
        from /usr/share/vagrant/plugins/communicators/ssh/communicator.rb:368:in `block in connect'
        from /usr/share/vagrant/lib/vagrant/util/retryable.rb:17:in `retryable'
        from /usr/share/vagrant/plugins/communicators/ssh/communicator.rb:367:in `connect'
        from /usr/share/vagrant/plugins/communicators/ssh/communicator.rb:125:in `ready?'
        from /home/rtalur/Appdata/vagrant/data/gems/gems/vagrant-libvirt-0.0.33/lib/vagrant-libvirt/action/wait_till_up.rb:66:in `block (2 levels) in call'
        from /usr/share/vagrant/lib/vagrant/util/retryable.rb:17:in `retryable'
        from /home/rtalur/Appdata/vagrant/data/gems/gems/vagrant-libvirt-0.0.33/lib/vagrant-libvirt/action/wait_till_up.rb:58:in `block in call'
        from /home/rtalur/Appdata/vagrant/data/gems/gems/vagrant-libvirt-0.0.33/lib/vagrant-libvirt/util/timer.rb:9:in `time'
        from /home/rtalur/Appdata/vagrant/data/gems/gems/vagrant-libvirt-0.0.33/lib/vagrant-libvirt/action/wait_till_up.rb:56:in `call'
        from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
        from /home/rtalur/Appdata/vagrant/data/gems/gems/vagrant-libvirt-0.0.33/lib/vagrant-libvirt/action/start_domain.rb:294:in `call'
        from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
        from /home/rtalur/Appdata/vagrant/data/gems/gems/vagrant-libvirt-0.0.33/lib/vagrant-libvirt/action/set_boot_order.rb:60:in `call'
        from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
        from /home/rtalur/Appdata/vagrant/data/gems/gems/vagrant-libvirt-0.0.33/lib/vagrant-libvirt/action/create_network_interfaces.rb:139:in `call'
        from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
        from /home/rtalur/Appdata/vagrant/data/gems/gems/vagrant-libvirt-0.0.33/lib/vagrant-libvirt/action/create_networks.rb:80:in `call'
        from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
        from /home/rtalur/Appdata/vagrant/data/gems/gems/vagrant-libvirt-0.0.33/lib/vagrant-libvirt/action/share_folders.rb:20:in `call'
        from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
        from /home/rtalur/Appdata/vagrant/data/gems/gems/vagrant-libvirt-0.0.33/lib/vagrant-libvirt/action/prepare_nfs_settings.rb:18:in `call'
        from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
        from /usr/share/vagrant/lib/vagrant/action/builtin/synced_folders.rb:87:in `call'
        from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
        from /usr/share/vagrant/lib/vagrant/action/builtin/synced_folder_cleanup.rb:28:in `call'
        from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
        from /usr/share/vagrant/plugins/synced_folders/nfs/action_cleanup.rb:25:in `call'
        from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
        from /home/rtalur/Appdata/vagrant/data/gems/gems/vagrant-libvirt-0.0.33/lib/vagrant-libvirt/action/prepare_nfs_valid_ids.rb:12:in `call'
        from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
        from /home/rtalur/Appdata/vagrant/data/gems/gems/vagrant-cachier-1.2.1/lib/vagrant-cachier/action/install_buckets.rb:14:in `call'
        from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
        from /home/rtalur/Appdata/vagrant/data/gems/gems/vagrant-rekey-ssh-0.1.9/lib/vagrant-rekey-ssh/actions/secure_box.rb:17:in `call'
        from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
        from /home/rtalur/Appdata/vagrant/data/gems/gems/vagrant-timezone-1.1.0/lib/vagrant-timezone/action/set_timezone.rb:13:in `call'
        from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
        from /usr/share/vagrant/lib/vagrant/action/builtin/provision.rb:80:in `call'
        from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
        from /home/rtalur/Appdata/vagrant/data/gems/gems/vagrant-cachier-1.2.1/lib/vagrant-cachier/action/configure_bucket_root.rb:20:in `call'
        from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
        from /home/rtalur/Appdata/vagrant/data/gems/gems/vagrant-libvirt-0.0.33/lib/vagrant-libvirt/action/create_domain.rb:236:in `call'
        from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
        from /home/rtalur/Appdata/vagrant/data/gems/gems/vagrant-libvirt-0.0.33/lib/vagrant-libvirt/action/create_domain_volume.rb:51:in `call'
        from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
        from /home/rtalur/Appdata/vagrant/data/gems/gems/vagrant-libvirt-0.0.33/lib/vagrant-libvirt/action/handle_box_image.rb:111:in `call'
        from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
        from /usr/share/vagrant/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
        from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
        from /home/rtalur/Appdata/vagrant/data/gems/gems/vagrant-libvirt-0.0.33/lib/vagrant-libvirt/action/handle_storage_pool.rb:50:in `call'
        from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
        from /home/rtalur/Appdata/vagrant/data/gems/gems/vagrant-libvirt-0.0.33/lib/vagrant-libvirt/action/set_name_of_domain.rb:35:in `call'
        from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
        from /usr/share/vagrant/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
        from /usr/share/vagrant/lib/vagrant/action/builder.rb:116:in `call'
        from /usr/share/vagrant/lib/vagrant/action/runner.rb:66:in `block in run'
        from /usr/share/vagrant/lib/vagrant/util/busy.rb:19:in `busy'
        from /usr/share/vagrant/lib/vagrant/action/runner.rb:66:in `run'
        from /usr/share/vagrant/lib/vagrant/action/builtin/call.rb:53:in `call'
        from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
        from /usr/share/vagrant/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
        from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
        from /home/rtalur/Appdata/vagrant/data/gems/gems/vagrant-rekey-ssh-0.1.9/lib/vagrant-rekey-ssh/actions/ssh_info.rb:47:in `call'
        from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
        from /usr/share/vagrant/lib/vagrant/action/builder.rb:116:in `call'
        from /usr/share/vagrant/lib/vagrant/action/runner.rb:66:in `block in run'
        from /usr/share/vagrant/lib/vagrant/util/busy.rb:19:in `busy'
        from /usr/share/vagrant/lib/vagrant/action/runner.rb:66:in `run'
        from /usr/share/vagrant/lib/vagrant/machine.rb:224:in `action_raw'
        from /usr/share/vagrant/lib/vagrant/machine.rb:199:in `block in action'
        from /usr/share/vagrant/lib/vagrant/environment.rb:561:in `lock'
        from /usr/share/vagrant/lib/vagrant/machine.rb:185:in `call'
        from /usr/share/vagrant/lib/vagrant/machine.rb:185:in `action'
        from /usr/share/vagrant/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'

WORKAROUND: for other users, insert a sleep before negotiate as mentioned above.

**Comment by mfazekas** [comment]
@raghavendra-talur it's strange that adding a sleep solves the issue. AFAIK Broken Pipe happens when you try to write to a socket that's closed on the other end. Not sure how writing later solves this.

Is this something i can reproduce?

**Comment by mfazekas** [comment]
will be reopened when we have more details/we can reproduce
