### ISSUE TITLE
Replicating ssh-keyscan with net-ssh

### ISSUE THREAD

**Issue by maran** [net-ssh/net-ssh#406]
I was wondering if it's possible to get the same output you get when using `ssh-keyscan hostname.com` using net-ssh. I would prefer to have all my code be ruby and not having to shell out.

**Comment by mfazekas** [comment]
@maran i'm sure you can get the same output, please take a look at Net::SSH::KnownHosts. I'm not aware that such code already exists.

**Comment by dLobatog** [comment]
Just for the record - no it's not possible to get the same output. 'ssh-keyscan' actually tries to fetch the key, whereas KnownHosts simply looks in all `known_hosts` files
