### ISSUE TITLE
connection is nil during do_request

### ISSUE THREAD

**Issue by kt97679** [net-ssh/net-ssh#411]
Hi folks,

I'm using net-ssh as part of my tool https://github.com/kt97679/one-ssh. Sometime I see following error:
<pre>
/home/kirill.timofeev/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/net-ssh-3.2.0/lib/net/ssh/connection/channel.rb:574:in `do_request': undefined method `send_message' for nil:NilClass (NoMethodError)
        from /home/kirill.timofeev/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/net-ssh-3.2.0/lib/net/ssh/connection/session.rb:588:in `channel_request'
        from /home/kirill.timofeev/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/em-ssh-0.7.0/lib/em-ssh/session.rb:67:in `block in register_callbacks'
        from /home/kirill.timofeev/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/em-ssh-0.7.0/lib/em-ssh/callbacks.rb:85:in `call'
        from /home/kirill.timofeev/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/em-ssh-0.7.0/lib/em-ssh/callbacks.rb:41:in `block in fire'
        from /home/kirill.timofeev/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/em-ssh-0.7.0/lib/em-ssh/callbacks.rb:41:in `map'
        from /home/kirill.timofeev/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/em-ssh-0.7.0/lib/em-ssh/callbacks.rb:41:in `fire'
        from /home/kirill.timofeev/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/em-ssh-0.7.0/lib/em-ssh/connection.rb:321:in `block in register_data_handler'
        from /home/kirill.timofeev/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/em-ssh-0.7.0/lib/em-ssh/callbacks.rb:85:in `call'
        from /home/kirill.timofeev/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/em-ssh-0.7.0/lib/em-ssh/callbacks.rb:41:in `block in fire'
        from /home/kirill.timofeev/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/em-ssh-0.7.0/lib/em-ssh/callbacks.rb:41:in `map'
        from /home/kirill.timofeev/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/em-ssh-0.7.0/lib/em-ssh/callbacks.rb:41:in `fire'
        from /home/kirill.timofeev/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/em-ssh-0.7.0/lib/em-ssh/connection.rb:140:in `receive_data'
        from /home/kirill.timofeev/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run_machine'
        from /home/kirill.timofeev/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run'
        from /home/kirill.timofeev/git/one-ssh/lib/ossh.rb:334:in `run'
        from /home/kirill.timofeev/git/one-ssh/lib/ossh.rb:409:in `run'
        from /home/kirill.timofeev/bin/ossh:10:in `<main>'
</pre>

From what I see this is caused by the nil value in the @connection in the Channel.

Please advise if this is expected behavior and I need to handle it somehow in my tool.

Thanks,
Kirill.

**Comment by kt97679** [comment]
I changed channel.rb as follows:
<pre>
574c574
<           connection.send_message(msg)
---
>           connection.send_message(msg) if @connection
</pre>
This solves my issue, but I'm not sure if this is a right fix.

**Comment by mfazekas** [comment]
Please report this error to em-ssh.
