### ISSUE TITLE
Keyboard Interactive Authentication Can Hang Indefinitely

### ISSUE THREAD

**Issue by NeilBetham** [net-ssh/net-ssh#412]
Hello,

I'm currently having a problem where threads are hanging while trying to authenticate to a remote host. The problem is that the `authenticate` method for the `KeyboardAuthentication` class is not using a timeout in its select call. So when it selects on a connection that doesn't reply to a request that call will hang indefinitely, which seems to be the case based on where the hang is occurring in the code.

Would it be possible to use the timeout from the initial start options hash to fail out of authentication if the select times out with nothing to read?

Thanks

P.S. Here's the backtrace of the hung thread:

    ~/.rvm/gems/ruby-2.3.1/gems/net-ssh-3.2.0/lib/net/ssh/ruby_compat.rb:25:in `select'"
    ~/.rvm/gems/ruby-2.3.1/gems/net-ssh-3.2.0/lib/net/ssh/ruby_compat.rb:25:in `io_select'"
    ~/.rvm/gems/ruby-2.3.1/gems/net-ssh-3.2.0/lib/net/ssh/transport/packet_stream.rb:100:in `block (2 levels) in next_packet'"
    ~/.rvm/gems/ruby-2.3.1/gems/net-ssh-3.2.0/lib/net/ssh/transport/packet_stream.rb:99:in `loop'"
    ~/.rvm/gems/ruby-2.3.1/gems/net-ssh-3.2.0/lib/net/ssh/transport/packet_stream.rb:99:in `block in next_packet'"
    ~/.rvm/gems/ruby-2.3.1/gems/net-ssh-3.2.0/lib/net/ssh/transport/packet_stream.rb:95:in `loop'"
    ~/.rvm/gems/ruby-2.3.1/gems/net-ssh-3.2.0/lib/net/ssh/transport/packet_stream.rb:95:in `next_packet'"
    ~/.rvm/gems/ruby-2.3.1/gems/net-ssh-3.2.0/lib/net/ssh/transport/session.rb:193:in `block in poll_message'"
    ~/.rvm/gems/ruby-2.3.1/gems/net-ssh-3.2.0/lib/net/ssh/transport/session.rb:188:in `loop'"
    ~/.rvm/gems/ruby-2.3.1/gems/net-ssh-3.2.0/lib/net/ssh/transport/session.rb:188:in `poll_message'"
    ~/.rvm/gems/ruby-2.3.1/gems/net-ssh-3.2.0/lib/net/ssh/transport/session.rb:173:in `next_message'"
    ~/.rvm/gems/ruby-2.3.1/gems/net-ssh-3.2.0/lib/net/ssh/authentication/session.rb:95:in `block in next_message'"
    ~/.rvm/gems/ruby-2.3.1/gems/net-ssh-3.2.0/lib/net/ssh/authentication/session.rb:94:in `loop'"
    ~/.rvm/gems/ruby-2.3.1/gems/net-ssh-3.2.0/lib/net/ssh/authentication/session.rb:94:in `next_message'"
    ~/.rvm/gems/ruby-2.3.1/gems/net-ssh-3.2.0/lib/net/ssh/authentication/methods/keyboard_interactive.rb:22:in `block in authenticate'"
    ~/.rvm/gems/ruby-2.3.1/gems/net-ssh-3.2.0/lib/net/ssh/authentication/methods/keyboard_interactive.rb:21:in `loop'"
    ~/.rvm/gems/ruby-2.3.1/gems/net-ssh-3.2.0/lib/net/ssh/authentication/methods/keyboard_interactive.rb:21:in `authenticate'"
    ~/.rvm/gems/ruby-2.3.1/gems/net-ssh-3.2.0/lib/net/ssh/authentication/session.rb:79:in `block in authenticate'"
    ~/.rvm/gems/ruby-2.3.1/gems/net-ssh-3.2.0/lib/net/ssh/authentication/session.rb:66:in `each'"
    ~/.rvm/gems/ruby-2.3.1/gems/net-ssh-3.2.0/lib/net/ssh/authentication/session.rb:66:in `authenticate'"
    ~/.rvm/gems/ruby-2.3.1/gems/net-ssh-3.2.0/lib/net/ssh.rb:236:in `start'"

And the debug log of the ssh session auth:

    DEBUG -- net.ssh.transport.server_version[3fe009936dbc]: remote is `SSH-2.0-OpenSSH_7.2'
     INFO -- net.ssh.transport.algorithms[3fe008fa55c8]: sending KEXINIT
    DEBUG -- socket[3fe00995ab54]: queueing packet nr 0 type 20 len 1684
    DEBUG -- socket[3fe00995ab54]: sent 1688 bytes
    DEBUG -- socket[3fe00995ab54]: read 976 bytes
    DEBUG -- socket[3fe00995ab54]: received packet nr 0 type 20 len 972
     INFO -- net.ssh.transport.algorithms[3fe008fa55c8]: got KEXINIT from server
     INFO -- net.ssh.transport.algorithms[3fe008fa55c8]: negotiating algorithms
    DEBUG -- net.ssh.transport.algorithms[3fe008fa55c8]: negotiated:
    * kex: diffie-hellman-group14-sha1
    * host_key: ssh-rsa
    * encryption_server: aes128-ctr
    * encryption_client: aes128-ctr
    * hmac_client: hmac-sha1
    * hmac_server: hmac-sha1
    * compression_client: none
    * compression_server: none
    * language_client: 
    * language_server: 
    DEBUG -- net.ssh.transport.algorithms[3fe008fa55c8]: exchanging keys
    DEBUG -- socket[3fe00995ab54]: queueing packet nr 1 type 30 len 268
    DEBUG -- socket[3fe00995ab54]: sent 272 bytes
    DEBUG -- socket[3fe00995ab54]: read 848 bytes
    DEBUG -- socket[3fe00995ab54]: received packet nr 1 type 31 len 828
    DEBUG -- socket[3fe00995ab54]: queueing packet nr 2 type 21 len 20
    DEBUG -- socket[3fe00995ab54]: sent 24 bytes
    DEBUG -- socket[3fe00995ab54]: received packet nr 2 type 21 len 12
    DEBUG -- net.ssh.authentication.session[3fe008f0d0c0]: beginning authentication of `local'
    DEBUG -- socket[3fe00995ab54]: queueing packet nr 3 type 5 len 28
    DEBUG -- socket[3fe00995ab54]: sent 52 bytes
    DEBUG -- socket[3fe00995ab54]: read 52 bytes
    DEBUG -- socket[3fe00995ab54]: received packet nr 3 type 6 len 28
    DEBUG -- net.ssh.authentication.session[3fe008f0d0c0]: trying none
    DEBUG -- socket[3fe00995ab54]: queueing packet nr 4 type 50 len 44
    DEBUG -- socket[3fe00995ab54]: sent 68 bytes
    DEBUG -- socket[3fe00995ab54]: read 84 bytes
    DEBUG -- socket[3fe00995ab54]: received packet nr 4 type 51 len 60
    DEBUG -- net.ssh.authentication.session[3fe008f0d0c0]: allowed methods: publickey,password,keyboard-interactive
    DEBUG -- net.ssh.authentication.methods.none[3fe008f00078]: none failed
    DEBUG -- net.ssh.authentication.session[3fe008f0d0c0]: trying publickey
    DEBUG -- net.ssh.authentication.agent[3fe008eed784]: connecting to ssh-agent
    ERROR -- net.ssh.authentication.agent[3fe008eed784]: could not connect to ssh-agent
    DEBUG -- net.ssh.authentication.methods.publickey[3fe008ef0394]: trying publickey ()
    DEBUG -- socket[3fe00995ab54]: queueing packet nr 5 type 50 len 348
    DEBUG -- socket[3fe00995ab54]: sent 372 bytes
    DEBUG -- socket[3fe00995ab54]: read 84 bytes
    DEBUG -- socket[3fe00995ab54]: received packet nr 5 type 51 len 60
    DEBUG -- net.ssh.authentication.session[3fe008f0d0c0]: allowed methods: publickey,password,keyboard-interactive
    DEBUG -- net.ssh.authentication.session[3fe008f0d0c0]: trying password
    DEBUG -- socket[3fe00995ab54]: queueing packet nr 6 type 50 len 60
    DEBUG -- socket[3fe00995ab54]: sent 84 bytes
    DEBUG -- socket[3fe00995ab54]: read 84 bytes
    DEBUG -- socket[3fe00995ab54]: received packet nr 6 type 51 len 60
    DEBUG -- net.ssh.authentication.session[3fe008f0d0c0]: allowed methods: publickey,password,keyboard-interactive
    DEBUG -- net.ssh.authentication.methods.password[3fe008ed9c20]: password failed
    DEBUG -- net.ssh.authentication.session[3fe008f0d0c0]: trying keyboard-interactive
    DEBUG -- net.ssh.authentication.methods.keyboard_interactive[3fe00c0dbd54]: trying keyboard-interactive
    DEBUG -- socket[3fe00995ab54]: queueing packet nr 7 type 50 len 76
    DEBUG -- socket[3fe00995ab54]: sent 100 bytes

**Comment by mfazekas** [comment]
Do you know why the server is not responding? Do you have logs on the server?
Can command line ```ssh``` connect to that server?

Adding timeout is more a workaround than a solution. Also ideally we should be moving away from those ```message = session.next_message``` to a more event based approach, where that timeout would require different approach.

**Comment by NeilBetham** [comment]
I don't know why it's not responding or have logs for the session on the server side of things. I did try ssh-ing the server while the session in ruby was hung and didn't have any issues connecting. I will try to get a verbose log of the server side to see what's going on there and post it back here.

**Comment by mfazekas** [comment]
will be repopened when we have more details

**Comment by NeilBetham** [comment]
As a follow up. I haven't been able to repro this issue. I think it was largely do to me using the library incorrectly. I fixed that problem and haven't seen the issue since.

**Comment by aughr** [comment]
I'm seeing similar behavior to this when talking to a vendor BMC device. It's entirely possible it's behaving badly, but there's not much I can do about that. The process has been hung for eight days with the TCP connection still open:

`TCP myhost:44742->bmchost:ssh (ESTABLISHED)`

Here's the backtrace:
```
.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/net-ssh-3.2.0/lib/net/ssh/ruby_compat.rb:25:in `select'
.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/net-ssh-3.2.0/lib/net/ssh/ruby_compat.rb:25:in `io_select'
.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/net-ssh-3.2.0/lib/net/ssh/transport/packet_stream.rb:100:in `block (2 levels) in next_packet'
.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/net-ssh-3.2.0/lib/net/ssh/transport/packet_stream.rb:99:in `loop'
.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/net-ssh-3.2.0/lib/net/ssh/transport/packet_stream.rb:99:in `block in next_packet'
.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/net-ssh-3.2.0/lib/net/ssh/transport/packet_stream.rb:95:in `loop'
.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/net-ssh-3.2.0/lib/net/ssh/transport/packet_stream.rb:95:in `next_packet'
.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/net-ssh-3.2.0/lib/net/ssh/transport/session.rb:193:in `block in poll_message'
.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/net-ssh-3.2.0/lib/net/ssh/transport/session.rb:188:in `loop'
.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/net-ssh-3.2.0/lib/net/ssh/transport/session.rb:188:in `poll_message'
.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/net-ssh-3.2.0/lib/net/ssh/transport/session.rb:173:in `next_message'
.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/net-ssh-3.2.0/lib/net/ssh/authentication/session.rb:95:in `block in next_message'
.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/net-ssh-3.2.0/lib/net/ssh/authentication/session.rb:94:in `loop'
.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/net-ssh-3.2.0/lib/net/ssh/authentication/session.rb:94:in `next_message'
.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/net-ssh-3.2.0/lib/net/ssh/authentication/methods/password.rb:25:in `authenticate'
.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/net-ssh-3.2.0/lib/net/ssh/authentication/session.rb:79:in `block in authenticate'
.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/net-ssh-3.2.0/lib/net/ssh/authentication/session.rb:66:in `each'
.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/net-ssh-3.2.0/lib/net/ssh/authentication/session.rb:66:in `authenticate'
.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/net-ssh-3.2.0/lib/net/ssh.rb:236:in `start'
```

**Comment by mfazekas** [comment]
@aughr  do you have server side logs? Ideall would be if i could connect to repro. Does command line ssh works, with what auth method? It seems to be hanging with password auth, is this you want to auth with?

**Comment by aughr** [comment]
I don't have any logs afaik, unfortunately. This failure only happens sporadically, too. Most of the time it works.
