### ISSUE TITLE
net-ssh does not support ruby 1.9 but can be installed on it

### ISSUE THREAD

**Issue by drbrain** [net-ssh/net-ssh#414]
The readme states that net-ssh newer than 2.9 do not support ruby 1.9.x.  It seems this was OK until  #247 was merged which uses parameters to Socket.tcp that only exist in modern ruby.

Since support for ruby 1.9.x was dropped long ago the gem should set its required_ruby_version appropriately.

**Comment by mfazekas** [comment]
which version are your referring to? master already has required_ruby_version https://github.com/net-ssh/net-ssh/blob/master/net-ssh.gemspec#L19

**Comment by drbrain** [comment]
And I can't reproduce it now, so I'm unsure how 3.2.0 got installed.
