### ISSUE TITLE
Backport fix #385 to 3.2.x branch

### ISSUE THREAD

**Issue by johnnyshields** [net-ssh/net-ssh#415]
Issue #385 addresses an issue with Pageant authentication affecting Windows users. After upgrading to Windows 10 I started seeing this very frequently.

I'd like to request net-ssh team to release v3.2.1 which has this fix.

**Comment by mfazekas** [comment]
Can you confirm this fix working in net-ssh-4.0.0-beta1 both on 32-bit and 64-bit windows?

**Comment by johnnyshields** [comment]
@mfazekas the fix itself works however net-ssh-4.0.0-beta had other issues when I tried it. We should backport to 3.2.x to provide a stable fix.

**Comment by mfazekas** [comment]
What is the issue you're having with 4.0.0-beta?

**Comment by johnnyshields** [comment]
There was an interface change which causes it to error something about "password: nil" when deploying with Capistrano 2. Anyway, I don't want to upgrade to 4.0.0 at this time, and this is a critical bug to fix on 3.2.x branch.

**Comment by mfazekas** [comment]
3.2.1.beta1 release please verify that it work correctly with pageant on win32 and win64

**Comment by johnnyshields** [comment]
@mfazekas tested it on win64 and it looks good. do not have access to win32.
