### ISSUE TITLE
can't close network sockets using latest net-ssh

### ISSUE THREAD

**Issue by kt97679** [net-ssh/net-ssh#417]
Hi folks,

I've build tool to run commands in parallel on multiple servers: https://github.com/kt97679/one-ssh Previously I had issue with leaking file descriptors and resolved it like this: https://github.com/kt97679/one-ssh/blob/master/lib/ossh.rb#L95 This works ok with ruby 1.9.3p551 and following gems:

em-ssh (0.7.0)
eventmachine (1.2.0.1)
net-ssh (2.8.0)

unfortunately this doesn't work with ruby 2.3.1 and following gems:

em-ssh (0.7.0)
net-ssh (3.2.0)
eventmachine (1.2.0.1)

I looked through the sources but couldn't figure out what do I need to do with latest net-ssh to make it work again. Please advise how to resolve this.

Thanks,
Kirill.

**Comment by mfazekas** [comment]
Please report em-ssh related issues to https://github.com/simulacre/em-ssh/issues
Basically em-ssh hooks into internals of net-ssh and with any change in net-ssh em-ssh likely needs to be  updated as well.

**Comment by kt97679** [comment]
@mfazekas can you point me to the net-ssh change that resulted in the new behavior?

**Comment by kt97679** [comment]
@mfazekas here: https://github.com/kt97679/one-ssh/blob/master/lib/ossh.rb#L95 I'm using ch.connection, which is EventMachine::Ssh::Session and is subclass of Net::SSH::Connection::Session. From what I see close() method of Net::SSH::Connection::Session was not changed between net-ssh 2.8.0 and 3.2.0. Do you know if there is any other way to close ssh connection socket without modifying em-ssh?

**Comment by mfazekas** [comment]
I think those changes might be related:
https://github.com/net-ssh/net-ssh/commit/514311b28c614551571848e7dea96186274a7a1e
https://github.com/net-ssh/net-ssh/commit/a69fd4edb85026769e7bbdfd920f78704892e188

**Comment by kt97679** [comment]
Thanks @mfazekas unfortunately this doesn't help much :(. May there is some explicit way to close socket?

**Comment by mfazekas** [comment]
Sorry i cannot help you. As said em-ssh hooks into internals of net-ssh and you cannot just upgrade net-ssh and expect it to work with older em-ssh. Your report also lacks details, logs, exceptions, etc. But even those things were there i just don't have time for this, sorry.

**Comment by kt97679** [comment]
No worries, thanks @mfazekas
