### ISSUE TITLE
Proxy Command returns no such file or directory on Windows 10

### ISSUE THREAD

**Issue by MarioRuiz** [net-ssh/net-ssh#420]
I am tunneling an ssh connection using this code:

require 'net/ssh'
require 'net/ssh/proxy/command'

proxy = Net::SSH::Proxy::Command.new('ssh 139.48.136.62 nc')
Net::SSH.start('myserver.com, 'myuser, :password=>"mypwd", :proxy => proxy) do |my_ssh|
              my_ssh.open_channel do |channel|
                channel.exec("ls")
              end
end

And I get this message:

C:/Ruby22/lib/ruby/gems/2.2.0/gems/net-ssh-3.2.0/lib/net/ssh/proxy/command.rb:67:in `rescue in open': No such file or directory - ssh 139.48.136.62 nc (Net::SSH::Proxy::ConnectError)

**Comment by mfazekas** [comment]
Do you have ssh.exe on windows in your path?

**Comment by MarioRuiz** [comment]
to use net/ssh i don't need any ssh command line interpreter... 
do i need it for net/ssh/proxy? which ssh client is the one i should use then?

**Comment by mfazekas** [comment]
@MarioRuiz yes net/ssh doesn't require command line ssh. The proxy command does work with Popen see Net::SSH::Proxy::Command https://net-ssh.github.io/ssh/v2/api/classes/Net/SSH/Proxy/Command.html

You might be able to write a Proxy::Command that works via opening another net-ssh session.

**Comment by MarioRuiz** [comment]
@mfazekas i used the proxy command like you see in the example I posted but then i get the message No such file or directory

If I try to do the same with Putty I connect to myserver1.com:22 with myuser and mypwd
when i am connected then i perform this directly from the ssh connection:
ssh myserver2.com
and i supplied mypwd
then i am finally ssh connected to myserver2.com

**Comment by mfazekas** [comment]
What you pass to Net::SSH::Proxy::Command.new is a command line string that have to be executable. So if you don't have ssh on your path```No such file or directory``` is the expected behaviour.
Putty might do replacement there, we don't.

**Comment by MarioRuiz** [comment]
then @mfazekas  is it possible to run an ssh command inside a Net::Ssh connection... i tried but i don't get any output
