### ISSUE TITLE
channel.active? is true while session.closed? is also true

### ISSUE THREAD

**Issue by akostadinov** [net-ssh/net-ssh#425]
Hello, I'm hitting a situation when `channel.active?` shows true  while `session.closed?` is also true. This happens when connection to remote host is suddenly lost. For example:

```
channel = session.open_channel do |channel|
  channel.exec("reboot") do |ch, success|
    ...
  end
end
session.loop rescue nil
channel.active? => true
session.closed? => true
```

I think that `channel.active?` method should return false when session was already closed.

On the other hand, presently by checking `session` and `channel` status, one can conclude that when both are true, then session terminated unexpectedly. So I'm not sure how  to actually fix while being able to know the difference. Perhaps a new channel method would be needed to know whether it finished prematurely or not?

**Comment by mfazekas** [comment]
what is the version you're using?

**Comment by akostadinov** [comment]
sorry, net-ssh (3.2.0)

**Comment by mfazekas** [comment]
See #427 ```channel.remote_closed?``` should be set in such case. 

What is the usecase where you need to check ```channel.active?``` and expect it to be false in such case?

**Comment by akostadinov** [comment]
@mfazekas , well intuitively a channel cannot be active while connection is dead. So my complaint is that it is confusing that there's no single intuitive call to ensure something may still come from a channel.

For example, what I'm doing is creating a connection and starting a separate thread to `#loop` it. Then different threads can open channels and do stuff, etc. When I want thread to wait for operation to complete (i.e. channel to stop being active) I had used in the past `channel.active?` but it turned out if connection closed abruptly, the channel still showed up active and blocking the thread forever.

Now I'm checking both - `channel.active?` and `channel.connection.closed?`. This seems to be working fine according to my testing.

One related issue is reporting session termination cause. Presently I'm `#join`-ing the  `loop` thread and check for error. I'm wondering if there is a better approach.

**Comment by mfazekas** [comment]
I agree it's non intuitive, but its' what we have now. We have ```closed?, remote_closed?, active? ```
if a session is both ```close?``` and ```remote_closed?``` it will soon stop being ```acive?```
