### ISSUE TITLE
High frequency invoke ssh.exec! method will produce a large CLOSE_WAIT status connections

### ISSUE THREAD

**Issue by Hentioe** [net-ssh/net-ssh#426]
example :

``` ruby
private
# check the connection
def fault?
  @connection.nil? || @connection.closed?
end

public
def connection
  @connection = Net::SSH.start(@host, @username, :password => @password) if fault?
  @connection
end

def get_log_text(p_name, line_size)
  line_size = 100 if line_size.nil?
  connection.exec! "tail -n #{line_size} /data/app_logs/#{p_name}/catalina.out"
end
```

If one second three times invoke the get_log_text method,  after a whilewill, produce a large CLOSE_WAIT status connections.

node: @connection instanced only once

As a result, get_log_text method blocked. :(

**Comment by mfazekas** [comment]
Can you include a standalone program to demonstrate the issue? Also which version of net-ssh?

**Comment by mfazekas** [comment]
i'll reopen if we have more details
