### ISSUE TITLE
Support for unix socket forwarding?

### ISSUE THREAD

**Issue by cultureulterior** [net-ssh/net-ssh#428]
I took a look at this library, and I can't see if it supports the new ssh unix socket forwarding functionality that I believe was merged recently?

**Comment by mfazekas** [comment]
Do you mean PR #23?
forward.local should support UNIXServer as argument to specify a domain socket. As i see docs was not updated with the PR.

**Comment by cultureulterior** [comment]
That's great, but does that work for remote unix sockets?
like:
`ssh -R/var/run/mysql.sock:/var/run/mysql.sock` which openssl 6.7+ supports
