### ISSUE TITLE
Cisco Devices Close Connection

### ISSUE THREAD

**Issue by CliffordBernard** [net-ssh/net-ssh#429]
I get the following error when trying a Cisco router:

```
/Library/Ruby/Gems/2.0.0/gems/net-ssh-4.0.0.beta3/lib/net/ssh/transport/packet_stream.rb:91:in `next_packet': connection closed by remote host (Net::SSH::Disconnect)
        from /Library/Ruby/Gems/2.0.0/gems/net-ssh-4.0.0.beta3/lib/net/ssh/transport/session.rb:193:in `block in poll_message'
        from /Library/Ruby/Gems/2.0.0/gems/net-ssh-4.0.0.beta3/lib/net/ssh/transport/session.rb:188:in `loop'
        from /Library/Ruby/Gems/2.0.0/gems/net-ssh-4.0.0.beta3/lib/net/ssh/transport/session.rb:188:in `poll_message'
        from /Library/Ruby/Gems/2.0.0/gems/net-ssh-4.0.0.beta3/lib/net/ssh/connection/session.rb:513:in `dispatch_incoming_packets'
        from /Library/Ruby/Gems/2.0.0/gems/net-ssh-4.0.0.beta3/lib/net/ssh/connection/session.rb:237:in `ev_preprocess'
        from /Library/Ruby/Gems/2.0.0/gems/net-ssh-4.0.0.beta3/lib/net/ssh/connection/event_loop.rb:95:in `each'
        from /Library/Ruby/Gems/2.0.0/gems/net-ssh-4.0.0.beta3/lib/net/ssh/connection/event_loop.rb:95:in `ev_preprocess'
        from /Library/Ruby/Gems/2.0.0/gems/net-ssh-4.0.0.beta3/lib/net/ssh/connection/event_loop.rb:27:in `process'
        from /Library/Ruby/Gems/2.0.0/gems/net-ssh-4.0.0.beta3/lib/net/ssh/connection/session.rb:216:in `process'
        from /Library/Ruby/Gems/2.0.0/gems/net-ssh-4.0.0.beta3/lib/net/ssh/connection/session.rb:178:in `block in loop'
        from /Library/Ruby/Gems/2.0.0/gems/net-ssh-4.0.0.beta3/lib/net/ssh/connection/session.rb:178:in `loop'
        from /Library/Ruby/Gems/2.0.0/gems/net-ssh-4.0.0.beta3/lib/net/ssh/connection/session.rb:178:in `loop'
        from /Library/Ruby/Gems/2.0.0/gems/net-ssh-4.0.0.beta3/lib/net/ssh/connection/channel.rb:269:in `wait'
        from /Library/Ruby/Gems/2.0.0/gems/net-ssh-4.0.0.beta3/lib/net/ssh/connection/session.rb:394:in `exec!'
        from /Users/cliffordbernard/Desktop/RubyScript/device_app_ssh/lib/connection_service.rb:14:in `run'
        from main_application.rb:5:in `<class:MainApplication>'
        from main_application.rb:1:in `<main>'
```

My configuration:

> class ConnectionService
>   require 'net/ssh'
> 
>   attr_accessor :username, :password, :host
> 
>   def initialize(username, password, host)
>     @username = username
>     @password = password
>     @host = host
>   end
> 
>   def run
>     session = Net::SSH.start(@host, @username, :password => @password)
>     output = session.exec! 'show run'
>     puts output.inspect
>   end
> end

**Comment by CliffordBernard** [comment]
Verbose output:

> D, [2016-08-22T11:50:19.418925 #38433] DEBUG -- net.ssh.transport.session[3fc575816508]: establishing connection to <ip address>
> D, [2016-08-22T11:50:19.420674 #38433] DEBUG -- net.ssh.transport.session[3fc575816508]: connection established
> I, [2016-08-22T11:50:19.420830 #38433]  INFO -- net.ssh.transport.server_version[3fc575813920]: negotiating protocol version
> D, [2016-08-22T11:50:19.420902 #38433] DEBUG -- net.ssh.transport.server_version[3fc575813920]: local is `SSH-2.0-Ruby/Net::SSH_4.0.0.beta3 universal.x86_64-darwin15'
> D, [2016-08-22T11:50:19.421369 #38433] DEBUG -- net.ssh.transport.server_version[3fc575813920]: remote is `SSH-2.0-Cisco-1.25'
> I, [2016-08-22T11:50:19.422126 #38433]  INFO -- net.ssh.transport.algorithms[3fc575812750]: sending KEXINIT
> D, [2016-08-22T11:50:19.422388 #38433] DEBUG -- socket[3fc575816058]: queueing packet nr 0 type 20 len 1156
> D, [2016-08-22T11:50:19.422540 #38433] DEBUG -- socket[3fc575816058]: sent 1160 bytes
> D, [2016-08-22T11:50:19.422701 #38433] DEBUG -- socket[3fc575816058]: read 304 bytes
> D, [2016-08-22T11:50:19.422804 #38433] DEBUG -- socket[3fc575816058]: received packet nr 0 type 20 len 300
> I, [2016-08-22T11:50:19.422863 #38433]  INFO -- net.ssh.transport.algorithms[3fc575812750]: got KEXINIT from server
> I, [2016-08-22T11:50:19.426049 #38433]  INFO -- net.ssh.transport.algorithms[3fc575812750]: negotiating algorithms
> D, [2016-08-22T11:50:19.426214 #38433] DEBUG -- net.ssh.transport.algorithms[3fc575812750]: negotiated:
> * kex: diffie-hellman-group-exchange-sha1
> * host_key: ssh-rsa
> * encryption_server: aes128-cbc
> * encryption_client: aes128-cbc
> * hmac_client: hmac-sha1
> * hmac_server: hmac-sha1
> * compression_client: none
> * compression_server: none
> * language_client:
> * language_server:
> D, [2016-08-22T11:50:19.426282 #38433] DEBUG -- net.ssh.transport.algorithms[3fc575812750]: exchanging keys
> D, [2016-08-22T11:50:19.426505 #38433] DEBUG -- socket[3fc575816058]: queueing packet nr 1 type 34 len 20
> D, [2016-08-22T11:50:19.426601 #38433] DEBUG -- socket[3fc575816058]: sent 24 bytes
> D, [2016-08-22T11:50:19.620887 #38433] DEBUG -- socket[3fc575816058]: read 152 bytes
> D, [2016-08-22T11:50:19.621067 #38433] DEBUG -- socket[3fc575816058]: received packet nr 1 type 31 len 148
> D, [2016-08-22T11:50:19.623936 #38433] DEBUG -- socket[3fc575816058]: queueing packet nr 2 type 32 len 140
> D, [2016-08-22T11:50:19.624048 #38433] DEBUG -- socket[3fc575816058]: sent 144 bytes
> D, [2016-08-22T11:50:19.654257 #38433] DEBUG -- socket[3fc575816058]: read 464 bytes
> D, [2016-08-22T11:50:19.654370 #38433] DEBUG -- socket[3fc575816058]: received packet nr 2 type 33 len 444
> D, [2016-08-22T11:50:19.656706 #38433] DEBUG -- socket[3fc575816058]: queueing packet nr 3 type 21 len 20
> D, [2016-08-22T11:50:19.656809 #38433] DEBUG -- socket[3fc575816058]: sent 24 bytes
> D, [2016-08-22T11:50:19.656921 #38433] DEBUG -- socket[3fc575816058]: received packet nr 3 type 21 len 12
> D, [2016-08-22T11:50:19.657278 #38433] DEBUG -- net.ssh.authentication.session[3fc575909460]: beginning authentication of <username>
> D, [2016-08-22T11:50:19.657378 #38433] DEBUG -- socket[3fc575816058]: queueing packet nr 4 type 5 len 28
> D, [2016-08-22T11:50:19.657462 #38433] DEBUG -- socket[3fc575816058]: sent 52 bytes
> D, [2016-08-22T11:50:19.856935 #38433] DEBUG -- socket[3fc575816058]: read 52 bytes
> D, [2016-08-22T11:50:19.857168 #38433] DEBUG -- socket[3fc575816058]: received packet nr 4 type 6 len 28
> D, [2016-08-22T11:50:19.857343 #38433] DEBUG -- net.ssh.authentication.session[3fc575909460]: trying none
> D, [2016-08-22T11:50:19.857498 #38433] DEBUG -- socket[3fc575816058]: queueing packet nr 5 type 50 len 60
> D, [2016-08-22T11:50:19.857603 #38433] DEBUG -- socket[3fc575816058]: sent 84 bytes
> D, [2016-08-22T11:50:19.857697 #38433] DEBUG -- socket[3fc575816058]: read 2196 bytes
> D, [2016-08-22T11:50:19.857853 #38433] DEBUG -- socket[3fc575816058]: received packet nr 5 type 53 len 2172
> I, [2016-08-22T11:50:19.857969 #38433]  INFO -- net.ssh.authentication.session[3fc575909460]:
> <ommited banner>
> D, [2016-08-22T11:50:19.858103 #38433] DEBUG -- socket[3fc575816058]: read 84 bytes
> D, [2016-08-22T11:50:19.858218 #38433] DEBUG -- socket[3fc575816058]: received packet nr 6 type 51 len 60
> D, [2016-08-22T11:50:19.858340 #38433] DEBUG -- net.ssh.authentication.session[3fc575909460]: allowed methods: publickey,keyboard-interactive,password
> D, [2016-08-22T11:50:19.858407 #38433] DEBUG -- net.ssh.authentication.methods.none[3fc575905068]: none failed
> D, [2016-08-22T11:50:19.858496 #38433] DEBUG -- net.ssh.authentication.session[3fc575909460]: trying publickey
> D, [2016-08-22T11:50:19.858653 #38433] DEBUG -- net.ssh.authentication.agent[3fc5758fd2a0]: connecting to ssh-agent
> E, [2016-08-22T11:50:19.858725 #38433] ERROR -- net.ssh.authentication.agent[3fc5758fd2a0]: could not connect to ssh-agent
> D, [2016-08-22T11:50:19.858785 #38433] DEBUG -- net.ssh.authentication.session[3fc575909460]: trying password
> D, [2016-08-22T11:50:19.858957 #38433] DEBUG -- socket[3fc575816058]: queueing packet nr 6 type 50 len 76
> D, [2016-08-22T11:50:19.859066 #38433] DEBUG -- socket[3fc575816058]: sent 100 bytes
> D, [2016-08-22T11:50:19.862714 #38433] DEBUG -- socket[3fc575816058]: read 36 bytes
> D, [2016-08-22T11:50:19.862817 #38433] DEBUG -- socket[3fc575816058]: received packet nr 7 type 52 len 12
> D, [2016-08-22T11:50:19.862925 #38433] DEBUG -- net.ssh.authentication.methods.password[3fc5758fc7ec]: password succeeded
> D, [2016-08-22T11:50:19.863148 #38433] DEBUG -- socket[3fc575816058]: queueing packet nr 7 type 90 len 44
> D, [2016-08-22T11:50:19.863324 #38433] DEBUG -- socket[3fc575816058]: sent 68 bytes
> D, [2016-08-22T11:50:19.863679 #38433] DEBUG -- socket[3fc575816058]: read 52 bytes
> D, [2016-08-22T11:50:19.863796 #38433] DEBUG -- socket[3fc575816058]: received packet nr 8 type 91 len 28
> I, [2016-08-22T11:50:19.863901 #38433]  INFO -- net.ssh.connection.session[3fc5758f85e8]: channel_open_confirmation: 0 3 8192 4096
> I, [2016-08-22T11:50:19.864060 #38433]  INFO -- net.ssh.connection.channel[3fc5758f83a4]: sending channel request "env"
> D, [2016-08-22T11:50:19.864184 #38433] DEBUG -- socket[3fc575816058]: queueing packet nr 8 type 98 len 44
> I, [2016-08-22T11:50:19.864300 #38433]  INFO -- net.ssh.connection.channel[3fc5758f83a4]: sending channel request "exec"
> D, [2016-08-22T11:50:19.864426 #38433] DEBUG -- socket[3fc575816058]: queueing packet nr 9 type 98 len 44
> D, [2016-08-22T11:50:19.864564 #38433] DEBUG -- socket[3fc575816058]: sent 136 bytes
> D, [2016-08-22T11:50:19.864965 #38433] DEBUG -- socket[3fc575816058]: read 36 bytes
> D, [2016-08-22T11:50:19.865058 #38433] DEBUG -- socket[3fc575816058]: received packet nr 9 type 99 len 12
> I, [2016-08-22T11:50:19.865120 #38433]  INFO -- net.ssh.connection.session[3fc5758f85e8]: channel_success: 0
> D, [2016-08-22T11:50:19.865687 #38433] DEBUG -- socket[3fc575816058]: read 68 bytes
> D, [2016-08-22T11:50:19.865786 #38433] DEBUG -- socket[3fc575816058]: received packet nr 10 type 94 len 44
> I, [2016-08-22T11:50:19.865848 #38433]  INFO -- net.ssh.connection.session[3fc5758f85e8]: channel_data: 0 29b
> D, [2016-08-22T11:50:19.928316 #38433] DEBUG -- socket[3fc575816058]: read 3920 bytes
> D, [2016-08-22T11:50:19.930602 #38433] DEBUG -- socket[3fc575816058]: read 4324 bytes
> D, [2016-08-22T11:50:19.930874 #38433] DEBUG -- socket[3fc575816058]: received packet nr 11 type 94 len 8220
> I, [2016-08-22T11:50:19.930947 #38433]  INFO -- net.ssh.connection.session[3fc5758f85e8]: channel_data: 0 8192b
> D, [2016-08-22T11:50:19.932773 #38433] DEBUG -- socket[3fc575816058]: read 2240 bytes
> D, [2016-08-22T11:50:19.933305 #38433] DEBUG -- socket[3fc575816058]: read 3360 bytes
> D, [2016-08-22T11:50:19.933408 #38433] DEBUG -- socket[3fc575816058]: read 1120 bytes
> D, [2016-08-22T11:50:19.933599 #38433] DEBUG -- socket[3fc575816058]: read 388 bytes
> D, [2016-08-22T11:50:19.933815 #38433] DEBUG -- socket[3fc575816058]: received packet nr 12 type 94 len 7084
> I, [2016-08-22T11:50:19.933881 #38433]  INFO -- net.ssh.connection.session[3fc5758f85e8]: channel_data: 0 7058b
> D, [2016-08-22T11:50:20.033095 #38433] DEBUG -- socket[3fc575816058]: read 140 bytes
> D, [2016-08-22T11:50:20.033260 #38433] DEBUG -- socket[3fc575816058]: read 0 bytes
> D, [2016-08-22T11:50:20.033407 #38433] DEBUG -- socket[3fc575816058]: received packet nr 13 type 98 len 44
> I, [2016-08-22T11:50:20.033513 #38433]  INFO -- net.ssh.connection.session[3fc5758f85e8]: channel_request: 0 exit-status false
> D, [2016-08-22T11:50:20.033647 #38433] DEBUG -- socket[3fc575816058]: read 0 bytes
> D, [2016-08-22T11:50:20.033731 #38433] DEBUG -- socket[3fc575816058]: received packet nr 14 type 96 len 12
> I, [2016-08-22T11:50:20.033793 #38433]  INFO -- net.ssh.connection.session[3fc5758f85e8]: channel_eof: 0
> D, [2016-08-22T11:50:20.033896 #38433] DEBUG -- socket[3fc575816058]: read 0 bytes
> D, [2016-08-22T11:50:20.034002 #38433] DEBUG -- socket[3fc575816058]: received packet nr 15 type 97 len 12
> I, [2016-08-22T11:50:20.034062 #38433]  INFO -- net.ssh.connection.session[3fc5758f85e8]: channel_close: 0
> D, [2016-08-22T11:50:20.034170 #38433] DEBUG -- socket[3fc575816058]: read 0 bytes
> /Library/Ruby/Gems/2.0.0/gems/net-ssh-4.0.0.beta3/lib/net/ssh/transport/packet_stream.rb:91:in `next_packet': connection closed by remote host (Net::SSH::Disconnect)
>         from /Library/Ruby/Gems/2.0.0/gems/net-ssh-4.0.0.beta3/lib/net/ssh/transport/session.rb:193:in `block in poll_message'
>         from /Library/Ruby/Gems/2.0.0/gems/net-ssh-4.0.0.beta3/lib/net/ssh/transport/session.rb:188:in `loop'
>         from /Library/Ruby/Gems/2.0.0/gems/net-ssh-4.0.0.beta3/lib/net/ssh/transport/session.rb:188:in `poll_message'
>         from /Library/Ruby/Gems/2.0.0/gems/net-ssh-4.0.0.beta3/lib/net/ssh/connection/session.rb:513:in `dispatch_incoming_packets'
>         from /Library/Ruby/Gems/2.0.0/gems/net-ssh-4.0.0.beta3/lib/net/ssh/connection/session.rb:237:in `ev_preprocess'
>         from /Library/Ruby/Gems/2.0.0/gems/net-ssh-4.0.0.beta3/lib/net/ssh/connection/event_loop.rb:95:in `each'
>         from /Library/Ruby/Gems/2.0.0/gems/net-ssh-4.0.0.beta3/lib/net/ssh/connection/event_loop.rb:95:in `ev_preprocess'
>         from /Library/Ruby/Gems/2.0.0/gems/net-ssh-4.0.0.beta3/lib/net/ssh/connection/event_loop.rb:27:in `process'
>         from /Library/Ruby/Gems/2.0.0/gems/net-ssh-4.0.0.beta3/lib/net/ssh/connection/session.rb:216:in `process'
>         from /Library/Ruby/Gems/2.0.0/gems/net-ssh-4.0.0.beta3/lib/net/ssh/connection/session.rb:178:in `block in loop'
>         from /Library/Ruby/Gems/2.0.0/gems/net-ssh-4.0.0.beta3/lib/net/ssh/connection/session.rb:178:in `loop'
>         from /Library/Ruby/Gems/2.0.0/gems/net-ssh-4.0.0.beta3/lib/net/ssh/connection/session.rb:178:in `loop'
>         from /Library/Ruby/Gems/2.0.0/gems/net-ssh-4.0.0.beta3/lib/net/ssh/connection/channel.rb:269:in `wait'
>         from /Library/Ruby/Gems/2.0.0/gems/net-ssh-4.0.0.beta3/lib/net/ssh/connection/session.rb:394:in `exec!'
>         from /Users/cliffordbernard/Desktop/RubyScript/device_app_ssh/lib/connection_service.rb:14:in `run'
>         from main_application.rb:5:in `<class:MainApplication>'
>         from main_application.rb:1:in `<main>'

**Comment by mfazekas** [comment]
Can you get logs on cisco server on why this channel close happens? Is this soemthing i can reproduce?

**Comment by CliffordBernard** [comment]
> Aug 29 20:25:30.145: SSH1: starting SSH control process
Aug 29 20:25:30.145: SSH1: sent protocol version id SSH-2.0-Cisco-1.25
Aug 29 20:25:30.149: SSH1: protocol version id is - SSH-2.0-Ruby/Net::SSH_4.0.0.beta3 universal.x86_64-darwin15
Aug 29 20:25:30.153: SSH2 1: send:packet of  length 304 (length also includes padlen of 7)
Aug 29 20:25:30.153: SSH2 1: SSH2_MSG_KEXINIT sent
Aug 29 20:25:30.153: SSH2 1: ssh_receive: 1160 bytes received
Aug 29 20:25:30.153: SSH2 1: input: total packet length of 1160 bytes
Aug 29 20:25:30.153: SSH2 1: partial packet length(block size)8 bytes,needed 1152 bytes,
               maclen 0
Aug 29 20:25:30.153: SSH2 1: input: padlength 11 bytes
Aug 29 20:25:30.153: SSH2 1: SSH2_MSG_KEXINIT received
Aug 29 20:25:30.153: SSH2 1: kex: client->server enc:aes128-cbc mac:hmac-sha1
Aug 29 20:25:30.153: SSH2 1: kex: server->client enc:aes128-cbc mac:hmac-sha1
Aug 29 20:25:30.153: SSH2 1: Using kex_algo = diffie-hellman-group-exchange-sha1
Aug 29 20:25:30.153: SSH2 1: ssh_receive: 24 bytes received
Aug 29 20:25:30.153: SSH2 1: input: total packet length of 24 bytes
Aug 29 20:25:30.153: SSH2 1: partial packet length(block size)8 bytes,needed 16 bytes,
               maclen 0
Aug 29 20:25:30.153: SSH2 1: input: padlength 6 bytes
Aug 29 20:25:30.153: SSH2 1: SSH2_MSG_KEX_DH_GEX_REQUEST received
Aug 29 20:25:30.153: SSH2 1: Range sent by client is - 1024 < 1024 < 8192
Aug 29 20:25:30.153: SSH2 1:  Modulus size established : 1024 bits
Aug 29 20:25:30.153: SSH2 1: send:packet of  length 152 (length also includes padlen of 8)
Aug 29 20:25:30.161: SSH2 1: expecting SSH2_MSG_KEX_DH_GEX_INIT
Aug 29 20:25:30.165: SSH2 1: ssh_receive: 144 bytes received
Aug 29 20:25:30.165: SSH2 1: input: total packet length of 144 bytes
Aug 29 20:25:30.165: SSH2 1: partial packet length(block size)8 bytes,needed 136 bytes,
               maclen 0
Aug 29 20:25:30.165: SSH2 1: input: padlength 5 bytes
Aug 29 20:25:30.165: SSH2 1: SSH2_MSG_KEXDH_INIT received
Aug 29 20:25:30.185: SSH2 1: signature length 143
Aug 29 20:25:30.185: SSH2 1: send:packet of  length 448 (length also includes padlen of 7)
Aug 29 20:25:30.189: SSH2: kex_derive_keys complete
Aug 29 20:25:30.189: SSH2 1: send:packet of  length 16 (length also includes padlen of 10)
Aug 29 20:25:30.189: SSH2 1: newkeys: mode 1
Aug 29 20:25:30.189: SSH2 1: SSH2_MSG_NEWKEYS sent
Aug 29 20:25:30.189: SSH2 1: waiting for SSH2_MSG_NEWKEYS
Aug 29 20:25:30.189: SSH2 1: ssh_receive: 24 bytes received
Aug 29 20:25:30.189: SSH2 1: input: total packet length of 24 bytes
Aug 29 20:25:30.189: SSH2 1: partial packet length(block size)8 bytes,needed 16 bytes,
               maclen 0
Aug 29 20:25:30.189: SSH2 1: input: padlength 18 bytes
Aug 29 20:25:30.189: SSH2 1: newkeys: mode 0
Aug 29 20:25:30.189: SSH2 1: SSH2_MSG_NEWKEYS received
Aug 29 20:25:30.389: SSH2 1: ssh_receive: 52 bytes received
Aug 29 20:25:30.389: SSH2 1: input: total packet length of 32 bytes
Aug 29 20:25:30.389: SSH2 1: partial packet length(block size)16 bytes,needed 16 bytes,
               maclen 20
Aug 29 20:25:30.389: SSH2 1: MAC compared for #4 :ok
Aug 29 20:25:30.389: SSH2 1: input: padlength 10 bytes
Aug 29 20:25:30.389: SSH2 1: send:packet of  length 32 (length also includes padlen of 10)
Aug 29 20:25:30.389: SSH2 1: computed MAC for sequence no.#4 type 6
Aug 29 20:25:30.389: SSH2 1: send:packet of  length 2176 (length also includes padlen of 8)
Aug 29 20:25:30.389: SSH2 1: computed MAC for sequence no.#5 type 53
Aug 29 20:25:30.389: SSH2 1: ssh_receive: 84 bytes received
Aug 29 20:25:30.389: SSH2 1: input: total packet length of 64 bytes
Aug 29 20:25:30.389: SSH2 1: partial packet length(block size)16 bytes,needed 48 bytes,
               maclen 20
Aug 29 20:25:30.389: SSH2 1: MAC compared for #5 :ok
Aug 29 20:25:30.389: SSH2 1: input: padlength 16 bytes
Aug 29 20:25:30.389: SSH2 1: Using method = none
Aug 29 20:25:30.389: SSH2 1: Authentications that can continue = publickey,keyboard-interactive,password
Aug 29 20:25:30.389: SSH2 1: send:packet of  length 64 (length also includes padlen of 14)
Aug 29 20:25:30.389: SSH2 1: computed MAC for sequence no.#6 type 51
Aug 29 20:25:30.393: SSH2 1: ssh_receive: 100 bytes received
Aug 29 20:25:30.393: SSH2 1: input: total packet length of 80 bytes
Aug 29 20:25:30.393: SSH2 1: partial packet length(block size)16 bytes,needed 64 bytes,
               maclen 20
Aug 29 20:25:30.393: SSH2 1: MAC compared for #6 :ok
Aug 29 20:25:30.393: SSH2 1: input: padlength 12 bytes
Aug 29 20:25:30.393: SSH2 1: Using method = password
Aug 29 20:25:30.397: SSH2 1: send:packet of  length 16 (length also includes padlen of 10)
Aug 29 20:25:30.397: SSH2 1: computed MAC for sequence no.#7 type 52
Aug 29 20:25:30.397: SSH2 1: authentication successful for networkadmin
Aug 29 20:25:30.397: SSH2 1: ssh_receive: 68 bytes received
Aug 29 20:25:30.397: SSH2 1: input: total packet length of 48 bytes
Aug 29 20:25:30.397: SSH2 1: partial packet length(block size)16 bytes,needed 32 bytes,
               maclen 20
Aug 29 20:25:30.397: SSH2 1: MAC compared for #7 :ok
Aug 29 20:25:30.397: SSH2 1: input: padlength 19 bytes
Aug 29 20:25:30.397: SSH2 1: channel open request
Aug 29 20:25:30.397: SSH2 1: send:packet of  length 32 (length also includes padlen of 10)
Aug 29 20:25:30.397: SSH2 1: computed MAC for sequence no.#8 type 91
Aug 29 20:25:30.397: SSH2 1: ssh_receive: 136 bytes received
Aug 29 20:25:30.397: SSH2 1: input: total packet length of 48 bytes
Aug 29 20:25:30.397: SSH2 1: partial packet length(block size)16 bytes,needed 32 bytes,
               maclen 20
Aug 29 20:25:30.397: SSH2 1: MAC compared for #8 :ok
Aug 29 20:25:30.397: SSH2 1: input: padlength 7 bytes
Aug 29 20:25:30.397: SSH2 1: env request
Aug 29 20:25:30.397: SSH2 1: input: total packet length of 48 bytes
Aug 29 20:25:30.397: SSH2 1: partial packet length(block size)16 bytes,needed 32 bytes,
               maclen 20
Aug 29 20:25:30.397: SSH2 1: MAC compared for #9 :ok
Aug 29 20:25:30.397: SSH2 1: input: padlength 17 bytes
Aug 29 20:25:30.397: SSH2 1: send:packet of  length 16 (length also includes padlen of 6)
Aug 29 20:25:30.401: SSH2 1: computed MAC for sequence no.#9 type 99
Aug 29 20:25:30.401: SSH2 1: exec request
Aug 29 20:25:30.401: SSH2 1: exec message received
Aug 29 20:25:30.401: SSH2 1: starting shell for vty
Aug 29 20:25:30.401: SSH2 1: send:packet of  length 48 (length also includes padlen of 7)
Aug 29 20:25:30.401: SSH2 1: computed MAC for sequence no.#10 type 94
Aug 29 20:25:30.465: SSH2 1: send:packet of  length 8224 (length also includes padlen of 18)
Aug 29 20:25:30.465: SSH2 1: computed MAC for sequence no.#11 type 94
Aug 29 20:25:30.469: SSH2 1: send:packet of  length 7040 (length also includes padlen of 19)
Aug 29 20:25:30.469: SSH2 1: computed MAC for sequence no.#12 type 94
Aug 29 20:25:30.569: SSH2 1: send:packet of  length 48 (length also includes padlen of 18)
Aug 29 20:25:30.569: SSH2 1: computed MAC for sequence no.#13 type 98
Aug 29 20:25:30.569: SSH2 1: send:packet of  length 16 (length also includes padlen of 6)
Aug 29 20:25:30.569: SSH2 1: computed MAC for sequence no.#14 type 96
Aug 29 20:25:30.569: SSH2 1: send:packet of  length 16 (length also includes padlen of 6)
Aug 29 20:25:30.569: SSH2 1: computed MAC for sequence no.#15 type 97
Aug 29 20:25:30.569: SSH1: Session terminated normally

**Comment by ytti** [comment]
Lot of other networking vendors either don't support exec channel at all, or if they do, like Cisco IOS, IOS-XR, they close the whole TCP session when the channel closes.

Try in older net/ssh, and it'll work, like 3.0.x. 

SSH shouldn't behave like this, just because channel closes, does not mean you can just close the TCP, but it is what it is, shitty SSH implementations are fact of life.
This error shouldn't raise or stop exec! from returning the data it read. It should simply mean that next exec! will fail, because connection is closed.

**Comment by mfazekas** [comment]
@ytti do you know other implementations that do? What would be the easies way for me to reproduce?

**Comment by ytti** [comment]
Testing against IOS or IOS-XR device should be simplest. Perhaps @CliffordBernard and produce sanitised device to test against.

**Comment by mfazekas** [comment]
Would this vagrant image help me? 
https://xrdocs.github.io/application-hosting/tutorials/iosxr-vagrant-quickstart

**Comment by ytti** [comment]
Yeah XRv will work, but XRv isn't free, you'd have to acquire the image from somewhere.

**Comment by ytti** [comment]
Looks reasonable, please do also confirm that this method does not show the problem on ```3.0.x``` if so, then I think you have good repro.

**Comment by mfazekas** [comment]
https://rubygems.org/gems/net-ssh/versions/4.0.0.beta4 was released it should fix the issue. Can you test?

**Comment by CliffordBernard** [comment]
This seems to be fixed now.  Thank you so much.
