### ISSUE TITLE
Could you please add support for the ProxyJump configuration?

### ISSUE THREAD

**Issue by rosenfeld** [net-ssh/net-ssh#430]
ProxyJump makes it much simpler to set up a jump host. Here are some references:

http://www.openssh.com/txt/release-7.3

```
New Features
------------

 * ssh(1): Add a ProxyJump option and corresponding -J command-line
   flag to allow simplified indirection through a one or more SSH
   bastions or "jump hosts".
```

https://en.wikibooks.org/wiki/OpenSSH/Cookbook/Proxies_and_Jump_Hosts#Passing_Through_One_or_More_Gateways_Using_ProxyJump

https://wiki.gentoo.org/wiki/SSH_jump_host

```
#~/.ssh/configProxyJump Example

### First jumphost. Directly reachable
Host betajump
  HostName jumphost1.example.org

### Host to jump to via jumphost1.example.org
Host behindbeta
  HostName behindbeta.example.org
  ProxyJump  betajump
```

**Comment by rmm5t** [comment]
I just ran into this limitation myself. I would also love to see `ProxyJump` support.  Is this something the maintainers would like to see a PR for?

**Comment by mfazekas** [comment]
sure, please send PR-s!

**Comment by rmm5t** [comment]
> sure, please send PR-s!

Cool. Will do as soon as I get a batch of time to investigate. I just looked at OpenSSH source, and it looks like `ProxyJump` just gets converted to a semi-recursive `ProxyCommand` under the hood.

**Comment by rmm5t** [comment]
Please review PR #497 for newly added `ProxyJump` support.

**Comment by rmm5t** [comment]
Safe to close this now, because #500?
