### ISSUE TITLE
Support more secure MAC algorithms

### ISSUE THREAD

**Issue by graaff** [net-ssh/net-ssh#441]
Trying to secure our servers follow the feedback from https://github.com/arthepsy/ssh-audit I noticed that all current MAC algorithms in net-ssh are considered either insecure or suspect by ssh-audit. It would be great if additional MAC algorithms could be supported, specifically:

hmac-sha2-512-etm@openssh.com 
hmac-sha2-256-etm@openssh.com
umac-128-etm@openssh.com

All of these have been available in openssh since 6.2 so they should already be used widely.

**Comment by fwininger** [comment]
#705
