### ISSUE TITLE
Sometime, net-ssh blocked when exit and ate CPU 100%...

### ISSUE THREAD

**Issue by jinchizhong** [net-ssh/net-ssh#445]
Hi friend,

I met a problem when net/ssh exit.
I don't why, (may be due to package lost or something else).
And then, net-ssh blocked, ate CPU 100%, and cannot exit.
Thank you very much.

Here's some code piece:

    opts = {
      key_data: ...,
      keys_only: ...,
      auth_methods: ['publickey'],
      verbose: :debug
    }
    Net::SSH.start(addr, "root", opts) do |session|
      session.open_chanel do |channel|
        channel.exec "echo hello"
        channel.on_data do |ch, data|
          puts data
        end
        channel.eof!
      end
    end

Here's logs:

    D, [2016-11-11T17:23:04.278164 #27987] DEBUG -- net.ssh.transport.session[1383564]: establishing connection to 45.63.94.145:22
    D, [2016-11-11T17:23:04.570743 #27987] DEBUG -- net.ssh.transport.session[1383564]: connection established
    I, [2016-11-11T17:23:04.572063 #27987]  INFO -- net.ssh.transport.server_version[1381f70]: negotiating protocol version
    D, [2016-11-11T17:23:04.573118 #27987] DEBUG -- net.ssh.transport.server_version[1381f70]: local is `SSH-2.0-Ruby/Net::SSH_3.2.0 x86_64-linux'
    D, [2016-11-11T17:23:04.813442 #27987] DEBUG -- net.ssh.transport.server_version[1381f70]: remote is `SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8'
    I, [2016-11-11T17:23:04.816353 #27987]  INFO -- net.ssh.transport.algorithms[1380134]: sending KEXINIT
    D, [2016-11-11T17:23:04.817732 #27987] DEBUG -- socket[1382e84]: queueing packet nr 0 type 20 len 1684
    D, [2016-11-11T17:23:04.818626 #27987] DEBUG -- socket[1382e84]: sent 1688 bytes
    D, [2016-11-11T17:23:04.819258 #27987] DEBUG -- socket[1382e84]: read 1448 bytes
    D, [2016-11-11T17:23:05.043997 #27987] DEBUG -- socket[1382e84]: read 200 bytes
    D, [2016-11-11T17:23:05.044907 #27987] DEBUG -- socket[1382e84]: received packet nr 0 type 20 len 1644
    I, [2016-11-11T17:23:05.045767 #27987]  INFO -- net.ssh.transport.algorithms[1380134]: got KEXINIT from server
    I, [2016-11-11T17:23:05.046858 #27987]  INFO -- net.ssh.transport.algorithms[1380134]: negotiating algorithms
    D, [2016-11-11T17:23:05.047851 #27987] DEBUG -- net.ssh.transport.algorithms[1380134]: negotiated:
    * kex: diffie-hellman-group-exchange-sha1
    * host_key: ssh-rsa
    * encryption_server: aes128-cbc
    * encryption_client: aes128-cbc
    * hmac_client: hmac-sha1
    * hmac_server: hmac-sha1
    * compression_client: none
    * compression_server: none
    * language_client:
    * language_server:
    D, [2016-11-11T17:23:05.050870 #27987] DEBUG -- net.ssh.transport.algorithms[1380134]: exchanging keys
    D, [2016-11-11T17:23:05.051357 #27987] DEBUG -- socket[1382e84]: queueing packet nr 1 type 34 len 20
    D, [2016-11-11T17:23:05.052046 #27987] DEBUG -- socket[1382e84]: sent 24 bytes
    D, [2016-11-11T17:23:05.885071 #27987] DEBUG -- socket[1382e84]: read 152 bytes
    D, [2016-11-11T17:23:05.885318 #27987] DEBUG -- socket[1382e84]: received packet nr 1 type 31 len 148
    D, [2016-11-11T17:23:05.889099 #27987] DEBUG -- socket[1382e84]: queueing packet nr 2 type 32 len 140
    D, [2016-11-11T17:23:05.890138 #27987] DEBUG -- socket[1382e84]: sent 144 bytes
    D, [2016-11-11T17:23:06.145603 #27987] DEBUG -- socket[1382e84]: read 720 bytes
    D, [2016-11-11T17:23:06.146541 #27987] DEBUG -- socket[1382e84]: received packet nr 2 type 33 len 700
    D, [2016-11-11T17:23:06.149075 #27987] DEBUG -- socket[1382e84]: queueing packet nr 3 type 21 len 20
    D, [2016-11-11T17:23:06.149864 #27987] DEBUG -- socket[1382e84]: sent 24 bytes
    D, [2016-11-11T17:23:06.150479 #27987] DEBUG -- socket[1382e84]: received packet nr 3 type 21 len 12
    D, [2016-11-11T17:23:06.151671 #27987] DEBUG -- net.ssh.authentication.session[13d4e28]: beginning authentication of `root'
    D, [2016-11-11T17:23:06.152759 #27987] DEBUG -- socket[1382e84]: queueing packet nr 4 type 5 len 28
    D, [2016-11-11T17:23:06.153622 #27987] DEBUG -- socket[1382e84]: sent 52 bytes
    D, [2016-11-11T17:23:06.706458 #27987] DEBUG -- socket[1382e84]: read 52 bytes
    D, [2016-11-11T17:23:06.707559 #27987] DEBUG -- socket[1382e84]: received packet nr 4 type 6 len 28
    D, [2016-11-11T17:23:06.708644 #27987] DEBUG -- net.ssh.authentication.session[13d4e28]: trying publickey
    D, [2016-11-11T17:23:06.709600 #27987] DEBUG -- net.ssh.authentication.agent[13cb058]: connecting to ssh-agent
    E, [2016-11-11T17:23:06.710198 #27987] ERROR -- net.ssh.authentication.agent[13cb058]: could not connect to ssh-agent
    D, [2016-11-11T17:23:06.710422 #27987] DEBUG -- net.ssh.authentication.methods.publickey[13cb364]: trying publickey (f6:52:57:cb:6e:2b:81:c9:e1:fb:37:78:55:8b:49:07)
    D, [2016-11-11T17:23:06.711226 #27987] DEBUG -- socket[1382e84]: queueing packet nr 5 type 50 len 348
    D, [2016-11-11T17:23:06.711764 #27987] DEBUG -- socket[1382e84]: sent 372 bytes
    D, [2016-11-11T17:23:08.398437 #27987] DEBUG -- socket[1382e84]: read 324 bytes
    D, [2016-11-11T17:23:08.398719 #27987] DEBUG -- socket[1382e84]: received packet nr 5 type 60 len 300
    D, [2016-11-11T17:23:08.402241 #27987] DEBUG -- socket[1382e84]: queueing packet nr 6 type 50 len 620
    D, [2016-11-11T17:23:08.402365 #27987] DEBUG -- socket[1382e84]: sent 644 bytes
    D, [2016-11-11T17:23:08.695813 #27987] DEBUG -- socket[1382e84]: read 36 bytes
    D, [2016-11-11T17:23:08.697157 #27987] DEBUG -- socket[1382e84]: received packet nr 6 type 52 len 12
    D, [2016-11-11T17:23:08.698147 #27987] DEBUG -- net.ssh.authentication.methods.publickey[13cb364]: publickey succeeded (f6:52:57:cb:6e:2b:81:c9:e1:fb:37:78:55:8b:49:07)
    D, [2016-11-11T17:23:08.700011 #27987] DEBUG -- socket[1382e84]: queueing packet nr 7 type 90 len 44
    D, [2016-11-11T17:23:08.701508 #27987] DEBUG -- socket[1382e84]: sent 68 bytes
    D, [2016-11-11T17:23:09.004741 #27987] DEBUG -- socket[1382e84]: read 52 bytes
    D, [2016-11-11T17:23:09.006186 #27987] DEBUG -- socket[1382e84]: received packet nr 7 type 91 len 28
    I, [2016-11-11T17:23:09.007194 #27987]  INFO -- net.ssh.connection.session[13b8840]: channel_open_confirmation: 0 0 0 32768
    I, [2016-11-11T17:23:09.008177 #27987]  INFO -- net.ssh.connection.channel[13b84bc]: sending channel request "env"
    D, [2016-11-11T17:23:09.009279 #27987] DEBUG -- socket[1382e84]: queueing packet nr 8 type 98 len 44
    I, [2016-11-11T17:23:09.009539 #27987]  INFO -- net.ssh.connection.channel[13b84bc]: sending channel request "exec"
    D, [2016-11-11T17:23:09.010575 #27987] DEBUG -- socket[1382e84]: queueing packet nr 9 type 98 len 44
    D, [2016-11-11T17:23:09.010781 #27987] DEBUG -- socket[1382e84]: sent 136 bytes
    D, [2016-11-11T17:23:09.315233 #27987] DEBUG -- socket[1382e84]: read 88 bytes
    D, [2016-11-11T17:23:09.315662 #27987] DEBUG -- socket[1382e84]: received packet nr 8 type 93 len 28
    I, [2016-11-11T17:23:09.315831 #27987]  INFO -- net.ssh.connection.session[13b8840]: channel_window_adjust: 0 +2097152
    D, [2016-11-11T17:23:09.316004 #27987] DEBUG -- socket[1382e84]: received packet nr 9 type 99 len 12
    I, [2016-11-11T17:23:09.317497 #27987]  INFO -- net.ssh.connection.session[13b8840]: channel_success: 0
    D, [2016-11-11T17:23:09.317802 #27987] DEBUG -- socket[1382e84]: queueing packet nr 10 type 96 len 28
    D, [2016-11-11T17:23:09.317963 #27987] DEBUG -- socket[1382e84]: sent 52 bytes
    D, [2016-11-11T17:23:09.319026 #27987] DEBUG -- socket[1382e84]: read 192 bytes
    D, [2016-11-11T17:23:09.319234 #27987] DEBUG -- socket[1382e84]: received packet nr 10 type 98 len 44
    I, [2016-11-11T17:23:09.319393 #27987]  INFO -- net.ssh.connection.session[13b8840]: channel_request: 0 exit-status false
    D, [2016-11-11T17:23:09.319606 #27987] DEBUG -- socket[1382e84]: received packet nr 11 type 94 len 28
    I, [2016-11-11T17:23:09.319733 #27987]  INFO -- net.ssh.connection.session[13b8840]: channel_data: 0 6b
    D, [2016-11-11T17:23:09.320947 #27987] DEBUG -- socket[1382e84]: received packet nr 12 type 96 len 12
    I, [2016-11-11T17:23:09.321071 #27987]  INFO -- net.ssh.connection.session[13b8840]: channel_eof: 0
    D, [2016-11-11T17:23:09.321265 #27987] DEBUG -- socket[1382e84]: received packet nr 13 type 97 len 12
    I, [2016-11-11T17:23:09.321378 #27987]  INFO -- net.ssh.connection.session[13b8840]: channel_close: 0
    D, [2016-11-11T17:23:09.322317 #27987] DEBUG -- socket[1382e84]: queueing packet nr 11 type 97 len 28
    I, [2016-11-11T17:23:09.322391 #27987]  INFO -- net.ssh.connection.session[13b8840]: 45.63.94.145 delete channel 0 which closed locally and remotely
    server ready
    I, [2016-11-11T17:23:09.322495 #27987]  INFO -- net.ssh.connection.session[13b8840]: closing remaining channels (0 open)
    D, [2016-11-11T17:23:09.327645 #27987] DEBUG -- net.ssh.transport.session[1318b74]: establishing connection to 45.63.94.145:22
    D, [2016-11-11T17:23:12.022263 #27987] DEBUG -- net.ssh.transport.session[1318b74]: connection established
    I, [2016-11-11T17:23:12.022470 #27987]  INFO -- net.ssh.transport.server_version[1313da4]: negotiating protocol version
    D, [2016-11-11T17:23:12.022512 #27987] DEBUG -- net.ssh.transport.server_version[1313da4]: local is `SSH-2.0-Ruby/Net::SSH_3.2.0 x86_64-linux'
    D, [2016-11-11T17:23:25.540978 #27987] DEBUG -- net.ssh.transport.server_version[1313da4]: remote is `SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8'
    I, [2016-11-11T17:23:25.542036 #27987]  INFO -- net.ssh.transport.algorithms[1312a80]: sending KEXINIT
    D, [2016-11-11T17:23:25.542280 #27987] DEBUG -- socket[1318354]: queueing packet nr 0 type 20 len 1684
    D, [2016-11-11T17:23:25.542382 #27987] DEBUG -- socket[1318354]: sent 1688 bytes
    Task #220 met problem

    SignalException: SIGTERM
        /home/jcz/.rvm/gems/ruby-2.2.4/gems/net-ssh-3.2.0/lib/net/ssh/ruby_compat.rb:25:in `select'
        /home/jcz/.rvm/gems/ruby-2.2.4/gems/net-ssh-3.2.0/lib/net/ssh/ruby_compat.rb:25:in `io_select'
        /home/jcz/.rvm/gems/ruby-2.2.4/gems/net-ssh-3.2.0/lib/net/ssh/transport/packet_stream.rb:75:in `available_for_read?'
        /home/jcz/.rvm/gems/ruby-2.2.4/gems/net-ssh-3.2.0/lib/net/ssh/transport/packet_stream.rb:87:in `next_packet'
        /home/jcz/.rvm/gems/ruby-2.2.4/gems/net-ssh-3.2.0/lib/net/ssh/transport/session.rb:193:in `block in poll_message'
        /home/jcz/.rvm/gems/ruby-2.2.4/gems/net-ssh-3.2.0/lib/net/ssh/transport/session.rb:188:in `loop'
        /home/jcz/.rvm/gems/ruby-2.2.4/gems/net-ssh-3.2.0/lib/net/ssh/transport/session.rb:188:in `poll_message'
        /home/jcz/.rvm/gems/ruby-2.2.4/gems/net-ssh-3.2.0/lib/net/ssh/transport/session.rb:225:in `block in wait'
        /home/jcz/.rvm/gems/ruby-2.2.4/gems/net-ssh-3.2.0/lib/net/ssh/transport/session.rb:223:in `loop'
        /home/jcz/.rvm/gems/ruby-2.2.4/gems/net-ssh-3.2.0/lib/net/ssh/transport/session.rb:223:in `wait'
        /home/jcz/.rvm/gems/ruby-2.2.4/gems/net-ssh-3.2.0/lib/net/ssh/transport/session.rb:88:in `initialize'
        /home/jcz/.rvm/gems/ruby-2.2.4/gems/net-ssh-3.2.0/lib/net/ssh.rb:232:in `new'
        /home/jcz/.rvm/gems/ruby-2.2.4/gems/net-ssh-3.2.0/lib/net/ssh.rb:232:in `start'
        /home/jcz/factorio-realm/service/libs/ssh.rb:128:in `connect'
        /home/jcz/factorio-realm/service/libs/ssh.rb:150:in `inspect'
        /home/jcz/factorio-realm/service/libs/ssh.rb:155:in `inspect!'
        /home/jcz/factorio-realm/service/tasks/start-realm.rb:131:in `setup_factorio'
        /home/jcz/factorio-realm/service/tasks/start-realm.rb:18:in `run'
        /home/jcz/factorio-realm/service/libs/task.rb:42:in `run_task'
        /home/jcz/factorio-realm/service/libs/task.rb:91:in `block in launch_task'
        /home/jcz/factorio-realm/service/libs/task.rb:84:in `fork'
        /home/jcz/factorio-realm/service/libs/task.rb:84:in `launch_task'
        server.rb:44:in `block in deal_tasks'
        /home/jcz/.rvm/gems/ruby-2.2.4/gems/mongo-2.3.0/lib/mongo/collection/view/iterable.rb:45:in `block in each'
        /home/jcz/.rvm/gems/ruby-2.2.4/gems/mongo-2.3.0/lib/mongo/cursor.rb:110:in `block in each'
        /home/jcz/.rvm/gems/ruby-2.2.4/gems/mongo-2.3.0/lib/mongo/cursor.rb:110:in `each'
        /home/jcz/.rvm/gems/ruby-2.2.4/gems/mongo-2.3.0/lib/mongo/cursor.rb:110:in `each'
        /home/jcz/.rvm/gems/ruby-2.2.4/gems/mongo-2.3.0/lib/mongo/collection/view/iterable.rb:44:in `each'
        server.rb:36:in `deal_tasks'
        server.rb:91:in `block (2 levels) in main_loop'
        server.rb:85:in `each'
        server.rb:85:in `block in main_loop'
        server.rb:79:in `loop'
        server.rb:79:in `main_loop'
        server.rb:99:in `<main>'

**Comment by jinchizhong** [comment]
Oh, sorry

the verson of my net/ssh is 3.2.0

**Comment by mfazekas** [comment]
Looks like we're waiting for algorithm.initialize for finish, and looks like it spins cpu there.
See https://github.com/net-ssh/net-ssh/blob/v3.2.0/lib/net/ssh/transport/session.rb#L88.

If i change that line from ```wait { algorithms.initialized? }``` to ```wait { algorithms.initialized? && false }``` i can repro the 100% cpu usage. 

I guess the fix for 100% cpu usage would be using blocking poll at 
https://github.com/net-ssh/net-ssh/blob/v3.2.0/lib/net/ssh/transport/session.rb#L225. 
I'm not sure what's the concrete issue that causes algorithms.initialized? to never suceed though.

Can you try with net-ssh-4.0.0.beta4?

**Comment by mfazekas** [comment]
Closing this, will reopen when hear back
