### ISSUE TITLE
missing "ssh-ed25519" in Transport::Algorithms::ALGORITHMS[:host_key]

### ISSUE THREAD

**Issue by detatka-kuzlatka-otevrete** [net-ssh/net-ssh#459]
I am using net-ssh 4.0.0.rc1, connecting to Junos OS 15.1X53. There is only the "ed25519" signature algorithm allowed on the device and only public key authentication is allowed.

Without the attached patch, net-ssh can't connect: Net::SSH::Exception "could not settle on host_key algorithm".

[transport_algorithms.diff.txt](https://github.com/net-ssh/net-ssh/files/637356/transport_algorithms.diff.txt)

**Comment by mfazekas** [comment]
Hi, thanks for the patch,

Is this something i can repro?
We should probably only enable `ssh-ed25519` if we have the required libraries installed.
So they have to be placed into
```ruby
if Net::SSH::Authentication::ED25519Loader::LOADED
```

**Comment by detatka-kuzlatka-otevrete** [comment]
Yes, I think you can create similar environment with ease:

In the Transport::Algorithms#negotiate method (where the aforementioned exception is raised) is: 
`@server_data[algorithm] == ["ssh-ed25519"]`

The ssh software of the device is (from `ssh -vvv`):
`debug1: Remote protocol version 2.0, remote software version OpenSSH_6.6.1`

**Comment by detatka-kuzlatka-otevrete** [comment]
Related problem: if KnownHosts::SUPPORTED_TYPE is missing the "ssh-ed25519" entry, each time a connection is made, new (eventually duplicated) line is added to the known_hosts file.
