### ISSUE TITLE
Version 4.0.0 doesn't work on Windows platform - can't parse the function prototype: HANDLE CreateFileMapping(HANDLE, void *, DWORD, ' + 'DWORD, DWORD, LPCTSTR)

### ISSUE THREAD

**Issue by stegalin** [net-ssh/net-ssh#472]
### Actual result

> can't parse the function prototype: HANDLE CreateFileMapping(HANDLE, void *, DWORD, ' + 'DWORD, DWORD, LPCTSTR) (RuntimeError)
C:/Ruby22-x64/lib/ruby/2.2.0/fiddle/cparser.rb:90:in `parse_signature'
C:/Ruby22-x64/lib/ruby/2.2.0/fiddle/import.rb:162:in `extern'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/net-ssh-4.0.0/lib/net/ssh/authentication/pageant.rb:101:in `<module:Win>'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/net-ssh-4.0.0/lib/net/ssh/authentication/pageant.rb:41:in `<module:Pageant>'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/net-ssh-4.0.0/lib/net/ssh/authentication/pageant.rb:33:in `<module:Authentication>'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/net-ssh-4.0.0/lib/net/ssh/authentication/pageant.rb:24:in `<module:SSH>'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/net-ssh-4.0.0/lib/net/ssh/authentication/pageant.rb:24:in `<module:Net>'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/net-ssh-4.0.0/lib/net/ssh/authentication/pageant.rb:24:in `<top (required)>'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/net-ssh-4.0.0/lib/net/ssh/authentication/agent.rb:9:in `require'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/net-ssh-4.0.0/lib/net/ssh/authentication/agent.rb:9:in `<top (required)>'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/net-ssh-4.0.0/lib/net/ssh/authentication/key_manager.rb:4:in `require'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/net-ssh-4.0.0/lib/net/ssh/authentication/key_manager.rb:4:in `<top (required)>'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/net-ssh-4.0.0/lib/net/ssh/authentication/session.rb:4:in `require'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/net-ssh-4.0.0/lib/net/ssh/authentication/session.rb:4:in `<top (required)>'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/net-ssh-4.0.0/lib/net/ssh.rb:12:in `require'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/net-ssh-4.0.0/lib/net/ssh.rb:12:in `<top (required)>'

### System configuration

- net-ssh version - 4.0.0
- Ruby version - 2.2.6
- OS - Windows 7

### Example App

Project starting is failed on `require 'net/ssh'`

The problems with quotes are in the file 'lib/net/ssh/authentication/pageant.rb' in lines
`extern "HANDLE CreateFileMapping#{SUFFIX}(HANDLE, void *, DWORD, ' +
        'DWORD, DWORD, LPCTSTR)"`
and
`extern "LRESULT SendMessageTimeout#{SUFFIX}(HWND, UINT, WPARAM, LPARAM, ' +
         'UINT, UINT, PDWORD_PTR)"`

**Comment by mfazekas** [comment]
Thanks for the report! 
Interestingly it seems to work in 2.3.
