### ISSUE TITLE
Add support for the `proxyusefdpass` config option

### ISSUE THREAD

**Issue by dusty-stripe** [net-ssh/net-ssh#496]
ProxyUseFDPass changes the treatment of the ProxyCommand setting. With this set to `yes`, the client should expect that the ProxyCommand process will pass back a reference to a file descriptor on STDIN rather than communicating directly on STDIN.

https://www.openssh.com/txt/release-6.5

New Features
------------

* ssh(1): Add a ssh_config ProxyUseFDPass option that supports the
   use of ProxyCommands that establish a connection and then pass a
   connected file descriptor back to ssh(1). This allows the
   ProxyCommand to exit rather than staying around to transfer data.

**Comment by mfazekas** [comment]
We don't plan to implement this at the near future. Pr's are welcome.

**Comment by baelter** [comment]
Reconsider?
