### ISSUE TITLE
Connection can not be established with OpenSSH_7.3 server

### ISSUE THREAD

**Issue by yambrosov** [net-ssh/net-ssh#507]
### Expected behavior
Client (Net::SSH_4.1.0) to Server (FreeNas 9.10) ssh connection is ok

### Actual behavior
Client to Server ssh connection is NOT ok (Errno::ECONNRESET: An existing connection was forcibly closed by the remote host. - recvfrom(2))

### System configuration
local is `SSH-2.0-Ruby/Net::SSH_4.1.0 x64-mingw32'
remote is `SSH-2.0-OpenSSH_7.3-hpn14v5 FreeBSD-openssh-portable-7.3.p1_1,1'
- capistrano (3.8.0)
- net-ssh 4.1.0
- Ruby version 2.2.3
- OS client win 10

### Example App

Net::SSH.start('192.168.5.32', 'root', :password=>'12345678', :verbose => :debug) do |ssh|
OK: 
    #Net::SSH.start('172.16.25.104', 'root', :password=>'12345678', :verbose => :debug) do |ssh|
      puts ssh.exec!('echo "hello"')
    end

Logs:
[freebsd10.3_OK.txt](https://github.com/net-ssh/net-ssh/files/850056/freebsd10.3_OK.txt)
[freenas9.10_basedon10.3_NOTOK.txt](https://github.com/net-ssh/net-ssh/files/850055/freenas9.10_basedon10.3_NOTOK.txt)

**Comment by mfazekas** [comment]
```
D, [2017-03-17T11:51:38.374695 #16000] DEBUG -- net.ssh.transport.algorithms[1802aa4]: negotiated:
* kex: diffie-hellman-group14-sha1
* host_key: ssh-rsa
* encryption_server: none
* encryption_client: none
* hmac_client: hmac-sha1
* hmac_server: hmac-sha1
* compression_client: none
* compression_server: none
* language_client: 
* language_server: 
```

what is the sshd config on the server it cannot connect to?

**Comment by yambrosov** [comment]
Configs from the server attached
[ssh_config_server_7.3_freenas910.txt](https://github.com/net-ssh/net-ssh/files/850192/ssh_config_server_7.3_freenas910.txt)
[sshd_config_server_7.3_freenas910.txt](https://github.com/net-ssh/net-ssh/files/850191/sshd_config_server_7.3_freenas910.txt)

**Comment by yambrosov** [comment]
This problem can be solved by adding "ciphers +aes128-cbc" at config of sshd on server side
https://bugs.freenas.org/issues/20044
