### ISSUE TITLE
lib/net/ssh/authentication/session.rb:106 undefined method `split' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by claudijd** [net-ssh/net-ssh#508]
### Expected behavior

When net-ssh encounters a USERAUTH_FAILURE packet within the Net::Session class, but does not include authentications, packet[:authentications] should be set to an empty String class and not a NilClass.

### Actual behavior

When net-ssh encounters a USERAUTH_FAILURE packet within the Net::Session class, but does not include authentications, packet[:authentications] is set to nil, which causes a NoMethod exception when split is called on a NilClass object.

		.rvm/gems/ruby-2.2.3/gems/net-ssh-4.1.0/lib/net/ssh/authentication/session.rb:106:in `block in next_message': undefined method `split' for nil:NilClass (NoMethodError)
			from /Users/jclaudius/.rvm/gems/ruby-2.2.3/gems/net-ssh-4.1.0/lib/net/ssh/authentication/session.rb:95:in `loop'
			from /Users/jclaudius/.rvm/gems/ruby-2.2.3/gems/net-ssh-4.1.0/lib/net/ssh/authentication/session.rb:95:in `next_message'
			from /Users/jclaudius/.rvm/gems/ruby-2.2.3/gems/net-ssh-4.1.0/lib/net/ssh/authentication/methods/password.rb:24:in `authenticate'
			from /Users/jclaudius/.rvm/gems/ruby-2.2.3/gems/net-ssh-4.1.0/lib/net/ssh/authentication/session.rb:80:in `block in authenticate'
			from /Users/jclaudius/.rvm/gems/ruby-2.2.3/gems/net-ssh-4.1.0/lib/net/ssh/authentication/session.rb:66:in `each'
			from /Users/jclaudius/.rvm/gems/ruby-2.2.3/gems/net-ssh-4.1.0/lib/net/ssh/authentication/session.rb:66:in `authenticate'
			from /Users/jclaudius/.rvm/gems/ruby-2.2.3/gems/net-ssh-4.1.0/lib/net/ssh.rb:237:in `start'
			from ssh/guess_ssh_credentials.rb:19:in `block (2 levels) in <main>'
			from ssh/guess_ssh_credentials.rb:16:in `each'
			from ssh/guess_ssh_credentials.rb:16:in `block in <main>'
			from ssh/guess_ssh_credentials.rb:14:in `each'
			from ssh/guess_ssh_credentials.rb:14:in `<main>' 

### System configuration

- net-ssh-4.1.0
- ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]

### Example App

The following script was run against a SSH-2.0-cryptlib ssh daemon to repro the bug.

```ruby
ssh = Net::SSH.start(ip, username, :password => password, :number_of_password_prompts => 0, :timeout => 3, :paranoid => Net::SSH::Verifiers::Null.new, :auth_methods => [ 'password' ])
ssh.close
```

**Comment by mfazekas** [comment]
Thanks much for the detailed bugreport. 
From [RFC](https://www.ietf.org/rfc/rfc4252.txt) if not's clear if it's legal for the server to send SSH_MSG_USERAUTH_FAILURE with `nil` name-list, also not sure if our parser set's nil if they just send an empty list.

```
5.1.  Responses to Authentication Requests

   If the server rejects the authentication request, it MUST respond
   with the following:

      byte         SSH_MSG_USERAUTH_FAILURE
      name-list    authentications that can continue
      boolean      partial success




Ylonen & Lonvick            Standards Track                     [Page 5]

RFC 4252              SSH Authentication Protocol           January 2006


   The 'authentications that can continue' is a comma-separated name-
   list of authentication 'method name' values that may productively
   continue the authentication dialog.

   It is RECOMMENDED that servers only include those 'method name'
   values in the name-list that are actually useful.  However, it is not
   illegal to include 'method name' values that cannot be used to
   authenticate the user.

   Already successfully completed authentications SHOULD NOT be included
   in the name-list, unless they should be performed again for some
   reason.

   The value of 'partial success' MUST be TRUE if the authentication
   request to which this is a response was successful.  It MUST be FALSE
   if the request was not successfully processed.
```

**Comment by mfazekas** [comment]
Hm' looking at our parser code it sounds like server is sending invalid packet, we can add a workaround though

**Comment by claudijd** [comment]
@mfazekas thanks for the quick reply on this!

**Comment by claudijd** [comment]
Please note in the example code I provided that I'm being explicit about auth_methods.  I do wonder if it's just the mash up of me being explicit and the SSH server I'm scanning recognizing a fatal mismatch in requirements.

**Comment by mfazekas** [comment]
My understanding from rfc is that server should send an empty `name-list` vs just sending a `SSH_MSG_USERAUTH_FAILURE` without anything following it, which is what i think is happending in this case

**Comment by claudijd** [comment]
@mfazekas ah, gotcha.  I can try to dig more to track down the server-side issue, if we can handle this cleaner in net-ssh with a NoMethod, awesome!

**Comment by mfazekas** [comment]
Closing it for now, will be reopening on further input
