### ISSUE TITLE
Connection reset by peer in case this net-ssh used on remote host

### ISSUE THREAD

**Issue by yambrosov** [net-ssh/net-ssh#511]
### Context

Trying to configure https://github.com/continuent/tungsten-replicator automatically from net-ssh.
Tungsten-replicator also uses net-ssh for installation and working.
If i connect to installation from putty - it is ok, but if i do it from net-ssh - i get such error:

### Expected behavior

win10 (putty) -> node1-deb8 (ruby 2.0, net-ssh 4.1.0) -> node1-deb8 (ruby 2.0, net-ssh 4.1.0)
Connection OK

If i start the same from 1.1) win10 (ruby 2.3, net-ssh 4.1.0) - should also work

### Actual behavior

If i start the same from 1.1) win10 (ruby 2.3, net-ssh 4.1.0) - attached errors
[auth-nide1.log.txt](https://github.com/net-ssh/net-ssh/files/892647/auth-nide1.log.txt)
[auth-node2.log.txt](https://github.com/net-ssh/net-ssh/files/892646/auth-node2.log.txt)
[ssh-net-debug.txt](https://github.com/net-ssh/net-ssh/files/892648/ssh-net-debug.txt)
[tungsten-configure.log.txt](https://github.com/net-ssh/net-ssh/files/892645/tungsten-configure.log.txt)

2017-04-04T12:30:12+03:00 DEBUG >> Connection reset by peer
/home/tungsten/.rvm/gems/ruby-2.0.0-p643/gems/net-ssh-4.1.0/lib/net/ssh/authentication/agent.rb:199:in `read'
/home/tungsten/.rvm/gems/ruby-2.0.0-p643/gems/net-ssh-4.1.0/lib/net/ssh/authentication/agent.rb:199:in `read_packet'
/home/tungsten/.rvm/gems/ruby-2.0.0-p643/gems/net-ssh-4.1.0/lib/net/ssh/authentication/agent.rb:210:in `send_and_wait'
/home/tungsten/.rvm/gems/ruby-2.0.0-p643/gems/net-ssh-4.1.0/lib/net/ssh/authentication/agent.rb:98:in `negotiate!'
/home/tungsten/.rvm/gems/ruby-2.0.0-p643/gems/net-ssh-4.1.0/lib/net/ssh/authentication/agent.rb:63:in `connect'
/home/tungsten/.rvm/gems/ruby-2.0.0-p643/gems/net-ssh-4.1.0/lib/net/ssh/authentication/key_manager.rb:179:in `agent'
/home/tungsten/.rvm/gems/ruby-2.0.0-p643/gems/net-ssh-4.1.0/lib/net/ssh/authentication/key_manager.rb:103:in `each_identity'
/home/tungsten/.rvm/gems/ruby-2.0.0-p643/gems/net-ssh-4.1.0/lib/net/ssh/authentication/methods/publickey.rb:19:in `authenticate'
/home/tungsten/.rvm/gems/ruby-2.0.0-p643/gems/net-ssh-4.1.0/lib/net/ssh/authentication/session.rb:80:in `block in authenticate'
/home/tungsten/.rvm/gems/ruby-2.0.0-p643/gems/net-ssh-4.1.0/lib/net/ssh/authentication/session.rb:66:in `each'
/home/tungsten/.rvm/gems/ruby-2.0.0-p643/gems/net-ssh-4.1.0/lib/net/ssh/authentication/session.rb:66:in `authenticate'

### System configuration
1.1) win10 (ruby 2.3, net-ssh 4.1.0)
1.2) win10 (putty)
2.1) node1-deb8 (ruby 2.0, net-ssh 4.1.0) - installing tungstem from here, uses net-ssh internally to connect to node2
2.2) node2-deb8 (ruby 2.0, net-ssh 4.1.0)

### Example App
Usage Net::SSH.start from here
https://github.com/continuent/tungsten-replicator/blob/master/builder/extra/tools/ruby-tpm/configurator.rb#L1683

This is default SSH options:
       :timeout => 5,
      :auth_methods => ["publickey", "hostbased"],
      :paranoid => false

**Comment by mfazekas** [comment]
Thanks for the bugreport, it's likely a config issue, most likely putty supports some alg that's not supported by net-ssh.

I also see this line
```
Apr  4 12:30:11 nodeone sshd[5558]: channel 2: open failed: connect failed: could not connect to authentication agent
```
in the logs. Do you know why it happens?

**Comment by yambrosov** [comment]
Hi, may be the problem in the following:
1) i'm connecting from workstation to node1 with the password
2) node 1 is connecting to node to with public key with the same user

may be problem in this.

**Comment by mfazekas** [comment]
I'm closing the issue for now, will reopen on further input
