### ISSUE TITLE
authentication failure with long RSA key

### ISSUE THREAD

**Issue by RSH2000** [net-ssh/net-ssh#518]
### Expected behavior

Trying to connect with  a long 513 byte rsa private key. Connection is successful through command line with the same key .

### Actual behavior

D, [2017-05-09T19:48:06.173327 #11020] DEBUG -- socket[3ffb5e93a154]: received packet nr 6 type 51 len 28
D, [2017-05-09T19:48:06.173364 #11020] DEBUG -- net.ssh.authentication.session[3ffb5ea5b18c]: allowed methods: publickey
D, [2017-05-09T19:48:06.173404 #11020] DEBUG -- net.ssh.authentication.methods.none[3ffb5ea5a160]: none failed
D, [2017-05-09T19:48:06.173442 #11020] DEBUG -- net.ssh.authentication.session[3ffb5ea5b18c]: trying publickey
E, [2017-05-09T19:48:06.173899 #11020] ERROR -- net.ssh.authentication.key_manager[3ffb5ea5a354]: could not load private key file `~/.ssh/id_rsa': RbNaCl::LengthError (key was 513 bytes (Expected 32))

### System configuration

- net-ssh 4.1.0
- Ruby 2.4.0

### Example App

  keys = [ "~/.ssh/id_rsa" ]
  Net::SSH.start(host,user,:keys => keys,:use_agent => false,:verbose => :debug) do |session|
  res= session.exec!(command)
  end

**Comment by lifeofguenter** [comment]
experiencing the same

**Comment by calvinmuller** [comment]
+1

**Comment by craigedmunds** [comment]
Any update on this?

**Comment by mfazekas** [comment]
Can someone confirm it's still an issue with net-ssh 5.0?

**Comment by mfazekas** [comment]
See also: #634 will reopen the issue if it happens with net-ssh 5.1

**Comment by moskyt** [comment]
Just had this issue and I can confirm that it is fixed by moving to net-ssh 5.x.
