### ISSUE TITLE
Net::SSH::Server?

### ISSUE THREAD

**Issue by sempervictus** [net-ssh/net-ssh#52]
This isnt so much an issue as a feature request, but i'm wondering what it would take to have net-ssh listen for inbound connections? Is this feasible or planned at some point in the future? I'd be quite happy with it simply using the none auth method and not having to deal with authentication so long as it could accept incoming SSH connections even as a single channel. Thanks much

**Comment by mfazekas** [comment]
There was a project to get server side working, but it needs integration 
see: 
https://github.com/net-ssh/net-ssh/commits/server_side
