### ISSUE TITLE
If the password contains "@" ssh password login will not be recognized, will show the password to login

### ISSUE THREAD

**Issue by ssh-copy-id** [net-ssh/net-ssh#520]
If the password contains "@" ssh password login will not be recognized, will show the password to login

**Comment by mfazekas** [comment]
@ssh-copy-id thanks for the bugreport, can you show concrete example of how are you calling net-ssh?

**Comment by ssh-copy-id** [comment]
I'm sorry I'm wrong. I used the url to pass the character "asdf @ # $" containing the "@" "#" parameter, which I thought was "@". Then I output the url parameter ("asdf @ # $") found to be "#" caused by the error. I am sorry

**Comment by mfazekas** [comment]
As i understand it's not an error in net-ssh, so closing the issue.
