### ISSUE TITLE
IO doesn't have a recv.

### ISSUE THREAD

**Issue by joedaniels29** [net-ssh/net-ssh#527]
The docs say "This module is used to extend sockets and other IO objects, to allow them to be buffered for both read and write. This abstraction makes it quite easy to write a select-based event loop (see Net::SSH::Connection::Session#listen_to)." 
However, this is misleading. If I try to do: 

$stdin.extend(Net::SSH::BufferedIo)
 and then hook up ssh.listen_to($stdin)

things will fail because $stdin will not implement recv. 

is there a work around for this.

**Comment by mfazekas** [comment]
@joedaniels29 sorry i don't think we support this
