### ISSUE TITLE
Awkward grammar: `verify_host_key: :very`

### ISSUE THREAD

**Issue by jaredbeck** [net-ssh/net-ssh#532]
After renaming `:paranoid` to `:verify_host_key` (https://github.com/net-ssh/net-ssh/pull/524) it becomes apparent that `verify_host_key: :very` is awkward grammar. The other values are fine, but `:very` is awkward. I see a few solutions:

1. Do nothing (least disruptive)
2. Deprecate `:very` only, choosing a new word like `:strict`.
3. Deprecate all existing values, replacing them with a set of words that match the classes in the `Net::SSH::Verifiers` module. Values would be replaced as follows:
        - `nil` becomes `:null`, 
        - `true` becomes `:lenient`, 
        - `:very` becomes `:strict`, and
        - `:secure` remains `:secure`.
  This would be the most disruptive solution, but perhaps a nice improvement, improving data type consistency (they're all symbols) and expressiveness (they reveal the underlying classes).

I'm happy with all of these options, including doing nothing, but I thought I'd mention it anyway.

**Comment by mfazekas** [comment]
@jaredbeck Thanks, we're open to a PR on this. I'm ok with either 2 or 3. 
I'm closing this now, will reopen on further input.

**Comment by jaredbeck** [comment]
Thanks Miklós. I will open a PR implementing solution 3 (all symbols).
