### ISSUE TITLE
How to write a interactive shell using net-ssh?

### ISSUE THREAD

**Issue by Sanster** [net-ssh/net-ssh#541]
Hi!
I am learning how to use `Net::SSH::Connection::Channel#request_pty` to write a interactive shell, but I cannot find any example(google, stackoverflow) on how to use it. Is anyone know how to it? 

I have tried the follow code, but it only print `done!`
```ruby
require 'net/ssh'

Net::SSH.start('localhost', 'user', :password => "psd") do |ssh|
  channel = ssh.open_channel do |ch|
     ch.request_pty do |ch, success|
       ch.on_data do |c, data|
         puts "data received!"
         $stdout.print data
       end

       ch.on_extended_data do |ch, type, data|
         puts "stderr"
       end

       ch.on_close { puts "done!" }

       ch.send_data("ls\n")
     end
  end
end
```

Sorry for opening issue here, close this if it's not appropriate.

**Comment by surver** [comment]
Hi,

Try this:
Net::SSH.start('localhost', 'user', :password => "psd") do |ssh|
  channel = ssh.open_channel do |ch|

    ch.on_data do |ch, data|
      puts data
    end

    ch.on_extended_data do |ch, type, data|
      puts "stderr"
    end

    ch.on_close { puts "done!" }

    ch.request_pty
    ch.send_channel_request("shell")

    ch.send_data("ls -l\n")
  end

  ssh.loop
end

I can send commands, but I've problems sending new commands to interactive interface. I've readed the source code to find what to do to send syncronized code, but I don't know what to do...

If someone can help us... 👍

**Comment by lumean** [comment]
have a look at this gem: https://github.com/duke-automation/net-ssh-telnet  
then use something like:
```
require 'net/ssh'
require 'net/ssh/telnet'
require 'thread'

ssh_opts = {}
ssh_opts[:host_name] = "1.2.3.4"
ssh_opts[:user] = "myuser"
ssh_opts[:password] = "mypass"
ssh = Net::SSH.start(nil, nil, ssh_opts)
output = ""
ssh_telnet_opts = {
              "Session" => ssh,
              "Prompt" => /.*/,
              "Waittime" => @options["Waittime"],
              "Timeout" => @options["Timeout"],
}
session = Net::SSH::Telnet.new(ssh_telnet_opts) { |s|
  print s
}

sout = Thread.new do
  print session.waitfor( {"Match" => /.+/m, "Timeout" => nil}) while (true)
end

@esc_char = "\x01"

def usage
  puts "\n\nBy default the escape character is Ctrl-a"
  puts "Exit with: ^a^d  (Ctrl-a followd by Ctrl-d)"
  puts "Help with: ^a^h  (Ctrl-a followd by Ctrl-h)"
  puts "Change escape: ^a^b then type the new escape\n\n"
end

usage()

escape_started = false
session.write("\n")
#while a = STDIN.getch do
STDIN.echo = false
STDIN.raw!
STDIN.sync = true
STDOUT.sync = true
while a = STDIN.readpartial(1) #IO.select([STDIN])
    #p a
    if escape_started
        case a
        when "\x04" # ctrl-c
        break
        when "\b"   # ctrl-h
        usage()
        when "\x02" # ctrl-b
        @esc_char = STDIN.getch
        puts "Escape char changed to: '#{@esc_char.inspect}'"
        else
        escape_started = false
        end
    end # if escape_started

    if a == @esc_char
        escape_started = true
    end

    #print a if a == "\b"
    #print "\e[A" # moves cursor up
    #print "\b" * a.length
    session.write(a)
end
puts "cli stopping"
sout.kill()
puts "cli stopped"
```
On Windows I had some issues that the cursor keys are not recognized by  `STDIN#getch` or `STDIN#readpartial` but did not follow it up.

**Comment by mfazekas** [comment]
I'm closing the issue as it's more belongs to stackoverflow.
