### ISSUE TITLE
Slow file upload via CTR mode of encryption

### ISSUE THREAD

**Issue by gsecillano** [net-ssh/net-ssh#542]
### Expected behavior

Uploading via SCP using CTR encryption mode should be comparable to using CBC.

### Actual behavior

CTR encryption mode is ~46x slower than CBC.  For a 79MB file upload via SCP:

*aes128-ctr*
```
real    1m17.345s
user    1m15.700s
sys     0m1.464s
```
*aes128-cbc*
```
real    0m2.538s
user    0m1.688s
sys     0m0.680s
```

### System configuration

- net-ssh version: 2.7.0 (reproducible on 4.1.0)
- Ruby version: 2.2.6 (jemalloc)

### Example App

```ruby
#gem 'net-ssh', '= 2.7.0'
gem 'net-scp', '= 1.1.2'
require 'net/scp'
puts Net::SSH::Version::CURRENT

@host = ENV['HOST']
@user = ENV['USER']
Net::SCP.start(@host, @user, encryption: ENV['ENCRYPTION'] || 'aes128-cbc') do |scp|
  # The file /tmp/testdata was created using
  #   dd if=/dev/random of=/tmp/testdata count=1024000
  scp.upload!('/tmp/testdata', '/tmp/testdata')
end
```

**Comment by mfazekas** [comment]
@gsecillano can you please try #570  and #569
