### ISSUE TITLE
LoadError (cannot load such file -- net/ssh)

### ISSUE THREAD

**Issue by marcatakubo** [net-ssh/net-ssh#548]
### Expected behavior
I just want to execute a command on SSH when a certain condition is true in my app controller. 

### Actual behavior
When manually running the command in my SSH it runs flawlessly. But when I try to use it in my app, it shows an error 
`LoadError (cannot load such file -- net/ssh)`

### System configuration

- net-ssh (4.2.0)
- ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]

### Example App
```ruby
require 'rubygems'
require 'net/ssh'
Net::SSH.start('host', 'user', :password => "pass") do |ssh|
    ssh.exec!("cd path/; /bin/bash -l -c 'cd /home/user/path && bundle exec script/rails runner -e development '\''Method.name_of_exec'\'''")
end
````

**Comment by mfazekas** [comment]
do you have net-ssh gem installed? can you try adding `gem('net-ssh')` just after `require('rubygems')` does it finds net-ssh?

**Comment by marcatakubo** [comment]
Yes i tried adding it to my `Gemfile` and ran `bundle install`. Also tried running `gem install net-ssh` but still dont work.
