### ISSUE TITLE
Agent forwarding does not work on Windows

### ISSUE THREAD

**Issue by mkremer** [net-ssh/net-ssh#55]
Agent forwarding with Pageant does't work as mentioned in #14. I tried applying the code changes suggested by @warezthebeef and @civiliz, however that doesn't do the trick for me. When trying to perform a command on another server through SSH that can only be reached by using agent forwarding it seems to hang indefinitely.

When I interrupt the command the stacktrace points to it hanging on IO#select

Does anybody have any idea as to how to make it work?

I'm trying to make this work with Ruby 1.9.3 on Windows 7.

**Comment by sschuberth** [comment]
@mkremer Looks like this was fixed in #140 and can be closed now, or?

**Comment by mkremer** [comment]
That issue does seem to reference the same problem. I'm find with closing this issue.
