### ISSUE TITLE
Setup.sh Claimed LGPL license, but the project claims MIT license

### ISSUE THREAD

**Issue by goupeng212** [net-ssh/net-ssh#551]
### Expected behavior
Currently, our internal security team reports we are using the LGPL license from the file setup.sh in  the net-ssh of V2.9 . However, the project claim MIT license. We expect the setup.sh refine and remove LGPL license 

### Actual behavior
In the setup.sh , the file claims GNU LGPL
```

# setup.rb
#
# Copyright (c) 2000-2005 Minero Aoki
#
# This program is free software.
# You can distribute/modify this program under the terms of
# the GNU LGPL, Lesser General Public License version 2.1.
#
```
### System configuration

- net-ssh 2.9
- Ruby version :  1.9.1

**Comment by mfazekas** [comment]
I don't think we have setup.sh any more
