### ISSUE TITLE
An existing connection was forcibly closed by the remote host. - recvfrom(2) (Errno::ECONNRESET)

### ISSUE THREAD

**Issue by sgorle** [net-ssh/net-ssh#558]
### Expected behavior

We should get Connection successful.

### Actual behavior

Getting the error Errno::ECONNRESET

### System configuration

- net-ssh version - 4.2.0
- Ruby version - 2.3.3

### Example App

@session = Net::SSH.start( IPAddress,
                                       User,
                                       :password => @password,
                                       :key_data => @key
                                     )

The remote is and hardware with an Application processor, we tried to connect it using it's IP address.

### Error stack trace

C:/Ruby23/lib/ruby/gems/2.3.0/gems/net-ssh-4.2.0/lib/net/ssh/buffered_io.rb:65:in `recv': An existing connection was forcibly closed by the remote hos
t. - recvfrom(2) (Errno::ECONNRESET)
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/net-ssh-4.2.0/lib/net/ssh/buffered_io.rb:65:in `fill'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/net-ssh-4.2.0/lib/net/ssh/transport/packet_stream.rb:91:in `next_packet'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/net-ssh-4.2.0/lib/net/ssh/transport/session.rb:193:in `block in poll_message'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/net-ssh-4.2.0/lib/net/ssh/transport/session.rb:188:in `loop'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/net-ssh-4.2.0/lib/net/ssh/transport/session.rb:188:in `poll_message'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/net-ssh-4.2.0/lib/net/ssh/transport/session.rb:225:in `block in wait'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/net-ssh-4.2.0/lib/net/ssh/transport/session.rb:223:in `loop'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/net-ssh-4.2.0/lib/net/ssh/transport/session.rb:223:in `wait'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/net-ssh-4.2.0/lib/net/ssh/transport/session.rb:88:in `initialize'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/net-ssh-4.2.0/lib/net/ssh.rb:237:in `new'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/net-ssh-4.2.0/lib/net/ssh.rb:237:in `start'

NOTES:
1. We are seeing this issue intermittently.
2. While executing my script, I see this issue in between also, i.e at first the it is connecting successfully but after some random amount of time again I see the disconnection. I tried with various timeout options that this gem provides but nothing worked out.

**Comment by mfazekas** [comment]
Hi thanks for the report.  The server terminated the connection, you need to see the server's logs on why it happened. It's possible that it's an issue in net-ssh but there is not enough info to tell what is it.
