### ISSUE TITLE
[DOC] net-ssh 5 and later ed25519 support

### ISSUE THREAD

**Issue by mfazekas** [net-ssh/net-ssh#565]
While net-ssh 5.0 and later supports ed25519 out of the box, net-ssh gem does not require the dependencies required for ed25519.

This issue documents the dependencies needed for ed25519 for net-ssh 5.0 and later.

Required dependencies for ed25519

    ed25519 (>= 1.2, < 1.3)
    bcrypt_pbkdf (>= 1.0, < 2.0) [not supported on java platform]

Note that as stated above bcrypt_pbkdf is a native gem and there is no jruby support at this time. This dependency is only required for decrypting password protected ed25519 keys, so if your ed25519 keys are not password protected or loaded to agent then you can still get ed25519 support on jruby.

See #478 for net-ssh `4.*` dependencies

**Comment by guanting112** [comment]
add ed25519 and bcrypt_pbkdf to Gemfile.

```Gmefile
gem 'ed25519', '>= 1.2', '< 2.0'
gem 'bcrypt_pbkdf', '>= 1.0', '< 2.0'
```

**Comment by daveomcd** [comment]
I was getting this error, but it was because I'm running WSL and didn't do the following before attempting to deploy my code.

`eval $(ssh-agent -s)`
`ssh-add ~/.ssh/id_rsa`

**Comment by JohnSmall** [comment]
@daveomcd 's comment fixed it for me on Ubuntu 20.04. I think my problem could have occurred because I was running Capistrano in a Tmux session window, which didn't set up ssh keys correctly

**Comment by roberthopman** [comment]
Note to self: add the 2 lines of @daveomcd to `.zshrc` or other dot file so you don't have to manually search for this each time you use capistrano.

**Comment by TSMMark** [comment]
> add ed25519 and bcrypt_pbkdf to Gemfile.
> 
> ```
> gem 'ed25519', '>= 1.2', '< 2.0'
> gem 'bcrypt_pbkdf', '>= 1.0', '< 2.0'
> ```

Anyone know if they need to be required or can they have `require: false`?

```
gem 'ed25519', '>= 1.2', '< 2.0', require: false
gem 'bcrypt_pbkdf', '>= 1.0', '< 2.0', require: false
```
