### ISSUE TITLE
net-ssh should avoid non-FIPS compliant cryptography when used on a FIPS-enabled system

### ISSUE THREAD

**Issue by trevor-vaughan** [net-ssh/net-ssh#574]
### Expected behavior

When using net-ssh on a system that has been set in`fips` mode, the code should not crash at any point.

### Actual behavior

Presently, the use of `OpenSSL::Digest::MD5.hexdigest` will cause an immediate failure on a FIPS-enabled system.

### System configuration

- net-ssh version: 4.2.0
- Ruby version: 2.4.1 and 2.1.9

### Example App

Any use of `Net::SSH.start` will cause the crash. The easiest method for reproducing the issue is to boot a CentOS 7 system in `fips` mode and then run a simple `Net::SSH.start` against any system using the **system** Ruby.

Full instructions can be found [in the Red Hat Documentation](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/security_guide/chap-federal_standards_and_regulations)

**Comment by mfazekas** [comment]
Net-ssh 5.0 should improve on this. I'm closing the issue for now will reopen on further input.
