### ISSUE TITLE
connect to windows openssh with wrong username ("sshd_server" instead of "IEUser")

### ISSUE THREAD

**Issue by clement-igonet** [net-ssh/net-ssh#576]
### Expected behavior

When running "vagrant provision" via ssh to a windows guest (modern.ie - win7 - ie11), I should see "IEUser" as username when calling "whoami" command.
```
    default: ie11win7\ieuser
```

It's what I get when connecting directly with openssh client
```
> sshpass -p 'Passw0rd!' ssh -p 2222 -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" IEUser@127.0.0.1 'whoami'
Warning: Permanently added '[127.0.0.1]:2222' (ECDSA) to the list of known hosts.
ie11win7\ieuser
```

### Actual behavior

When running "vagrant provision" via ssh to a windows guest, I see "sshd_server" as username" when calling "whoami" command.
```
 INFO ssh: Execute: chown -R IEUser /tmp/vagrant-shell (sudo=true)
DEBUG ssh: Exit status: 0
DEBUG ssh: Uploading: /tmp/vagrant-shell20180209-24166-aw2g2p.ps1 to /tmp/vagrant-shell
DEBUG ssh: Re-using SSH connection.
 INFO interface: detail: Running: inline script
 INFO interface: detail:     default: Running: inline script
    default: Running: inline script
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: chmod +x '/tmp/vagrant-shell' && /tmp/vagrant-shell (sudo=false)
DEBUG ssh: stderr: 41e57d38-b4f7-4e46-9c38-13873d338b86-vagrant-ssh
DEBUG ssh: stderr: ++ whoami

 INFO interface: detail: ++ whoami
 INFO interface: detail:     default: ++ whoami
    default: ++ whoami
 INFO interface: detail: ie11win7\sshd_server
 INFO interface: detail:     default: ie11win7\sshd_server
    default: ie11win7\sshd_server
```
### System configuration

- vagrant version: Vagrant 2.0.2
- net-ssh version: SSH-2.0-Ruby/Net::SSH_4.2.0 x86_64-linux
- Ruby version: ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux-gnu]

### Example App

Extract of my Vagrantfile:
```ruby
# (...)
  config.vm.guest = :windows
  config.ssh.username = "IEUser"
  config.ssh.password = "Passw0rd!"
  config.ssh.insert_key = false
  config.ssh.sudo_command = ''
  config.ssh.shell = 'sh -l'
  config.vm.provision "shell",
    binary: true,
    privileged: false,
    inline: <<-SHELL
    set -x
    whoami
  SHELL
# (...)
```

**Comment by mfazekas** [comment]
Thanks for the report! It would be great to have a reproduction without vagrant

**Comment by mfazekas** [comment]
@clement-igonet Unfortunately i do not have resources to debug vagrant related issues, please report the bug to vagrant maintaneers, they should be able to create a net-ssh only bugreport if it's a net-ssh issue. Thanks for the understanding!
