### ISSUE TITLE
SSH command returing special characters

### ISSUE THREAD

**Issue by abhilash945** [net-ssh/net-ssh#577]
### Expected behavior
If I run the same command in putty, the result is clear without any special characters.
Tell us what should happen
So the same command if I run using the Expect function along with the result it is also returning some special characters like [D or long spaces.
### Actual behavior
It should be same as putty result.

### System configuration
- net-ssh version latest

**Comment by mfazekas** [comment]
@abhilash945 thanks for the report, can you please post a script to reproduce the issue? 

I'm closing the issue now will reopen on more information.
