### ISSUE TITLE
<ArgumentError: iv must be 0 bytes>

### ISSUE THREAD

**Issue by gr790** [net-ssh/net-ssh#578]
### Expected behavior

It should successfully create a socket

### Actual behavior

Instead of above, it print iv must be 0 bytes

### System configuration

net-ssh 2.9.4
ruby 2.4.3p205

### Example App

```
require 'net/ssh'
puts Net::SSH::Version::CURRENT

@host = 'localhost'
@user = 'oamsys'
Net::SSH.start(@host, @user) do |ssh|
  puts ssh.exec!('echo "hello"')
end
```

**Comment by mfazekas** [comment]
@gr790 sorry i cannot answer the question, there is not enough information here. Have you tried with latest version? Also reading server or client logs might help understanding the issue.

**Comment by geanguanxue** [comment]
This has been fixed in this commit, means you'll be good if you upgrade to v4.0+:
https://github.com/net-ssh/net-ssh/commit/3e8a469a60d0acfd3b1071bf338c1666026c6e47#diff-2ae6f27bf4778912fdbe807199b9eaaf

Took me a whole night to find out...
