### ISSUE TITLE
Host match broken?

### ISSUE THREAD

**Issue by nhed** [net-ssh/net-ssh#581]
### Expected behavior
the port number listed in the wildcard match (2222) should show up in the log

### Actual behavior
default port of 22 shows up in the logs
```
D, [2018-03-05T02:40:44.269863 #23130] DEBUG -- net.ssh.transport.session[2ad7aa5876c0]: establishing connection to 192.168.111.102:22
```

### System configuration

- net-ssh version (5.0.0.beta1 #cfb3ac692af643cc7faa30ba3d9c3dd4caa14e9f but older ones tested as well)
- Ruby version (ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux])

### Example App
```
#!/usr/bin/env ruby
# Note - hosts do not need to exit - we are just looking at the log to see the impact of config
require 'net/ssh'

Net::SSH.start("host_a", "lab", :verbose=>:debug) do |ssh|
  ssh.exec!("ls /tmp")
  ssh.loop
end
```

Config for test - temporarily replace your `~/.ssh/config` with 
```
Host host_d
    Hostname 192.168.111.100

Match host *
    Port 2222
Host host_a
    Hostname 192.168.111.102
```

Note - reduced from full multi-file (working) `openssh`

**Comment by mfazekas** [comment]
Thanks for the report `Match` is not fully supported for now only `all` works #593  should improve on that.
