### ISSUE TITLE
Do you follow SemVer? If yes, please mention in README

### ISSUE THREAD

**Issue by pravi** [net-ssh/net-ssh#582]
We already got a lot of positive response from many projects which updated their READMEs as tracked in https://wiki.debian.org/Teams/Ruby/UpstreamPledge

**Comment by mfazekas** [comment]
We do try to follow the spirit of semver guidelines, but IMO that doesn't really guarantees anything in practice. I can imagine a lot of minor bugfixes that might be breaking change for some exotic apps.
