### ISSUE TITLE
Public RSA key not identified.

### ISSUE THREAD

**Issue by bdiz** [net-ssh/net-ssh#59]
The following error occurs it seems, because the public key is being improperly identified as dss.

/gems/net-ssh-2.5.2/lib/net/ssh/key_factory.rb:101:in `load_data_public_key': not a public key "/usr/joe/.ssh2/id_rsa_2048_a.pub" (OpenSSL::PKey::PKeyError)

Key looks like:
---- BEGIN SSH2 PUBLIC KEY ----
Subject: joe
Comment: "2048-bit rsa, joe@nas2000, Tue Mar 20 2012 14:17:39 -\
0700"
AAAAB3NzaC1yc2EAAAADAQABAAABAQCbmWOXX0+2HUWfFdQHDiW+vMfkuetv/D+rOKtCQs
apCcxeFU9Ru5m+jZtb9ozv... <rest of public key>
---- END SSH2 PUBLIC KEY ----

Has there been any luck getting Net::SSH working with SSH2/sshkeygen2?

**Comment by mfazekas** [comment]
We don't support PEM at the momemnt /rfc4716
we only support authroized_keys format. which has a base64-encoded key
But this is what normally ssh-keygen creates, not sure about sshkeygen2 we need more description on the usecase
