### ISSUE TITLE
Using a 2nd key configured on a Proxy::Jump?

### ISSUE THREAD

**Issue by jletizia** [net-ssh/net-ssh#596]
I was curious if the following was possible (I have yet to figure out the right combination of runtime options to make this work):

Host A authenticates to Proxy::Jump host using Key A, the Proxy::Jump host has Key B stored on it, which is then used to authenticate against the final endpoint of Host B.

Is this possible? All of the documentation that I've read (utilizing the keys option, etc) seem to only support specifying a list of keys to get to the Proxy::Jump host in the first place, but not specifying a 2nd key to use once there. Is there any sort of ssh config file fun that I could do instead to achieve the same thing?

**Comment by jletizia** [comment]
Basically the behavior I'm trying to reproduce is:

`ssh -t <JUMP-USER>@<JUMP-IP> -p <JUMPPORT> ssh <ENDHOST>@<ENDHOST-IP>`

where it will connect to <JUMP-IP> using my local key, and then connect to <ENDHOST-IP> using <JUMP-USER>'s local key stored on <JUMP-IP>

**Comment by mfazekas** [comment]
Adding an way to add more arguments to `Jump::Proxy` per #653 might solve this too.
