### ISSUE TITLE
Unexpected closed_stream

### ISSUE THREAD

**Issue by BenjaminJacobsImtech** [net-ssh/net-ssh#610]
Dear, 
### Expected behavior

Connection open to the Nokia equipment, 
The session should remain open in order to send commands.

### Actual behavior

Connection hangs when trying to send the first command after sucessfull login.

### System configuration

- net-ssh version: 5.0. 1 (same behavior on 4.2)
- Ruby version 2.4.4p296 (on windows)

### Example App
`require 'net/ssh'
require_relative 'params.rb'
Net::SSH.start( @oobip , @login, :password =>@pwd, :verbose => :debug) do |session|
	output = session.exec!("admin display-config\n")
end`

[log.txt](https://github.com/net-ssh/net-ssh/files/2089248/log.txt)

note: using other tools like putty works fine.

Thank you in advance for your help/advices,
Benjamin Jacobs.

**Comment by mfazekas** [comment]
@BenjaminJacobsImtech all i can see that after successfull password auth the server closed the connection (before or just after we issued `exec` command.)

You'd need to look into the server logs.

**Comment by BenjaminJacobsImtech** [comment]
Sadly, the logs of the equipment doesn't allow further debugging.
I do see in wireshark that the server send a TCP FIN,ACK during the exec.
(the channel open successfully, the client sends data and the server unexpectedly close the connection)

![image](https://user-images.githubusercontent.com/7934801/41230334-b1380d8c-6d7f-11e8-8ebe-5de9ec31a089.png)

and that's all...
