### ISSUE TITLE
need to press enter key twice 

### ISSUE THREAD

**Issue by remon** [net-ssh/net-ssh#616]
### Expected behavior
I use net-ssh with capistrano , when I deploy my app , I used to just enter the password for the server in some cases , everything was working fine for years 

### Actual behavior
what happens now that 
I need to press enter key twice so the password is accepted , I tried also to login to my server with ssh command only , everything is fine , just one Enter Key , nothing wrong with my keyboard or windows .

### System configuration

- net-ssh version 4.2.0
- Ruby version 2.2.1p85 
-Capistrano Version 2.13.5

- I am using cygwin on windows 10 machine

**Comment by mfazekas** [comment]
@remon please test with the latest version of net-ssh. Also it's not clear from description if you password is rejected for the first attempt our it's just re requesting the password.

**Comment by remon** [comment]
The password is not rejected , but I need to press the Enter Key twice instead of one time
