### ISSUE TITLE
Jump Proxy ignores verify_host_key and other SSH configuration

### ISSUE THREAD

**Issue by adammw** [net-ssh/net-ssh#617]
### Expected behavior

When using a jump proxy, the jump proxy applies the same configuration as the rest of net-ssh. 

### Actual behavior

When using a jump proxy, net-ssh shells out to the system's ssh command, and doesn't pass along configuration such as turning off host key verification. 

### System configuration

- net-ssh version: 5.0.2
- Ruby version: 2.5.1p57

### Example App

```ruby
gem 'net-ssh', '= 5.0.2'
require 'net/ssh'
puts Net::SSH::Version::CURRENT

@host = 'localhost'
@user = ENV['USER']
proxy = Net::SSH::Proxy::Jump.new('user@proxy')
Net::SSH.start(@host, @user, proxy: proxy, verify_host_key: :never) do |ssh|
  puts ssh.exec!('echo "hello"')
end
```

**Comment by mfazekas** [comment]
@adammw i'm not sure about this request. I'd say you might want to verify proxy but not target host or vica versa, as per 653 a way to pass additional options/arguments to Proxy::Jump might be enough.
