### ISSUE TITLE
NetSSH matches all conditions if ssh config has `Match` with criteria other than `host`

### ISSUE THREAD

**Issue by vedharish** [net-ssh/net-ssh#631]
### System configuration

- net-ssh version: `5.0.2`
- Ruby version: `ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin17]`
- `ssh -v`: `OpenSSH_7.6p1, LibreSSL 2.6.2`

### Example App

I am using [`Match`](https://man.openbsd.org/ssh_config#Match) in my ssh config file with multiple blocks with criteria `exec`. 

From the case statement [here](https://github.com/net-ssh/net-ssh/blob/7429a290230b2f31179047a7130b40744e1b0b54/lib/net/ssh/config.rb#L335), looks like net-ssh does not support criteria other than `host`. The issue is that the even for unsupported blocks, because of the default=true [here](https://github.com/net-ssh/net-ssh/blob/7429a290230b2f31179047a7130b40744e1b0b54/lib/net/ssh/config.rb#L333), NetSSH sources blocks for each of these criteria and we end up with mixed up config for connection.

I feel that for unsupported blocks / criteria, we should just ignore the block ( as if they are absent ) (ie have `eval_match_conditions` return false for unsupported blocks)

Sample ssh config:
```bash
IdentityFile ~/.ssh/id_rsa

Host random_host
  Port 4444

Match exec "exit 1"
  ProxyJump other_host

Match exec "exit 1"
  IdentityFile ~/.ssh/personal_id_rsa
```

Sample net/ssh code:
```ruby
require 'net/ssh'

Net::SSH.start("random_host", "dev", :verbose=>:debug) do |ssh|
  ssh.exec!("ls /tmp")
  ssh.loop
end
```

### Expected behavior

Should not use proxy for connection to random:host:4444 with `id_rsa`
- cli ssh evaluates exec conditions are executes based on return code
- This issue is not for implementing `exec` support, but just to have false as default so as to ignore unsupported blocks

### Actual behavior

Output from the above code
```bash
DEBUG -- net.ssh.transport.session[3fc610c9c76c]: establishing connection to xx.xx.xx.xx:4444 through proxy
```
Also ^ `personal_id_rsa` is used instead of `id_rsa`

**Comment by aleksandrs-ledovskis** [comment]
https://github.com/net-ssh/net-ssh/pull/642

**Comment by vedharish** [comment]
Thanks @aleksandrs-ledovskis @mfazekas
