### ISSUE TITLE
Cannot ssh with ssh RSA keys having BEGIN OPENSSH PRIVATE KEY header (PKCS8 format)

### ISSUE THREAD

**Issue by frezbo** [net-ssh/net-ssh#633]
### Expected behavior

SSH should work

### Actual behavior

SSH authentication fails, but manual ssh works

### System configuration

- net-ssh version - 5.0.2
- Ruby version - ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]

### Example App

```
net_ssh_test (aws:rean-devops)(kc)$ bundle list 
Gems included by the bundle:
  * bcrypt_pbkdf (1.0.0)
  * bundler (1.16.5)
  * ed25519 (1.2.4)
  * net-ssh (5.0.2)
net_ssh_test (aws:rean-devops)(kc)$ 
```

key generated on Fedora 28 with `ssh-keygen -q -N '' -f image-keypair`

System details:
```
net_ssh_test (aws:rean-devops)(kc)$ uname -a
Linux frezbo 4.18.8-200.fc28.x86_64 #1 SMP Sun Sep 16 18:15:41 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
net_ssh_test (aws:rean-devops)(kc)$ cat /etc/*-release
Fedora release 28 (Twenty Eight)
NAME=Fedora
VERSION="28 (Workstation Edition)"
ID=fedora
VERSION_ID=28
PLATFORM_ID="platform:f28"
PRETTY_NAME="Fedora 28 (Workstation Edition)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:fedoraproject:fedora:28"
HOME_URL="https://fedoraproject.org/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=28
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=28
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
Fedora release 28 (Twenty Eight)
Fedora release 28 (Twenty Eight)
net_ssh_test (aws:rean-devops)(kc)$ 
```

**Manual SSH works fine**

Code:

```
require 'net/ssh'

opts = {
  :host => '34.205.48.89',
  :port => 22,
  :user => 'ec2-user',
  :key_files => ['image-keypair'],
}

opts[:logger] = Logger.new(STDERR)
opts[:logger].level = Logger::INFO

Net::SSH.start(opts[:host], opts[:user], :keys => opts[:key_files], :keys_only => true, :logger => opts[:logger]) do |ssh|
  ls_result = ssh.exec("ls -l")
  puts ls_result
end
```

Key starts with `BEGIN OPENSSH PRIVATE KEY`

**Comment by mfazekas** [comment]
@frezbo thaks for the bugreport. Do you see anything in the logs about `image-keypair` any exception thrown? What is the failure you see?

**Comment by frezbo** [comment]
@mfazekas I have found the bug here: https://github.com/net-ssh/net-ssh/blob/master/lib/net/ssh/key_factory.rb#L112. The actual generated key was an RSA key, i  have updated the bug description. The `ssh-keygen` command on **FIPS** enabled systems and on newer version generate RSA key that begins with `BEGIN OPENSSH PRIVATE KEY`. Hence we cannot assume a key starting with `BEGIN OPENSSH PRIVATE KEY` as an ed25519 key.

**Comment by phillc** [comment]
I am encountering this same issue. Have you figured out a work around?

**Comment by frezbo** [comment]
@phillc not any workaround, I ended up creating normal RSA key, with ruby. The `ssh-keygen` still creates PKCS#8 format keys

**Comment by sls** [comment]
I was able to convert an existing key with this problem (RSA generated with -o and thus in the new format) by adding and removing a passphrase and not specifying -o as follows:
% ssh-keygen -p -f id_rsa       # add a passphrase when prompted
% ssh-keygen -p -f id_rsa       # provide the passphrase you added and specify an empty passphrase at the prompt

**Comment by MikaelSmith** [comment]
I'm encountering a similar issue with an ECDSA key, created with `ssh-keygen -t ecdsa`. Starting with OpenSSH 7.8, the key is created with the OpenSSH private key format instead of the OpenSSL PEM format (see [openssh's release notes](https://www.openssh.com/releasenotes.html)).

With the `ed25519` gem installed, I get an exception `expected 64-byte String, got 65` from https://github.com/crypto-rb/ed25519/blob/v1.2.4/lib/ed25519/signing_key.rb#L20. I'm not sure whether the part that's wrong is that it's using the ed25519 gem, or that the ed25519 gem doesn't support the OpenSSH format. Happy to open an issue there if it's the latter.

**Comment by MikaelSmith** [comment]
A fix for this probably needs to add support for reading the protocol described at https://github.com/openssh/openssh-portable/blob/master/PROTOCOL.key.

**Comment by stiller-leser** [comment]
I have found another solution and described it here: https://github.com/net-ssh/net-ssh/issues/638#issuecomment-441189002 - unfortunately this requires a new key. Maybe worth closing #638 to focus the discussion?

**Comment by eepstein** [comment]
Is this fixed in a patch release?  We're on 2.4.2 and this has broken our workflows.  We were on a much older version and things worked.  We'd rather not roll-back due to other dependencies.  openssh is widely used and it seems from the code, easy to support.  Can we offer a PR?

**Comment by chris-kiick-sp** [comment]
According to https://serverfault.com/questions/939909/ssh-keygen-does-not-create-rsa-private-key openssh has changed the default new key format.  To get the old format you have to add '-m PEM' to the keygen command.  That should be a simple patch to the module code.

I have found that the openssl_privatekey module generates the PEM format, and has similar options to openssh_keypair.  If you need the corresponding public key, the openssl_publickey module can create it from the private key.

```
diff --git a/lib/ansible/modules/crypto/openssh_keypair.py b/lib/ansible/modules/crypto/openssh_keypair.py
index 61c8513eb1..b411fbfbca 100644
--- a/lib/ansible/modules/crypto/openssh_keypair.py
+++ b/lib/ansible/modules/crypto/openssh_keypair.py
@@ -173,6 +173,7 @@ class Keypair(object):
                 '-b', str(self.size),
                 '-t', self.type,
                 '-f', self.path,
+                '-m', 'PEM',
             ]

             if self.comment:
```
NOTE: haven't tested the patch.

**Comment by cangetright** [comment]
Why is someone named Ed using my account I just created, on Termius?

**Comment by cangetright** [comment]
What’s that mean? I can’t figure out how to start or where?
