### ISSUE TITLE
Socket error, even though I can connect using ssh

### ISSUE THREAD

**Issue by ilovemysillybanana** [net-ssh/net-ssh#648]
### Expected behavior

I am attempting to use the net/ssh library to connect to a node, it does in fact work a majority of the time. However, sometimes there are **some** nodes that don't work. It may be an issue on my end or an issue on net/ssh's part I'm not really sure. 

I am running several thousand connections(**single threaded currently**). One thing I have noticed that is *special* about these nodes is that I **AM** **able** to ssh into them, but I **can not** resolve their ip addresses using `nslookup`.  If I attempt to do so I met with the following result:

```
[user@jumpbox ssh_gem]$ nslookup machine_name
Server:		xxx.xxx.xxx.xxx
Address:	xxx.xxx.xxx.xxx#53

** server can't find machine_name: NXDOMAIN
```

I'm wondering if this library goes through and relies on something to do with a dns lookup? Because that will always fail for these affected nodes. I just can't think of another reason why I'd be able to ssh into the node manually, and not be able to do so using this library. I'm not sure what's wrong the dns entries for the nodes, just that their ip's can't be gotten using nslookup but you can ssh into them just fine. 

### System configuration
- net-ssh net-ssh (5.0.2)
- Ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]

### Example App

```ruby
Net::SSH.start('machine_name', 'user', options = { :keys => ['~/.ssh/id_rsa'], :non_interactive => true, :verify_host_key => :never }) do |con|
  pwd = con.exec!("pwd")
end
```

**Comment by mfazekas** [comment]
I'm not sure if you cannot resolve their names, maybe there is somehting in `ssh_config` that let's you connect to them. 

I'm closing this as there is not enough info to determine if it's a net-ssh issue or not.
