### ISSUE TITLE
fetch switch config and protocol error: rcvd type 0

### ISSUE THREAD

**Issue by kevhjelm** [net-ssh/net-ssh#664]
I'm trying to get switch config using oxidized. For my last 10 switches I'm getting an SSH error
### Expected behavior
When running oxidized it is suppose to go and fetch the config from the switch using ssh, this is working for almost all my devices, but not for the last 10. These are Extreme network switches VSP 9012 and VSP 8400 series. 

Below is the switch log 

CP1  [03/06/19 10:29:03.492:CET] 0x000d8603 00000000 GlobalRouter SSH INFO Enabling compatibility mode for protocol 2.0
CP1  [03/06/19 10:29:03.504:CET] 0x0003c77a 00000000 GlobalRouter IP INFO kex:chosen algorithms for client->server: encryption:aes128-cbc mac:hmac-sha1 compression:none
CP1  [03/06/19 10:29:03.507:CET] 0x0003c77a 00000000 GlobalRouter IP INFO kex:chosen algorithms for server->client: encryption:aes128-cbc mac:hmac-sha1 compression:none
CP1  [03/06/19 10:29:03.642:CET] 0x000d8602 00000000 GlobalRouter SSH INFO Disconnecting: protocol error: rcvd type 0

Below is the oxidized log 

#28714] DEBUG -- : 10.20.4.1 raised Net::SSH::Disconnect with msg "disconnected: protocol error: rcvd type 0 (2)"
 #28714] DEBUG -- : lib/oxidized/node.rb: Oxidized::SSH failed for host-1-test
 #28714] DEBUG -- : lib/oxidized/job.rb: Config fetched for host-1-test.com  at 2019-03-06 09:37:53 UTC
 #28714]  WARN -- : VSP9K/host-1-test.com status no_connection, retries exhausted, giving up

- net-ssh version
net-ssh-5.1.0

- Ruby version
ruby 2.5.1p57

-OpenSSL version
OpenSSL 1.0.2n  7 Dec 2017

- system
Ubuntu 18.04

What is happenind here?

**Comment by mfazekas** [comment]
The switch receives some packet which he thinks is violating the protocol, so it sends disconnect to net-ssh with messsage protocol error: rcvd type 0 (2).

Not sure if it's a but in net-ssh or a bug in the switch.
