### ISSUE TITLE
EventLoop documentation / examples / tests?

### ISSUE THREAD

**Issue by kke** [net-ssh/net-ssh#667]
The only mention repository search finds for EventLoop is the file where it is defined.

![image](https://user-images.githubusercontent.com/224971/54616986-343dd600-4a69-11e9-8502-4c47e5cbefc9.png)

The inline documentation:

https://github.com/net-ssh/net-ssh/blob/1e47189698a7624a4f5986b69bc622f900ee664f/lib/net/ssh/connection/event_loop.rb#L4-L11

This is the SingleSessionEventLoop that normally gets used:

https://github.com/net-ssh/net-ssh/blob/1e47189698a7624a4f5986b69bc622f900ee664f/lib/net/ssh/connection/event_loop.rb#L89-L90

How does a multi session event loop work and when should it be used?

**Comment by mfazekas** [comment]
@kke there was a server project - maybe the branch is https://github.com/net-ssh/net-ssh/tree/server_side, as i recall EventLoop was developed for that.

The work on EventLoop was not finished a lot of net-ssh has sync functions that should be rewritten to be async  with eventLoop so multiple sessions could work. See next_message on session for example - https://github.com/net-ssh/net-ssh/blob/master/lib/net/ssh/transport/session.rb#L174

There is no documentation and it's an implementation detail for now.
