### ISSUE TITLE
on_data doesn't receive the STDOUT util  multiple send_data

### ISSUE THREAD

**Issue by KINGSABRI** [net-ssh/net-ssh#676]
### Expected behavior
I want to build a simple SSH client where I request pty and shell channel. 
The expected behavior is to keep the session and channel open while I send commands to executed and receive stdout data instantly.

When I send command by (`channel.send_data`), the channel should send me back the result of that command by (`channel.on_data`). 

### Actual behavior
The main issue here is that I have to send multiple data (eg. `\n`) to eventually receive the expected stdout (command's result) I was waiting for.

### System configuration
- net-ssh version: 5.2.0
- Ruby version: 2.5.1p57

### Example App
```ruby
require 'net/ssh'

Net::SSH.start(hostname, username, :password => password) do |session|
  session.open_channel do |channel|
    channel.request_pty
    channel.send_channel_request("shell")
    channel.on_data do |_ch, data|
      print data
      cmd = gets
      channel.send_data("#{cmd}")
    end
  end
  session.loop
end
```

**Comment by stillhart** [comment]
I recommend to have a look at my gem https://github.com/swisscom/net-ssh-cli/blob/master/lib/net/ssh/cli.rb#L279

You probably get each char as it's own "data". So your `send_data` might get called for each char. Therefore you should process till a certain point, a soft timeout or a regex which matches the prompt. And then continue with the next command. 

Also have a look at https://github.com/net-ssh/net-ssh/blob/master/lib/net/ssh/connection/channel.rb#L338

```
        # Registers a callback to be invoked when data packets are received by the
        # channel. The callback is called with the channel as the first argument,
        # and the data as the second.
        #
        #   channel.on_data do |ch, data|
        #     puts "got data: #{data.inspect}"
        #   end
        #
        # Data received this way is typically the data written by the remote
        # process to its +stdout+ stream.
```

**Comment by KINGSABRI** [comment]
@stillhart I didn't know about the `net-ssh-cli` this is exactly what I needed a long time ago!.

thank you!
