### ISSUE TITLE
Is it possible to detect which auth methods an SSH server will accept without actually connecting?

### ISSUE THREAD

**Issue by Rylon** [net-ssh/net-ssh#683]
Hi,

Sorry if this isn't the right place to ask, but I was wondering if it is possible to detect which auth_methods an SSHD server is actually configured to allow? My use case is wanting to programmatically go through a list of hosts and detect if any of them are configured to allow password-based auth.

Thanks for your time!
Ryan

**Comment by fwininger** [comment]
No, it's not possible with this gem !

You can lock the auth methods with someting like that : 

```ruby
Net::SSH.start('localhost', 'test', auth_methods: %w[password])
> raise Net::SSH::AuthenticationFailed (Authentication failed for user test@localhost)
```
You got the same error for a wrong password or if the server don't accept the method.

For this kind of check, I suggest you to use Nmap NSE : https://nmap.org/nsedoc/scripts/ssh-auth-methods.html

@mfazekas : you can close this issue.

**Comment by Rylon** [comment]
Ok thanks for the suggestion 👍
