### ISSUE TITLE
Modernize Openssl prerequirement

### ISSUE THREAD

**Issue by fwininger** [net-ssh/net-ssh#695]
### Description

We have some piece of old code like this : 

```
if defined?(OpenSSL::Digest::SHA256)
  @digester = OpenSSL::Digest::SHA256
end
```

but other file use directly : 

```
def digester
  OpenSSL::Digest::SHA256
end
```

could it be possible to add a clear OpenSSL requirement to allow to clean code and make it more robust ?

I propose to add a prerequirement for OpenSSL 1.0.1 release in 2012.

### Expected behavior

- OpenSSL 1.0.0 [29 Mar 2010] introduce SHA2 (SHA256/SHA512)
- OpenSSL 1.0.1 [14 Mar 2012] introduce NIST-P224, NIST-P256, NIST-P521

### Actual behavior

In the readme we speak about : OpenSSL 0.9.8g 19 Oct 2007.

### Reference

https://www.openssl.org/news/changelog.html

**Comment by fwininger** [comment]
@mfazekas what do you think about support only OpenSSL > 1.0.1 ?

Can I open a PR that enhance the code with this prerequirement ?

**Comment by fwininger** [comment]
I have test with jruby 9.1 (ruby 2.3 compatible), OpenSSL::PKey::EC is defined. 

```sh
$ docker run -it jruby:9.1
irb(main):001:0> require 'openssl'
=> true
irb(main):002:0> OpenSSL::PKey::EC
=> OpenSSL::PKey::EC
```

https://github.com/jruby/jruby/wiki/Roadmap

**Comment by mfazekas** [comment]
I'm fine with OpenSSL > 1.0.1

**Comment by fwininger** [comment]
I have check aes-256-ctr is also introduice in OpenSSL 1.0.1.

https://security.stackexchange.com/questions/81243/openssl-with-aes-256-ctr-cipher/81308

I have try with Centos 6 / OpenSSL 1.0.1e 11 Feb 2013.

**Comment by fwininger** [comment]
@mfazekas this issue can be close after #701 and #703.
