### ISSUE TITLE
Feature request: add a new ssh option `set_env`, in addition to `send_env`

### ISSUE THREAD

**Issue by uzxmx** [net-ssh/net-ssh#725]
### Expected behavior

Currently, this gem only supports forwarding environment variables in ENV class. In a process lifecycle, when we want to start multiple ssh sessions concurrently, each with different value for a same environment variable name, `send_env` will not help.

I'm using Capistrano to deploy rails application to servers that's behind a bastion server, and I need to pass server name and other information as ssh environment variable to bastion server to select which server. For `config/deploy/production.rb`,

```
ENV['AssetName'] = 'server1'
ENV['SystemUserName'] = 'jenkins'
server '192.168.1.2', user: 'jenkins', ssh_options: { send_env: ['AssetName', 'SystemUserName'], keys: File.expand_path('~/.ssh/jenkins.pem') }

# Here I cannot deploy to more than one server concurrently, because of `send_env` limitation.
# ENV['AssetName'] = 'server2'
# ENV['SystemUserName'] = 'jenkins'
# server '192.168.1.2', user: 'jenkins', ssh_options: { send_env: ['AssetName', 'SystemUserName'], keys: File.expand_path('~/.ssh/jenkins.pem') }
```

Capistrano depends on sshkit which depends on this gem. Of course I can make suggestion to sshkit team, but I think sshkit just passes ssh_options to `Net::SSH.start`. So maybe it make more senses to suggest such change in this gem.

I suggest adding a new option `set_env`, the usage is like this:

```
Net::SSH.start('host', 'user', set_env: { AssetName: 'server1', SystemUserName: 'jenkins' })
Net::SSH.start('host', 'user', set_env: { AssetName: 'server2', SystemUserName: 'jenkins' })
```

It makes sense that `send_env` and `set_env` can both exist. `send_env` specifies which names from ENV you want to expose, and `set_env` specifies which pairs of environment name and value you want to expose. And for a same name, `set_env` will win against `send_env`.

I know that we can use `Net::SSH::Connection::Channel#env` to add environment variables, but it will be more straightforward to pass a hash of environment variables as an option of ssh. It will also match more with what linux command ssh supports: `ssh -o "SetEnv=AssetName=server1 SystemUserName=jenkins"`

What do you think of this? If you think this is a good idea, I can make a PR to add such feature.

**Comment by mfazekas** [comment]
I'm fine with such a feature. I'm not sure about naming. I understand your rationale for `set_env` but, without all the context the difference between `set_env` and `send_env` can be confusing. An alternative solution would be for `send_env` to accept a key value pair as well.
```ruby
send_env: ['env1', 'env2', ['env3', 'env3_value'], /env4.+/]
```

**Comment by uzxmx** [comment]
Hi @mfazekas , sorry for so long delay. Because of large of company work, I could not respond.  

I'm also fine with your alternative solution. But about the naming, it's based on the [release note of OpenSSH 7.8](https://www.openssh.com/txt/release-7.8). If you Ctrl-F and type `SetEnv`, you will find some information. OpenSSH 7.8 adds `SetEnv` option. I see lots of options in [lib/net/ssh.rb](https://github.com/net-ssh/net-ssh/blob/54476fa1e88a046014fa986792dbf2c65c5f17db/lib/net/ssh.rb#L65) that are converted to snakecase from camelcase of OpenSSH options. Isn't it better to add another option `set_env` from `SetEnv`?

**Comment by mfazekas** [comment]
@uzxmx sorry i overlooked that SetEnv is an existing convention in OpenSSH and it's config files. 

Sure `set_env` is the proper name in `net-ssh`
