### ISSUE TITLE
Add command hook to retrieve ssh host key

### ISSUE THREAD

**Issue by logicminds** [net-ssh/net-ssh#732]
### Expected behavior

I use an alternative ssh client that provides centralized management of ssh host keys and authorization.  Due to the central management feature of my ssh client, the ssh client does not write public host keys to the known hosts file and instead runs a command to consult a database of known hosts to verify the remote host during the ssh connection process.    I expect Net::SSH to be able to validate the remote host key with something other than a known hosts file.   Having the ability to specify a command to run to produce the remote host key would be ideal.  

### Actual behavior

Net::SSH fails and cannot verify the remote host key.  The only workaround is to obtain the ssh host key by other means and write to the local known_hosts file. However, this process does not scale and is a manual process. 

### System configuration

- net-ssh any
- Ruby 2.5

### Example App

This is a bit difficult as you would have to be in my environment with the proprietary and centralized ssh management tool.  

You can use this as stating point:

```ruby
gem 'net-ssh', '= 4.0.0.beta3'
require 'net/ssh'
puts Net::SSH::Version::CURRENT

@host = 'localhost'
@user = ENV['USER']
Net::SSH.start(@host, @user) do |ssh|
  puts ssh.exec!('echo "hello"')
end
```

**Comment by mfazekas** [comment]
#308 should allow you to implement custom known hosts logic. See the `:known_hosts` options
