### ISSUE TITLE
net-ssh 6.0.0beta raises exception during parse of known hosts

### ISSUE THREAD

**Issue by amvasilyev** [net-ssh/net-ssh#737]
### Expected behavior

The library should be able to initiate SSH connection with the remote host.

### Actual behavior

During the known hosts parse the exception is thrown:
```
ARGS="HOST_NAME", EXCEPTION=NoMethodError: undefined method `start_with?' for nil:NilClass
/tmp/.mount_mdbci3hl6sh/usr/lib/ruby/gems/2.6.0/gems/net-ssh-6.0.0.beta1/lib/net/ssh/known_hosts.rb:134:in `block (2 levels) in keys_for'
/tmp/.mount_mdbci3hl6sh/usr/lib/ruby/gems/2.6.0/gems/net-ssh-6.0.0.beta1/lib/net/ssh/known_hosts.rb:132:in `each_line'
```
### System configuration

- net-ssh version 6.0.0.beta1
- Ruby version 2.6.5

### Issue reason

There is an error in [`lib/net/ssh/known_hosts.rb#L134`](
https://github.com/net-ssh/net-ssh/blob/a2c486ccc3d87c1c69b8ed69d611e6083ad5626b/lib/net/ssh/known_hosts.rb#L134):
```ruby
next unless hosts || hosts.start_with?('#')
```
If `hosts` variable on this line is falsy, then the execution of the code will continue past `||`. The Ruby will need to check that the expression after `||` is falsy too.

The `nil` is falsy, therefore the error arises.

Unfortunately I do not have an example of the known hosts file that will ease the debug of the statement.

Possible solution: change `||` to `&&` on the line.

**Comment by mfazekas** [comment]
Thanks i was able to reproduce by adding  blank line to `known_hosts` then running this:

```ruby
gem 'net-ssh', '= 6.0.0.beta2'
require 'net/ssh'
puts Net::SSH::Version::CURRENT

Net::SSH.start('localhost', ENV['USER']) do |ssh|
  puts ssh.exec!('echo "hello"')
end
```
