### ISSUE TITLE
Gem::Security::Exception during high-security install - "no digests provided (probable bug)"

### ISSUE THREAD

**Issue by wangthony** [net-ssh/net-ssh#738]
### Expected behavior

Wanted to install the gem with high security, as per https://github.com/net-ssh/net-ssh#install

### Actual behavior

```
$ curl -O https://raw.githubusercontent.com/net-ssh/net-ssh/master/net-ssh-public_cert.pem
$ gem cert --add net-ssh-public_cert.pem
Added '/CN=netssh/DC=solutious/DC=com'
$ gem install net-ssh -P HighSecurity
ERROR:  While executing gem ... (Gem::Security::Exception)
    no digests provided (probable bug)
```

### System configuration

- net-ssh version: 5.2.0
- Ruby version: ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin18]

### Example App

Didn't get that far :)

**Comment by mfazekas** [comment]
The 6.0.0.beta2 release seems to be signed. Not sure what's the issue with 5.2.0

**Comment by wangthony** [comment]
Ok, I'll use that version, then. Thanks!
