### ISSUE TITLE
Invalid kex algorithms specified by net-ssh

### ISSUE THREAD

**Issue by aspyatkin** [net-ssh/net-ssh#740]
### Expected behavior
net-ssh should connect to hosts which support `curve25519-sha256@libssh.org` kex algorithm.

### Actual behavior
net-ssh fails during kex negotiation

```
ERROR: Train::Transports::SSHFailed: SSH command failed (could not settle on kex algorithm
       Server kex preferences: curve25519-sha256@libssh.org,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,diffie-hellman-group16-sha512
       Client kex preferences: curve25519-sha256,curve22519-sha256@libssh.org,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1)
```

### System configuration
net-ssh 6.0.0.beta1
ruby 2.6.0

### Example App
```ruby
gem 'net-ssh', '= 6.0.0.beta1'
require 'net/ssh'
puts Net::SSH::Version::CURRENT

@host = '1.2.3.4'
@user = ENV['USER']
Net::SSH.start(@host, @user) do |ssh|
  puts ssh.exec!('echo "hello"')
end
```

Most likely is caused by a typo [here](https://github.com/net-ssh/net-ssh/blob/master/lib/net/ssh/transport/algorithms.rb#L61). It must be `curve25519`, not `curve22519` instead.

**Comment by mfazekas** [comment]
@aspyatkin  thanks for the bugreport and PR.

You might be able to work around by

```
Net::SSH::Transport::Algorithms::DEFAULT_ALGORITHMS[:kex].unshift("curve25519-sha256@libssh.org")
```
