### ISSUE TITLE
Etc.getlogin vs Etc.getpwuid.name ?

### ISSUE THREAD

**Issue by noda50** [net-ssh/net-ssh#749]
### Expected behavior

[on linux]
Suppose that we login as userA, and `su` (switch-user) to userB.
When we call `Net::SSH.start("hostname")` without username,
it try to ssh-login using "userB".
(This is default behavior of ssh itself.)

### Actual behavior

`Net::SSH.start` try to ssh-login using "userA".

### Detail

Currently, `Net::SSH.start()` uses `Etc.getlogin()` when no username is specified.
`Etc.getlogin()` retrieves the original login name before `su`.
But, ssh's default behavior is the username of the current UID, whch can be
retrieved by `Etc.getpwuid.name()`.

For the consistency with ssh's behavior, `Net::SSH` also use `Etc.getpwuid.name()`
to get the default username.

### System configuration

- net-ssh version: 5.2.0
- Ruby version: 2.6.5

### Example App

ssh's behavior as follows:
```
login: userA
userA@hostX:~$ su userB
userB@hostX:/home/userA$ ssh hostY
userB@hostY:~$ whoami
userB
```

Net::SSH's behavior as follows:
```
login: userA
userA@hostX:~$ su userB
userB@hostX:/home/userA$ irb
irb(main):> require 'net/ssh'
irb(main):> Net::SSH.start("hostY") do |ssh| ssh.exec! "whoami" end
=> "userA"
```

**Comment by mfazekas** [comment]
@noda50 thanks for the report seems to be a valid issue, pls submit a PR!

**Comment by noda50** [comment]
I do not permission to push my changes.
So, I post a patch to fix this issue.


[patch-for-issue-749.diff.txt](https://github.com/net-ssh/net-ssh/files/4562939/patch-for-issue-749.diff.txt)

**Comment by mfazekas** [comment]
@noda50 Thanks for the patch, you do not have permission to push your changes, but you should be able to open a pull request. 

Create a for of this repo, add your changes to the forked repo, then you should be able to open a pull request from github web ui.

https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

**Comment by noda50** [comment]
Thanks for the help.
I did it.
