### ISSUE TITLE
Question: Defining a source port when establishing connection

### ISSUE THREAD

**Issue by Blazy7** [net-ssh/net-ssh#752]
Hi, I am working on integration where the provider is using a static firewall configuration where we must provide a source port which then will be whitelisted.

I have reviewed the supported options and as a possibility, I have found that I can make a specific configuration in OpenSSH config files(i can see they are loaded by default [source](https://www.rubydoc.info/github/net-ssh/net-ssh/Net%2FSSH.start)) for provider IP's where I can set source port but
I don't like this approach, because then the logic will be outside our app which will be confusing for those working on the project after time. 

So are there any other options which I can use?

**Comment by mfazekas** [comment]
@Blazy7 what is that option?! I don't think net-ssh support setting the source port.

Looking at the code you should be able to use the `proxy:` option. 

https://github.com/net-ssh/net-ssh/blob/3eb4a3e2729273343a2cef4ac3e0650fefec571c/lib/net/ssh/transport/session.rb#L67-L75

**Comment by Blazy7** [comment]
Thank you for your answer @mfazekas.
Actually my statement was not 100% correct I was looking at `:config` where it says it loads `~/.ssh/config, /etc/ssh_config` where I can put my IP specific configuration.

**Comment by Blazy7** [comment]
Just as a followup I have achieved my goal by using the [Net::SSH::Proxy::Command](https://www.rubydoc.info/github/net-ssh/net-ssh/Net/SSH/Proxy/Command)

```ruby
proxy = Net::SSH::Proxy::Command.new('nc -p <STATIC-PORT> %h %p')
Net::SSH.start('host', 'user', proxy: proxy) do |ssh|
  ...
end
```
