### ISSUE TITLE
How to read process exit status?

### ISSUE THREAD

**Issue by wmakley** [net-ssh/net-ssh#753]
### Expected behavior

I would like be able to get the exit status of an "exec" call.

### Actual behavior

The README doesn't have an example of this.

### System configuration

- net-ssh 5.2.0
- Ruby 2.5

### Example App

Just see the one in the README.

**Comment by mfazekas** [comment]
http://net-ssh.github.io/net-ssh/Net/SSH/Connection/Session.html#method-i-exec-21

**Comment by wmakley** [comment]
Thanks!
