### ISSUE TITLE
Not efficient to use with sidekiq?

### ISSUE THREAD

**Issue by altonj** [net-ssh/net-ssh#779]
RE: https://github.com/mperham/sidekiq/issues/4625

I am using Sidekiq to run backgrounded jobs, scheduled by Rails. However, in my sidekiq workers I am using net-ssh in many instances to run commands on remote Linux servers via SSH. When this is happening by multiple Sidekiq workers, it seems to cause an issue within Sidekiq that causes some of the workers to "hang". For example, if Worker1 starts, followed by Worker2, Worker1 will just hang until Worker2 completes, even if Worker1 runs once every minute for 2-3 seconds and doesn't depend on Worker2.

The author of Sidekiq doesn't seem to understand why this might be happening and suggested coming here, so I wanted to come here for help as well. Is net-ssh not a good thing to pair with Sidekiq workers?

**Comment by mfazekas** [comment]
@altonj MRI Ruby and net-ssh is not ideal for hundreds of concurrent connection via threads. But it should not be blocking, or we're not aware of such issue. 

Maybe your ssh server is limiting the number of concurrent connections `MaxStartups`?

You can increase logging level of net-ssh, to undestand more.

**Comment by altonj** [comment]
Hey @mfazekas,

Thanks for your response. I don't have any limits on the SSH connections (only 3 were being established at the time of the issue). Since this is not an ideal situation altogether though, do you recommend just using the standard ssh command from within the image itself?

**Comment by mfazekas** [comment]
@alton I don't see why `net-ssh` wouldn't work for you for such a few concurrent connections, but if you can get standard `ssh` work to you, that's probably more efficient, and more futureproof.

**Comment by altonj** [comment]
Hey @mfazekas,

Sounds great. Only problem with ssh is that it's a lot slower as I have to tear down and build a new SSH connection each time I want to run a command, whereas with `net-ssh` I can run the command 2-3 times back to back and get its output before the standard `ssh` command even runs once.

Sorry for my lack of knowledge here, but it shouldn't be a problem that a Sidekiq worker would pass an Net::SSH::Session object to another class for using the object's `exec` function would it? Wondering if that could be a potential reason for Sidekiq to sorta hang.

**Comment by mfazekas** [comment]
@altonj can you share code?! Not sure how you are using `Net::SSH::Session` i'd say you'd not  want to share it accross workers, but i'm not sure if that's even possible.

**Comment by altonj** [comment]
Hi @mfazekas,

Sorry for the delay. I've been investigating this like crazy. I've provided some additional output in the sidekiq issue here: https://github.com/mperham/sidekiq/issues/4625

Basically, I've been trying to evaluate whether or not I should just simply use the `ssh` command on Linux or use the `net-ssh` gem as it's a _lot_ faster to send commands through an open channel rather than rebuilding a new one every single command, especially across possibly 50-60 commands per task.

Here's a great example of what I was working with:

```
# app/workers/internal_health_check_worker.rb
class InternalHealthCheckWorker
    include Sidekiq::Worker
    sidekiq_options queue: Rails.env.to_sym
    
    def perform(options)
        @cmd = SSHCommand.new(agent)
        @options = Options.new(options)
        
        internal_health_check
        
        @cmd.terminate_ssh
    end
    
    def internal_health_check
        command = "./bash_command.sh"
        results = @cmd.execute(command)
        sleep 10
        
        @options.wait_until_completion("/root/healthcheck_done.txt")
    end
end
```

This worker basically runs a command on a remote system that essentially launches a variety of health checks across multiple systems. It waits until it's complete. Sometimes it can take 1 minute, or take 20, or an hour. Just depends on a variety of other tasks on the remote system.

The SSHCommand class looks as follows:

```
class SSHCommand
    def initialize(agent)
        @key = agent.key_file_path
        @port = agent.port
        @ip = agent.ip
        @ssh = establish_ssh
        @session_name = "test"
	end

	def establish_ssh
		ssh = Net::SSH.start(
			@ip, 'root',
			:host_key => 'ssh-rsa',
			:encryption => 'aes256-ctr',
			:keys => [@key],
			:compression => "zlib@openssh.com",
			:port => @port
		)
		return ssh
	end

	def terminate_ssh
		@ssh.close
	end

    def execute(window, command, wait=false, done_file=nil)
        ... some other irrelevant code ...
		results = run_cmd(command)
		if results.include? "no matches found"
			results = ""
		end
		return results
	end
	def run_cmd(cmd)
		results = @ssh.exec! cmd
		return results
	end
end
```

As far as `wait_until_completion` method of the `Options` class, that looks like this:

```
def wait_until_completion(file_name="")
		while true
			results = @cmd.execute(0, "ls #{file_name} 2>/dev/null")
			file_exists = (!results.empty? and !results.include? "No such file")
			if !file_name.empty?
				if file_exists
					@cmd.execute(0, "rm #{file_name}")
					break
				end
			end
			sleep 5
		end
end
```

So as you can see, it's a little bit chained in multiple ways. I run a command over an SSH channel, wait until the command is complete, and then I finish. However, while it's _waiting_ to complete, sometimes other jobs will queue up into the sidekiq worker and just simply hang, and it's only while one of these jobs are running.

In case you may be wondering why I'm not just simply letting the output of the `execute` command determine if it's finished or not -- it's because I'm also leveraging tmux on the remote server, so pushing commands to a tmux session will finish the `execute` method immediately, so I have to constantly query the remote device for a file's presence to determine if it's truly finished or not.

**Comment by altonj** [comment]
Confirmed that this issue was due to code reloading being enabled.
