### ISSUE TITLE
Suggestion for handling encryption algorithm mismatch.

### ISSUE THREAD

**Issue by fakefarm** [net-ssh/net-ssh#780]
👋 Hello there 
great set of code tools you've got here! 👏 👏

I arrived here by attempting to use `Net::SFTP`. The `SFTP` server I'm attempting to connect to uses and unsupported encryption since it appears [these are the only options](https://github.com/net-ssh/net-ssh/blob/b38f7ba0bf7aa83e49c2e8e17444804b1fce4bcc/lib/net/ssh/transport/algorithms.rb#L46).  Any suggestions on what it would take to incorporate a `3des-cbc,aes256-cbc,aes128-cbc` encryption? I would be willing to attempt a PR if that's of interest to the project? If so, I can commit to getting an update to `Net::SFTP` as well since that's my use case.

```
could not settle on encryption_client algorithm
       Server encryption_client preferences: 3des-cbc,aes256-cbc,aes128-cbc
       Client encryption_client preferences: aes256-ctr,aes192-ctr,aes128-ctr
```

**Comment by fakefarm** [comment]
I'm currently tracking down how `aes256-ctr` is implemented so that I can attempt to support `3des-cbc`

**Comment by fwininger** [comment]
Hello, you can use unsecure algs by adding the option `append_all_supported_algorithms: true` as said in the Readme.md.

```ruby
Net::SFTP.start('host', 'username', { password: 'password', append_all_supported_algorithms: true}) 
```

**Comment by fakefarm** [comment]
That fixed it, thank you! I'm sorry I missed that line in the readme. I see it now that you pointed it out.
I don't normally dwell in this part of the underworld, so I am not well versed in all the lingo.

Just an idea, what if there was a trouble shooting section? Something like

## Troubleshooting

### could not settle on encryption_client algorithm

```
could not settle on encryption_client algorithm
       Server encryption_client preferences: 3des-cbc,aes256-cbc,aes128-cbc
       Client encryption_client preferences: aes256-ctr,aes192-ctr,aes128-ctr
```

If you have no control over the Server's encryption options, try connecting by adding `append_all_supported_algorithms: true`, like so: 

```
Net::SFTP.start('host', 'username', { password: 'password', append_all_supported_algorithms: true}) 
```
