### ISSUE TITLE
Banner agreement prompt before password working implementation

### ISSUE THREAD

**Issue by deligatedgeek** [net-ssh/net-ssh#804]
### Expected behavior

It's becoming common for devices to have a legal banner and prompt for agreement between the username and password. SSH standard can handle this using message type 60 and 61 to request the agreement and again to provide the password.

My initially googling showed a lot of people getting stuck due to this new requirement.

I've added some code to handle this by checking the prompt sent in the type 60 contains "Password:", providing the password if it does or responding with a "yes".  I then added configuration for a regex to match password prompt and the response to banner to allow for device and password prompt variations.

I created a google sheet and added columns of debug output from openssh cli manual authentication, oxidized, and a script I wrote contain code snippets from Oxidized.  After removing the chaff and lining up the different ssh message type numbers across the different outputs I discovered that the session closes if it takes longer than 20.5 seconds, but I'm sure what closes the session.  In Oxidized I forced keyboard-interactive which save 3 seconds of negotiation and authentication works.

Im using Oxidized for device config backup, this uses net-ssh v5, so I initially branched v5.2.0 and created v5.3.0.  Oxidized is running fine with this and backing up devices with or without banner.

I have submitted PR [#802](https://github.com/net-ssh/net-ssh/pull/802) which is failing some tests with the changes but having trouble setting up an environment to run rake test successfully on MACOS (notmy choice). I'm thinking to create an environment in using an Ubuntu docker container unless anyone has a better suggestion.

Once the PR is accepted I would appreciate a back port to v5 maybe as v5.3.0 so others can obtain the code in a signed gem from a known source.

Some help or recommended reading for Ruby testing would be appreciated.  I have been programming for over 25 years but only had 12 days with Ruby

### Actual behavior

Authentication fails on banner.

### System configuration

- net-ssh v5.2.0
- Ruby version 2.5.5p157

### Example App

[Oxidized](https://github.com/ytti/oxidized)

**Comment by mfazekas** [comment]
Hey @deligatedgeek thanks much the the issue and PR! 👍 

As noted on PR we're already supporting custom prompts so I think it's best handled there. (see `password_prompt`).
As for v5 back port that is extremely unlikely.  I have very limited time, and I'm currently strugling releasing a new 6* version, mainly because of the travis => gh-actions migration.


> I have submitted PR #802 which is failing some tests with the changes but having trouble setting up an environment to run rake test successfully on MACOS (notmy choice). I


Linux VM can be used to run tests.  See https://github.com/net-ssh/net-ssh/blob/master/test/README.txt for instructions:

```sh
brew install ansible ; ansible-galaxy install rvm.ruby ; vagrant up ; vagrant ssh
cd net-ssh ; rake test
```

**Comment by deligatedgeek** [comment]
Hi @mfazekas, 

Custom prompt builds a prompt for user interaction, I've been down that rabbit hole.

Imagine this as being prompted twice in the same authentication, with no user interaction. A banner is sent by the device followed by a USERAUTH_INFO_REQUEST (60) net-ssh responds with the USERAUTH_INFO_RESPONSE (61) containing the password, which fails.  If the USERAUTH_INFO_RESPONSE (61) contains "yes", another USERAUTH_INFO_REQUEST (60) is sent for the password, which then fails.  

The current implementation doesn't handle this particular requirement.

**Comment by mfazekas** [comment]
> Custom prompt builds a prompt for user interaction, I've been down that rabbit hole.

Even if `Prompt` was not designed for it I don't see why you couldn't make a Prompt subclass that handles this case. https://github.com/net-ssh/net-ssh/blob/master/lib/net/ssh/prompt.rb

**Comment by deligatedgeek** [comment]
There is no user interaction!!  How can I use something designed to request information from a user on the console, to talk to another machine?  The changes to code would be much larger and it's not good software design.

I have added to the code that responds to user information requests for password and added to allow it to also respond to other requests.

**Comment by mfazekas** [comment]
> There is no user interaction!! How can I use something designed to request information from a user on the console, to talk to another machine? The changes to code would be much larger and it's not good software design.
> 

The default `Prompt` implementation uses console, but I suggested to provide your own `Prompt` implementation. It doesn't have to use the console.

I'm closing the issue as I believe `password_prompt` option allows you to implement it without changing net-ssh.
