### ISSUE TITLE
Documentation site is no longer available (404)

### ISSUE THREAD

**Issue by autonomousapps** [net-ssh/net-ssh#810]
### Expected behavior

I should be able to go to https://net-ssh.github.com/net-ssh

### Actual behavior

It 404s.

### System configuration

Chrome.

### Example App

n/a

**Comment by j1wilmot** [comment]
Some time ago Github moved repo pages to `github.io` for security reasons. The 404 page mentions that you can visit https://net-ssh.github.io/net-ssh instead.

**Comment by fwininger** [comment]
close with #813
