### ISSUE TITLE
Don't ship the rubocop todo config in the gem

### ISSUE THREAD

**Issue by tas50** [net-ssh/net-ssh#814]
### Expected behavior

net-ssh's rubocop config should not impact other projects

### Actual behavior

RuboCop gets fancy and ends up reading the config from net-ssh and failing on the deprecated cop names

### System configuration

- net-ssh 6l1
- 2.7
- GitHub Acxtions

See an example of this file impacting other test jobs here:
https://github.com/chef/chef/runs/2634208291?check_suite_focus=true#step:5:9

**Comment by fwininger** [comment]
Thanks for reporting this issue. I will update the rubocop_todo.yml.

Otherwise we can remove the .rubocop.yml from the repo. I think the best way to solve our issue is to ignore the vendor folder on your tests suites.
