### ISSUE TITLE
Configure support for gcm algorithms?

### ISSUE THREAD

**Issue by bf4** [net-ssh/net-ssh#834]
Following #193 

I'd expect these to work now, right? e.g. `OpenSSL::OPENSSL_VERSION #=> "OpenSSL 1.1.1j  16 Feb 2021"` and `OpenSSL::Cipher::AES256.ciphers.grep(/gcm/) #=> ["aes-128-gcm", "aes-192-gcm", "aes-256-gcm", "aria-128-gcm", "aria-192-gcm", "aria-256-gcm"]`

**Comment by fwininger** [comment]
@bf4 net-ssh don't support aes-256-gcm now. I'm also interested to have the support. PR are welcome.

**Comment by fwininger** [comment]
In fact, the challenge is not to implement AES-256-GCM but supporting AEAD method. This method merge the cipher and the hmac authentication.

**Comment by bf4** [comment]
So, the issue isn't just to (practically) revert #193 but something in addition?

**Comment by flux-benj** [comment]
@fwininger @mfazekas seeking reivew on #946

**Comment by flux-benj** [comment]
Thanks for merging, possible to get this tagged in the current major version?
