### ISSUE TITLE
pubkey auth doesn't authenticate using net-ssh after upgrading openssh from 8.7 to 8.8

### ISSUE THREAD

**Issue by simplelikecode** [net-ssh/net-ssh#836]
### Expected behavior

Commands execute.

### Actual behavior

After upgrading to openssh 8.8, `net-ssh` prompts for a password, if ssh is configured to not accept passwords, then you get a `Net::SSH::AuthenticationFailed` error.

`ssh`-ing normally has no issue, auth failure only happens when using `net-ssh`

### System configuration

client: 
- ruby 3.0.0
- net-ssh 6.1.0

server:
- Linode arch base image
- libssh2 1.9.0-3
- works as expected with openssh 8.7p1-1
- auth failure using openssh-8.8p1-1

### Example App

Nothing special with the script:

```ruby
require 'net/ssh'

Net::SSH.start(<ip addr>, 'root') do |ssh|
  ssh.exec!('ls -lah')
end
```

Upgrading openssh caused the issue:

```
[root@localhost ~]# pacman -Q | grep ssh
libssh2 1.9.0-3
openssh 8.7p1-1
[root@localhost ~]# pacman -S openssh
resolving dependencies...
looking for conflicting packages...

Packages (1) openssh-8.8p1-1

Total Download Size:   0.99 MiB
Total Installed Size:  5.90 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n] 
...
```

Still able to ssh in normally though:

```
> ssh root@<server ip>
Last login: Sat Oct  2 20:57:17 2021 from <client ip>
```

### Other

May have something to do with this: https://dev.to/cloudx/why-openssh-8-8-cannot-find-a-host-key-type-if-ssh-rsa-is-provided-49i

Temporary fix: downgrade to openssh 8.7

**Comment by fwininger** [comment]
#838 close this issue
