### ISSUE TITLE
Upgrading to ruby 3.1 leads to "verify_signature" error

### ISSUE THREAD

**Issue by quantson** [net-ssh/net-ssh#847]
Hello,

I've originally opened this issue on net-sftp (https://github.com/net-ssh/net-sftp/issues/130), but realize it would probably be more appropriate here as I have the same issue using `Net::SFTP.start` or ` Net::SSH.start`.

We're using the net-sftp gem to connect to various SFTP servers hosted by our customers. We recently upgraded to ruby 3.1 from 3.0.2 and are now receiving the below exception on a small sample of our outgoing connections (3 out of approximatively 20 different servers).

```
/usr/local/bundle/gems/net-ssh-6.1.0/lib/net/ssh/transport/kex/abstract.rb:101:in `verify_signature': could not verify server signature (Net::SSH::Exception)
```

I unfortunately don't know much about how those distant servers are set up.
I've tried to connect using the `append_all_supported_algorithms: true` in ssh options but it didn't change anything.

**Prior to update**
ruby version: 3.0.2
net-ssh version: 6.1.0
net-sftp version: 3.0.0

**After update**
ruby version: 3.1.0
net-ssh version: 6.1.0
net-sftp version: 3.0.0

Here's the verbose log of the ssh connection attempt. I can provide the host of a broken server upon request.
```
D, [2022-01-17T18:17:20.809841 #685] DEBUG -- net.ssh.transport.session[35d7c]: establishing connection to xx.xxx.xxx.xxx:2221
D, [2022-01-17T18:17:20.821827 #685] DEBUG -- net.ssh.transport.session[35d7c]: connection established
I, [2022-01-17T18:17:20.822213 #685]  INFO -- net.ssh.transport.server_version[35d90]: negotiating protocol version
D, [2022-01-17T18:17:20.822409 #685] DEBUG -- net.ssh.transport.server_version[35d90]: local is `SSH-2.0-Ruby/Net::SSH_6.1.0 x86_64-linux'
D, [2022-01-17T18:17:20.855658 #685] DEBUG -- net.ssh.transport.server_version[35d90]: remote is `SSH-2.0-mod_sftp'
I, [2022-01-17T18:17:20.856676 #685]  INFO -- net.ssh.transport.algorithms[35da4]: sending KEXINIT
D, [2022-01-17T18:17:20.856956 #685] DEBUG -- socket[35db8]: queueing packet nr 0 type 20 len 796
D, [2022-01-17T18:17:20.857200 #685] DEBUG -- socket[35db8]: sent 800 bytes
D, [2022-01-17T18:17:20.857583 #685] DEBUG -- socket[35db8]: read 288 bytes
D, [2022-01-17T18:17:20.857915 #685] DEBUG -- socket[35db8]: received packet nr 0 type 20 len 284
I, [2022-01-17T18:17:20.858096 #685]  INFO -- net.ssh.transport.algorithms[35da4]: got KEXINIT from server
I, [2022-01-17T18:17:20.858242 #685]  INFO -- net.ssh.transport.algorithms[35da4]: negotiating algorithms
D, [2022-01-17T18:17:20.859040 #685] DEBUG -- net.ssh.transport.algorithms[35da4]: negotiated:
* kex: diffie-hellman-group-exchange-sha256
* host_key: ssh-rsa
* encryption_server: aes256-ctr
* encryption_client: aes256-ctr
* hmac_client: hmac-sha2-512
* hmac_server: hmac-sha2-512
* compression_client: none
* compression_server: none
* language_client: 
* language_server: 
D, [2022-01-17T18:17:20.859214 #685] DEBUG -- net.ssh.transport.algorithms[35da4]: exchanging keys
D, [2022-01-17T18:17:20.859593 #685] DEBUG -- socket[35db8]: queueing packet nr 1 type 34 len 20
D, [2022-01-17T18:17:20.859783 #685] DEBUG -- socket[35db8]: sent 24 bytes
D, [2022-01-17T18:17:21.090983 #685] DEBUG -- socket[35db8]: read 280 bytes
D, [2022-01-17T18:17:21.091320 #685] DEBUG -- socket[35db8]: received packet nr 1 type 31 len 276
D, [2022-01-17T18:17:21.101149 #685] DEBUG -- socket[35db8]: queueing packet nr 2 type 32 len 268
D, [2022-01-17T18:17:21.101546 #685] DEBUG -- socket[35db8]: sent 272 bytes
D, [2022-01-17T18:17:21.112042 #685] DEBUG -- socket[35db8]: read 848 bytes
D, [2022-01-17T18:17:21.112263 #685] DEBUG -- socket[35db8]: received packet nr 2 type 33 len 828
/usr/local/bundle/gems/net-ssh-6.1.0/lib/net/ssh/transport/kex/abstract.rb:101:in `verify_signature': could not verify server signature (Net::SSH::Exception)
```

**Comment by dentarg** [comment]
I've also seen this on one hosts, but haven't dug into what's causing it yet.

**Comment by AnotherJoSmith** [comment]
I ran tests locally using ruby 3.1, and got a handful of failures related to OpenSSL. Ruby 3.1 upgraded openssl to version 3.0.0, compared to 2.2.1 for ruby version 3.0.

It seems quite likely that there's a compatibility issue between the latest version of this gem and openssl 3.0.

When I manually downgrade the openssl version to 2.2.1, all the tests pass.

https://github.com/ruby/openssl/blob/v3.0.0/History.md#compatibility-notes

**Comment by quantson** [comment]
Thanks @AnotherJoSmith, I can confirm that manually installing openssl < 3.0 fixed the issue for us as well.

There's an issue opened on the openssl gem that seems to be the cause of those errors: https://github.com/ruby/openssl/issues/489

**Comment by fwininger** [comment]
I am investigating this issue.

**Comment by fwininger** [comment]
https://github.com/net-ssh/net-ssh/pull/857 solve this issue

**Comment by fwininger** [comment]
https://github.com/net-ssh/net-ssh/pull/865 add unit test for this issue.

**Comment by fwininger** [comment]
#864 close this issue
