### ISSUE TITLE
Update changelog for v7.0.0+ releases

### ISSUE THREAD

**Issue by edmorley** [net-ssh/net-ssh#870]
v7.0.0 and v7.0.1 have been released:
https://github.com/net-ssh/net-ssh/tags

However they are not listed in the changelog:
https://github.com/net-ssh/net-ssh/blob/v7.0.1/CHANGES.txt

**Comment by rylanb** [comment]
This would be nice, a bit hard to know what changed in a major version bump.

**Comment by tisba** [comment]
There are a ton of changes between 6.1.0 and 7.0.1, see https://github.com/net-ssh/net-ssh/compare/net-ssh:74919ef...net-ssh:dc18e79. A lot of the 175 commits do look like cleanup and tooling. But it's hard to tell what else changed and I'm not sure it makes sense to generate a changelog from commit log.

7.0.0 to 7.0.1 is just removing a `put`/debugging statement (https://github.com/net-ssh/net-ssh/pull/866): https://github.com/net-ssh/net-ssh/compare/net-ssh:a2b4cf1...net-ssh:dc18e79.

/cc @mfazekas

**Comment by swiknaba** [comment]
A major version change infers (potential) breaking changes. At least documenting those would be great.

I went through all pull requests in the posted git diff from 6.1.0 to 7.0.1. None of the descriptions mention any breakages (most PR descriptions are shockingly blank, though).

**Comment by mfazekas** [comment]
> A major version change infers (potential) breaking changes. At least documenting those would be great.
> I went through all pull requests in the posted git diff from 6.1.0 to 7.0.1. None of the descriptions mention any breakages (most PR descriptions are shockingly blank, though).

No breaking changes AFAIK, but in ruby almost any change is potentially breaking. Sorry I don't have much time to spend on `net-ssh` these days. It's safer to release new major releases, than to release a minor that might break something for someone, and the project has large install base.

Can you please point out an example pr, with no description, probably there was quite a few about infrastructure (GitHub actions, etc), but that should not be an issue. 

We welcome a PR, with a proper changelog. We have changelogs until 6.3.0.beta so this is the diff that have to be converted into changelog:
https://github.com/net-ssh/net-ssh/compare/v6.3.0.beta1...v7.0.1

**Comment by tisba** [comment]
Here we go: https://github.com/net-ssh/net-ssh/pull/884

I hope I captured everything that's relevant. There were a bunch of changes without a PR, so I tried to extract the important changes from commit messages and in part by reading the diff.

Let me know if I missed something of relevance.
