### ISSUE TITLE
Net::SSH.start with `set_env` gives error `undefined method `each' for "SECRET=XXXXXXX":String`

### ISSUE THREAD

**Issue by SecretShangri-La** [net-ssh/net-ssh#885]
### Expected behavior

I expect `Net::SSH.start(RHOSTS, USER, set_env: 'SECRET=XXXXXXXXXXXXXXX', password: PASS)` to start `each` with ssh SECRET included.

### Actual behavior

got error like below
```
`set_remote_env': undefined method `each' for "SECRET=XXXXXXXXXXXXXXX'":String (NoMethodError)
```

### System configuration

- net-ssh 7.0.1
- ruby 3.0.0

### Example App

```
# ssh server is `segfault.net` in login user `root` 
require 'net/ssh'

RHOSTS = 'de.segfault.net'
USER = 'root'
PASS = 'segfault'
SECRET = 'SECRET=XXXXXXXXXXXXXXX'

Net::SSH.start(RHOSTS, USER, set_env: SECRET, password: PASS) do |sf|
    pp sf.exec!("which ruby") 
end
```

**Comment by mfazekas** [comment]
You're passing a string not a hash. See the docs:

https://github.com/net-ssh/net-ssh/blob/0150d054f0cd0beacd4ba1000c6df6d8636a2c18/lib/net/ssh.rb#L178-L179
