### ISSUE TITLE
deploying to server with ed25519 genereated key fails

### ISSUE THREAD

**Issue by dvodvo** [net-ssh/net-ssh#903]
### What I did.

• made backup of rsa keys
• ssh-keygen -t ed25519 -C "my@EMAIL.com"
• added key to github and to VPS  via `ssh-copy-id deploy@server_ip`
• private key has appropriate timestamps, distinct from backed up rsa keys
• can push to git
• can ssh/mosh into VPS
• installed ruby 3.2.1 on VPS  (this was also attempted with a pristine image of Ubuntu 22.04)
• set rbenv local 3.2.1 in the application's directory
• ~/the_app$ ruby -v
ruby 3.2.1 (2023-02-08 revision 31819e82c8) [x86_64-linux]

### Expected behavior

Recognise key and allow deploy

### Actual behavior
```
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as deploy@server_ip: the given identity is known, but the private key could not be loaded: OpenSSL::PKey::PKeyError (rsa#set_key= is incompatible with OpenSSL 3.0)


Caused by:
Net::SSH::Authentication::KeyManagerError: the given identity is known, but the private key could not be loaded: OpenSSL::PKey::PKeyError (rsa#set_key= is incompatible with OpenSSL 3.0)
```

It appears when communicating with the VPS the old key is being manipulated on the VPS, not the newer one.

### System configuration

Mac OS 12.3 deploying to Ubuntu 22.04

ruby "3.2.1"
gem 'net-ssh', '~> 7.0', '>= 7.0.1'
gem 'ed25519', '~> 1.2', '>= 1.2.4'
gem 'bcrypt_pbkdf', '~> 1.1'
from Gemfile.lock:
capistrano-rbenv (2.2.0)

### Example App

I cannot reproduces the problem on the VPS, as there is no gemfile nor bundler existing in the app directory and thus the version of net-ssh is not present:

```
ruby
gem 'net-ssh'
/.rbenv/versions/3.2.1/lib/ruby/3.2.0/rubygems/dependency.rb:314:in `to_specs': Could not find 'net-ssh' (>= 0) among 86 total gem(s) (Gem::MissingSpecError)
```

On localhost, which runs the server with no apparent issues:
```
puts Net::SSH::Version::CURRENT
7.0.1
@host = 'localhost'
 @user = ENV['USER']
=> "deploy"
 Net::SSH.start(@host, @user) do |ssh|
  puts ssh.exec!('echo "hello"')
end
=> /Users/deploy/.rbenv/versions/3.2.1/lib/ruby/3.2.0/socket.rb:68:in `connect': Connection refused - connect(2) for 127.0.0.1:22 (Errno::ECONNREFUSED)
```

**Comment by mfazekas** [comment]
net-ssh 7.1.0 is now released, have you tested with that as well? #875 should have fixed this issue
