### ISSUE TITLE
Option to customize prompting

### ISSUE THREAD

**Issue by jheiss** [net-ssh/net-ssh#91]
The set of prompting options is hard-coded in Net::SSH::Prompt.  I would like to use a custom prompt module (that does caching), which is not possible currently without monkey patching Net::SSH.

On a related front (which perhaps should be a separate ticket) it would probably be useful to also just give users an option to simply disable prompting, similar to BatchMode=yes in the command line ssh.  In Net::SSH::Authentication::KeyManager#each_identity the call to load_identities has the ask_passphrase parameter hard-coded to true.

**Comment by mfazekas** [comment]
:non_interactive  should disable asking for questions. 
Should be straightforward to be able to pass a custom prompt function, we should also pass information that enables caching.

**Comment by mfazekas** [comment]
@jheiss Custom prompts including password cache can be implemented. There is an ask method to ask for a password, and there is also a success method to let you know that the password was used sucessfully. That's a good point to save passwords.
