### ISSUE TITLE
Net::SSH.start does not work with configs with IdentityAgent options

### ISSUE THREAD

**Issue by tosuke** [net-ssh/net-ssh#911]
### Expected behavior

SSH connects properly

### Actual behavior

```
/***/lib/ruby/gems/3.1.0/gems/net-ssh-7.2.0.beta1/lib/net/ssh.rb:225:in `start': invalid option(s): identity_agent (ArgumentError)
```

### System configuration

- net-ssh version
  - 7.2.0.beta1
- Ruby version
  - 3.1.4

### Example App

Please provide an example script that reproduces the problem. This will save maintainers time so they can spend it fixing your issues instead of trying to build a reproduction case from sparse instructions.

You can use this as stating point:

```ruby
gem 'net-ssh', '= 7.2.0.beta1'
rrequire "net/ssh"
puts Net::SSH::Version::CURRENT

@host = "localhost"
@user = "user"
@identity_agent = "/path/to/auth.sock"

Net::SSH.start(@host, @user, {
  :identity_agent => @identity_agent,
}) do |ssh|
  puts ssh.exec!('echo "hello"')
end
```

**Comment by mfazekas** [comment]
@tosuke we read `identity_agent` from config but we don't seems to allow it in options as Net::SSH. You should be able to use agent_socket_factory to work around this.

https://github.com/net-ssh/net-ssh/blob/576dbbd4b0fd6e30eccd8f9895cf8c8f6df129f0/lib/net/ssh.rb#L65-L77
