### ISSUE TITLE
Do we have a way to enable FIPS-only mode for net-ssh library

### ISSUE THREAD

**Issue by yweiy10** [net-ssh/net-ssh#913]
### Expected behavior

I have an application that depends on this and want to know if it's possible to set it in FIPS mode.

**Comment by mfazekas** [comment]
@yweiy10 do you face any issue, on FIPS system? We don't have a flag, but by default we might be FIPS compliant unless you enable insecure stuff.

**Comment by yweiy10** [comment]
I don't face any specific issues. My use case is to make my Jruby-based application to be FIPS-compliant. In that env, the openssl dependency is [JRuby-OpenSSL](https://github.com/jruby/jruby-openssl) which explicitly states that they are not FIP compliant and do not have plan to support. And we also dependent on net-ssh which in my understanding is one layer up from the JRuby-OpenSSL to handle the SSH connections. So I'm just wondering what would be the best way to upgrade our application to be FIPS compliant.

**Comment by mfazekas** [comment]
@yweiy10 so yes net-ssh uses OpenSSL, I assume that is in JRuby case that's JRuby-OpenSSL. But I have no knowledge of FIPS compliance, so I cannot help I'm afraid.
