### ISSUE TITLE
7.2.2 giving me error when using sshkit to remotely execute commands

### ISSUE THREAD

**Issue by jasonperrone** [net-ssh/net-ssh#943]
### Expected behavior

Properly execute commands on remote server

### Actual behavior

SSHKit::Runner::ExecuteError: Exception while executing as deploy@cstage: uninitialized constant SSHKit::Backend::Netssh::KnownHostsKeys::Base64 (SSHKit::Runner::ExecuteError)

### System configuration

- net-ssh version = 7.2.2
- Ruby version = 3.3.0

**Comment by jasonperrone** [comment]
Downgrading to 7.2.1 resolved problem.

Command I was trying to execute was just: mkdir -p /tmp

**Comment by mfazekas** [comment]
@jasonperrone thanks for the report let me yank the release and look into what's going on

**Comment by mfazekas** [comment]
Interesting looking at the changes we've just removed require 'bese64' usage from some places - see https://github.com/net-ssh/net-ssh/commit/6b7d21b88504b0938f0a17fbd2a248965af0d68d. It looks to me ssh-kit was piggybacking on our requires and they used Base64 without require, that causes the issue, so for me net-ssh looks fine, but sshkit looks to be broken.

@jasonperrone what do you think? 
@mattbrictson  FYI

https://github.com/capistrano/sshkit/blob/952d3be0d7032e6e6c5273672601a976d1977cc0/lib/sshkit/backends/netssh/known_hosts.rb#L88

**Comment by mfazekas** [comment]
@jasonperrone can you please open an issue for this in ssh-kit?

**Comment by jasonperrone** [comment]
Will do.

**Comment by mattbrictson** [comment]
Fixed in [sshkit 1.22.1](https://github.com/capistrano/sshkit/releases/tag/v1.22.1).

**Comment by jasonperrone** [comment]
@mfazekas do you want to try un-yanking 7.2.2?

**Comment by dentarg** [comment]
Or release 7.2.3? (not sure you can un-yank a version?

Also, maybe chill on the yank "button" in the future? `yank` isn't for removing buggy versions: https://github.com/rubygems/rubygems/issues/1506#issuecomment-188496149

**Comment by mfazekas** [comment]
Released https://rubygems.org/gems/net-ssh/versions/7.2.3 

sorry about the yank
