### ISSUE TITLE
Client encryption client preferences is empty (none)

### ISSUE THREAD

**Issue by jbwl** [net-ssh/net-ssh#956]
### Expected behavior

Connection to the server should be made with SSH-Key authentication

### Actual behavior

Connection fails because negotiation of algorithms fails - **client encryption preferences are empty**

```zsh
/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/net-ssh-7.2.3/lib/net/ssh/transport/algorithms.rb:415:in `negotiate': could not settle on encryption_client algorithm (Net::SSH::Exception)
Server encryption_client preferences: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
Client encryption_client preferences: 
```

### System configuration

- net-ssh version: 7.2.3
- Ruby version: 3.3.4
- installed via `gem install kamal` -> Kamal 2.0 gem which depends on Net:SSH
- Mac OS 15.0 Sequoia on Apple Silicon

### Example App

```ruby
require 'net/ssh'
Net::SSH.start(HOSTNAME, USERNAME) do |ssh|
    puts ssh.exec!('date')
    puts "Logging out..."
 end
```

### workaround

Using option  **append_all_supported_algorithms = true** makes the script succeed:

```ruby
require 'net/ssh
Net::SSH.start(HOSTNAME, USERNAME, { append_all_supported_algorithms: true } ) do |ssh|
    puts ssh.exec!('date')
    puts "Logging out..."
  end
```

But it is not possible to set it via Kamal config

**Comment by owst** [comment]
I hit the same issue, and dug into it a bit. It seems that by default net-ssh will load client cipher preferences from 

https://github.com/net-ssh/net-ssh/blob/d9549e4226dc3aed12efcca24a8b6d349143f398/lib/net/ssh/config.rb#L47

and for me on macOS 15.2, my `/etc/ssh/ssh_config` includes (transitively) the file`/etc/ssh/crypto.conf` which has the line `Ciphers ^aes128-gcm@openssh.com,aes256-gcm@openssh.com`. Those ciphers are used as the default client encryption preference, but aren't supported in net-ssh 7.2, so the client encryption preferences end up empty and the negotiation fails. 

`man apple_ssh_and_fips` references `/etc/ssh/crypto.conf` and says it was introduced in macOS 15, which explains why I don't recall hitting this problem on an earlier macOS versions.

Upgrading to 7.3.0 means the GCM ciphers are supported and the negotiation succeeds.

**Comment by noelblaschke** [comment]
For all users that may have upgraded to macOS 15 (Sequoia) instead of a fresh installment:

https://keith.github.io/xcode-man-pages/apple_ssh_and_fips.7.html

**Comment by remd** [comment]
According to https://documentation.ubuntu.com/server/explanation/crypto/openssh-crypto-configuration/ the inclusion of the line from `/etc/ssh/crypto.conf` should not override all ciphers available to ssh:

> ^ The specified ciphers will be placed at the beginning of the default set. For example, PubkeyAcceptedAlgorithms ^ssh-ed25519,ecdsa-sha2-nistp256 will move both signature algorithms to the start of the set.

I am on a fresh installation of MacOS Sequoia 15.6. `/etc/ssh/ssh_config` transitively includes `/etc/ssh/crypto.conf` which is a symlink to `/etc/ssh/crypto/apple.conf` on my machine:
```
⏺ ~ % grep -v '^#' /etc/ssh/ssh_config
Include /etc/ssh/ssh_config.d/*
⏺ ~ % ls /etc/ssh/ssh_config.d
100-macos.conf
⏺ ~ % cat /etc/ssh/ssh_config.d/100-macos.conf
Host *
  SendEnv LANG LC_*
  Include /etc/ssh/crypto.conf
⏺ ~ % ls -la /etc/ssh/crypto.conf
lrwxr-xr-x@ 1 root  wheel  17 Aug 20 12:56 /etc/ssh/crypto.conf -> crypto/apple.conf
⏺ ~ % cat /etc/ssh/crypto/apple.conf
# Default algorithms favoring higher-performance FIPS algorithms
# in most cases.
#
# To configure these SSH algorithms, run the following command:
#
# sudo ln -fs crypto/apple.conf /etc/ssh/crypto.conf
#
Ciphers ^aes128-gcm@openssh.com,aes256-gcm@openssh.com
KexAlgorithms ^ecdh-sha2-nistp256
MACs ^hmac-sha2-256-etm@openssh.com,hmac-sha2-256
⏺ ~ % ls ~/.ssh/config
ls: /Users/remd/.ssh/config: No such file or directory
⏺ ~ % ssh -G localhost | grep ciphers
ciphers aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr
```

`chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr` are still offered as client encryption ciphers and should be used by net-ssh. The presence of `/etc/ssh/crypto/apple.conf` doesn't exclude them from being chosen. 

Does net-ssh support prepending SSH configuration options?
