### ISSUE TITLE
net-ssh 7.3.0 - Method redefinition warnings for #nonce= in gcm_cipher.rb?

### ISSUE THREAD

**Issue by gdtrfb55** [net-ssh/net-ssh#957]
### Expected behavior

Warning-free execution of a simple net-ssh code block. This block has run successfully and without warnings for years.

### Actual behavior

After installing the 7.3.0 gem, the code block still runs successfully, but now emits the following warnings:

```
/home/jack/.rvm/gems/ruby-3.3.5/gems/net-ssh-7.3.0/lib/net/ssh/transport/gcm_cipher.rb:177: warning: method redefined; discarding old nonce=
/home/jack/.rvm/gems/ruby-3.3.5/gems/net-ssh-7.3.0/lib/net/ssh/transport/gcm_cipher.rb:177: warning: method redefined; discarding old nonce=
```

### System configuration

net-ssh version: 7.3.0
ruby version: 3.3.5

### Example App

The code block in question is:

```
class PiSSHExec
  require 'net/ssh'

  HOST = 'rpi4'.freeze
  USER = 'pi'.freeze
  KEYS = ['/home/jack/.ssh/id_ed25519'].freeze

  def self.run(cmd)
    Net::SSH.start(HOST, USER, keys: KEYS, timeout: 5) do |ssh|
      ssh.exec!(cmd)
    end
  end
end
```

The code is invoked at startup as follows:

`@leases = PiSSHExec.run('cat /etc/dnsmasq.local/leases')`

I believe a warning is emitted each time a net-ssh method is called, i.e., when the `#start` and `#exec!` methods are executed.

Like I said, I've had zero problems with this code block until the release of 7.3.0. I've been unable to find another method definition for `#nonce=` (using `grep -rn 'def nonce=' net-ssh-7.3.0/lib/*`), other than the one at line 177 of `gcm_cipher.rb`. My code does use an ed25519 key, which requires the presence of the `ed25519` and `bcrypt_pbkdf` gems. But, grepping the `lib` dirs of both of those gems did not reveal a definition of `#nonce=`.

Thanks in advance.

**Comment by gdtrfb55** [comment]
Set `$VERBOSE` to `false` in my script, and the warnings went away (as expected). Best practice? Probably not, but the script seems to run as it should. Like I said previously, though, I've been using net-ssh in this script for years, with the `$VERBOSE` flag set, and never encountered these warnings. So, heads up...

**Comment by martin-dorey-hv** [comment]
As the next poor sap, I appreciate the writeup, but I'd have let it languish unclosed if no fix were forthcoming.  Being Closed didn't stop me googling it up but, somewhat impolite though it would have seemed, I might even have gone so far as to reopen it, except that apparently I "do not have permissions to reopen this issue".

> unable to find another method definition for #nonce=

Oh yes, how perplexing...  ah, this seems to do the trick:
```
devadmin@pot:~$ diff -u /var/lib/gems/3.1.0/gems/net-ssh-7.3.0/lib/net/ssh/transport/gcm_cipher.rb{.orig,}
--- /var/lib/gems/3.1.0/gems/net-ssh-7.3.0/lib/net/ssh/transport/gcm_cipher.rb.orig	2025-07-28 23:18:37.606269672 +0100
+++ /var/lib/gems/3.1.0/gems/net-ssh-7.3.0/lib/net/ssh/transport/gcm_cipher.rb	2025-07-28 23:19:01.522436511 +0100
@@ -13,7 +13,7 @@
 
             attr_reader   :cipher
             attr_reader   :key
-            attr_accessor :nonce
+            attr_reader   :nonce
 
             #
             # Semantically gcm cipher supplies the OpenSSL iv interface with a nonce
devadmin@pot:~$ 
```
Looks like the conflicts-with-self code arrived with the first version of this file in https://github.com/net-ssh/net-ssh/commit/a280273ecb8fd0a4c959977020b50a58a7ee454b by @flux-benj.

**Comment by flux-benj** [comment]
https://github.com/net-ssh/net-ssh/pull/960 fixes this issue 🙈
